add index and style files
mate-academy/layout_moyo-header pull request #1025
Opened 2021-10-28 18:26 UTC by romafanasiev

- [DEMO LINK](https://romafanasiev.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://romafanasiev.github.io/layout_moyo-header/report/html_report/)

2021-11-02 12:40 UTC, vkryvytskyy reviewed
![image](https://user-images.githubusercontent.com/38065883/139848227-cb529a1b-9adf-415a-96fb-575bd1bc3342.png)
Не вижу где заканчивается header, и подчеркивание под активной ссылкой выглядит не так, как должно

2021-11-02 12:42 UTC, vkryvytskyy requested changes

2021-11-02 12:42 UTC, vkryvytskyy commented on src/index.html
> +      <a href="#" class="logo"><img src="images/logo.png" alt="Logo: four letters meaning the name of the store MOYO"></a>
```suggestion
      <a href="#" class="logo">
        <img src="images/logo.png" alt="Logo: four letters meaning the name of the store MOYO">
      </a>
```
Новый тег с новой строки

2021-11-02 12:42 UTC, vkryvytskyy commented on src/style.css
> +  width: 36.6px;
Тебе не надо использовать дробные значения и явно устанавливать ширину этого элемента, чтобы он адаптировался под ширину любой ссылки, а не только этой

2021-11-02 12:42 UTC, vkryvytskyy commented on src/style.css
> +  padding-bottom: 56px;
Padding ему тоже не нужен

2021-11-02 12:42 UTC, vkryvytskyy commented on src/style.css
> +  margin: 0 -10px;
Тебе не нужны тут отрицательные марджины

2021-11-02 12:50 UTC, romafanasiev commented
> ![image](https://user-images.githubusercontent.com/38065883/139848227-cb529a1b-9adf-415a-96fb-575bd1bc3342.png) Не вижу где заканчивается header, и подчеркивание под активной ссылкой выглядит не так, как должно

Что имеется в виду 'Не вижу где заканчивается header'?

2021-11-03 19:17 UTC, vkryvytskyy approved these changes

2021-11-03 19:17 UTC, vkryvytskyy commented on src/index.html
> +              class="nav__link">
```suggestion
            <a 
              href="#" 
              data-qa="hover"
              class="nav__link"
            >
```

2021-11-03 19:17 UTC, vkryvytskyy commented on src/style.css
> +  top: 56px;
bottom: 0

2021-11-03 19:17 UTC, vkryvytskyy commented on src/style.css
> +  border-bottom: 4px solid #00acdc;
```suggestion
  height: 4px;
  background-color: #00acdc;
```

2022-08-02 17:37 UTC, closed without merging