moyo header layout solution
mate-academy/layout_moyo-header pull request #1045
Opened 2021-11-17 13:57 UTC by levix2l

- [DEMO LINK](https://levix2l.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://levix2l.github.io/layout_moyo-header/report/html_report/)

2021-11-18 11:56 UTC, danheim requested changes

2021-11-18 11:56 UTC, danheim commented on src/style.css
> +.header {
add box-shadow from the markup

2021-11-18 11:56 UTC, danheim commented on src/style.css
> +  padding: 10px 50px;
remove paddings from logo, add paddings to the header

2021-11-18 11:56 UTC, danheim commented on src/style.css
> +  margin-right: 50px;
remove margin-right, add padding to the header

2021-11-18 11:56 UTC, danheim commented on src/style.css
> +  display: flex;
you don't need display-flex

2021-11-19 12:50 UTC, danheim requested changes
Never leave commented code

2021-11-22 09:03 UTC, ArtemTopolskyi approved these changes

2021-11-22 09:03 UTC, ArtemTopolskyi commented on src/style.css
> +  margin-left: 20px;
убери этот маржен для первого элемента и тесты пройдут

2026-06-20 16:12 UTC, closed without merging