MOYO navbar created
mate-academy/layout_moyo-header pull request #1085
Opened 2021-11-19 11:37 UTC by gnosis-frog

- [DEMO LINK](https://gnosis-frog.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://gnosis-frog.github.io/layout_moyo-header/report/html_report/)

2021-11-19 12:17 UTC, Elena-brv requested changes
- this indent shouldn't be here
![image](https://user-images.githubusercontent.com/64437769/142621495-611c1245-25ad-45ff-a78d-5b50f51ac119.png)

- checklist about links

2021-11-19 15:53 UTC, Elena-brv requested changes
- indents should be the same 
![image](https://user-images.githubusercontent.com/64437769/142651086-9986d6ef-1c0f-44d8-8084-b83103a1f854.png)

2021-11-19 15:53 UTC, Elena-brv commented on src/style.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap");
add fonts via a link in the `<head>`

2021-11-19 15:53 UTC, Elena-brv commented on src/style.css
> +  float: left;
use display: flex for .header instead of this property

2021-11-22 10:24 UTC, Denchepornyuk approved these changes

2023-02-08 11:04 UTC, closed without merging