Header and styles were added
mate-academy/layout_moyo-header pull request #1096
Opened 2021-11-27 11:49 UTC by Mazyt81

2021-11-29 13:21 UTC, vkryvytskyy requested changes

2021-11-29 13:21 UTC, vkryvytskyy commented on src/style.css
> +  margin: 0 10px;
Указывай отступы с одной стороны, например margin-right 20px всем кроме последнего ребена

2021-11-29 13:21 UTC, vkryvytskyy commented on src/style.css
> +}
Это можно не указывать

2021-11-29 13:21 UTC, vkryvytskyy commented on src/style.css
> +  position: absolute;
Зачем лого позиционировать абсолютно?

2021-11-29 13:21 UTC, vkryvytskyy commented on src/style.css
> +  justify-content: flex-end;
Укажи padding 0 50, и space-between

2022-01-26 13:39 UTC, aliceblunt8 requested changes

2022-01-26 13:39 UTC, aliceblunt8 commented on src/index.html
> +          <li class="nav__list">
elements should be inside block (nav)

```suggestion
      <nav class="nav">
        <ul class="nav__list">
          <li class="nav__item">
```

2022-01-26 13:39 UTC, aliceblunt8 commented on src/style.css
> +  justify-content: flex-end;
remove, you don't need it

2022-01-26 13:39 UTC, aliceblunt8 commented on src/style.css
> +  align-items: center;
same, it's useless, there will be no change if you get rid of it

```suggestion
```

2022-01-26 13:39 UTC, aliceblunt8 commented on src/index.html
> +      <a href="#home" class="logo"></a>
add image with logo inside link

2022-01-26 13:39 UTC, aliceblunt8 commented on src/style.css
> +  justify-content: space-between;
add align-items: center to center everything vertically (logo too)

2022-01-26 13:39 UTC, aliceblunt8 commented on src/style.css
> +  top: 10px;
```suggestion
  height: 40px;
  width: 40px;
```

2022-01-26 13:39 UTC, aliceblunt8 commented on src/style.css
> +  top: 10px;
add image to html

2022-01-28 12:34 UTC, danylo-onishchuk approved these changes

2024-06-11 15:37 UTC, closed without merging