moyo
mate-academy/layout_moyo-header pull request #1158
Opened 2021-12-28 19:59 UTC by Havrysh

- [DEMO LINK](https://Havrysh.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Havrysh.github.io/layout_moyo-header/report/html_report/)

2021-12-29 18:12 UTC, aliceblunt8 requested changes
please deploy your project, demo link doesn't working

2021-12-30 12:58 UTC, varseniuk requested changes
Риска під активним компонентом не відображається.
Також зверни увагу, що тести не задеплоїлись.
Спробуй поміняти налаштування, як у наведеному відео, запусти тести ще раз і знову задеплой

![image](https://user-images.githubusercontent.com/66570142/147753980-e776535f-6d37-4013-9489-aed320133c4f.png)


https://user-images.githubusercontent.com/66570142/147753990-3f13fb80-be5e-4147-bfdd-3bf1572fe339.mov

2021-12-30 12:58 UTC, varseniuk commented on src/index.html
> +            <li class="nav-item">
```suggestion
            <li class="nav_item">
```
Назви класів мають бути в одному стилі. Якщо ти скріщт використовуєш нижнє підкреслювання, то і тут потрібно

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  height: 60px;
Ці стилі стосуються класу .container
Варто прописати їх там і уникати селектори по тегам, де можна використати класи

2021-12-30 12:58 UTC, varseniuk commented on src/index.html
> +              class="photo"
клас photo ніде не використовується. Навіщо він?

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  width: 250;
Чому 250?
Просто задай 
```
  height: 40px;
  width: 40px;
```

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  justify-content: right;
```suggestion
  justify-content: center;
```
Тобі ж потрібно розмістити зображення по центру цього контейнера

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  margin-right: 3%;
```suggestion
  margin-right: 3%;
```
Звідки така цифра? 🤔 
В хедера мають бути відступи по 50px по бокам. Отже можна це зробити, задавши там бокові падінги 50 пікселів

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  right: 10%;
```suggestion
  right: 10%;
```
не варто тут викоритовувати відсоткові значення.
Має бути відступ 50 пікселів

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +}
```suggestion
.nav-item {
  position: relative;
  margin: 0 10px;
}
```
Ці всі стилі не потрібні. Для nav_item варто лише задати position: relative (щоб можна було задати позиціонування для :before) та відступи між самимим елементами. 
Розмір контенту визначається елементами `a`, які знаходяться всередині

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  text-align: center;
```suggestion
  display: block;
  height: 60px;
  line-height: 60px;
  text-align: center;
```
Як варіант - контент всередині можна центрувтаи за допомогою
```

display:flex;
justify-content: center;
align-items: center;
```

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  color: blue;
Колір має бути не blue. Зверни увагу, який колір на макеті

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +.is-active:active::before {
```suggestion
.is-active::before {
```
Ти стилізуєш саме елемент, в якого є клас 'is-active'
Стану active в даному завданні немає

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  content: " ";
```suggestion
  content: "";
```

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  height: 5px;
```suggestion
  height: 4px;
```

По дизайну 4 пікселі

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +  top: 4.6em;
```suggestion
  bottom: 0;
```

2021-12-30 12:58 UTC, varseniuk commented on src/style.css
> +
має ще бути border-radius. Зверни увагу на макет

2021-12-30 13:20 UTC, Havrysh commented
> 
<img width="1440" alt="Screen Shot 2021-12-30 at 3 18 04 PM" src="https://user-images.githubusercontent.com/21238164/147755554-51fd9cd6-8900-4db3-af45-f265220dacc6.png">

при нажатии активна

2021-12-30 13:24 UTC, Havrysh commented on src/style.css
> +  height: 60px;
у меня ломается всё и сьездает навигация при этом как вы сказали

2021-12-30 13:29 UTC, Havrysh commented
> Риска під активним компонентом не відображається. Також зверни увагу, що тести не задеплоїлись. Спробуй поміняти налаштування, як у наведеному відео, запусти тести ще раз і знову задеплой
> 
> ![image](https://user-images.githubusercontent.com/66570142/147753980-e776535f-6d37-4013-9489-aed320133c4f.png)
> 
<img width="1440" alt="Screen Shot 2021-12-30 at 3 28 17 PM" src="https://user-images.githubusercontent.com/21238164/147756261-30eb1d4e-2a4d-4558-896a-8e7551648029.png">

>  ghpages.fix.mov
<img width="1440" alt="Screen Shot 2021-12-30 at 3 28 31 PM" src="https://user-images.githubusercontent.com/21238164/147756262-d12b851a-4ade-4f6d-8f3a-9e31e0a6a5f9.png">

всё-сделал как и показано ввидео

2021-12-30 13:31 UTC, Havrysh commented on src/index.html
> +            <li class="nav-item">
ок

2021-12-30 13:31 UTC, Havrysh commented on src/index.html
> +              class="photo"
ок

2021-12-30 13:35 UTC, Havrysh commented on src/style.css
> +  justify-content: right;
cделал но логотип не так близко к левой части как на макете, за то в центре контейнера

2021-12-30 13:40 UTC, Havrysh commented on src/style.css
> +.is-active:active::before {
ок

2021-12-30 13:40 UTC, Havrysh commented on src/style.css
> +  width: 250;
ок

2021-12-30 15:23 UTC, varseniuk requested changes
Більшість коментарів залишились без уваги.
- бокові падінги для хедера
- колір при хавері та is-active
- позиціонування НЕ у відсотках
- is-active має бути постійно, а не тільки при кліку
- висота і border-radius для риски

Тести так і не задеплоїлись. Потрібно внести зміни, запустити npm test, після чого пушити все на гітхаб і знову запускати npm run deploy

2021-12-30 15:23 UTC, varseniuk commented on src/style.css
> +  height: 60px;
Тоді взагалі варто прибрати цей div з класом контейнер і стилізувати сам header (задавши йому відповідний клас)
Лишній контейнер тут не потрібен

2021-12-30 15:23 UTC, varseniuk commented on src/style.css
> +  margin-right: 3%;
Комент залишився без уваги

2021-12-30 15:23 UTC, varseniuk commented on src/style.css
> +  right: 10%;
Комент залишився без уваги

2021-12-30 15:23 UTC, varseniuk commented on src/style.css
> +  color: blue;
Комент залишився без уваги

2021-12-30 15:23 UTC, varseniuk commented on src/style.css
> +  height: 5px;
Комент залишився без уваги

2021-12-30 15:23 UTC, varseniuk commented on src/style.css
> +  top: 4.6em;
Комент залишився без уваги

2021-12-30 15:23 UTC, varseniuk commented on src/style.css
> +
Комент залишився без уваги

2021-12-31 12:19 UTC, varseniuk requested changes
Тести не задеплоїлись і у нас немає можливості перевірити, чи дійсно все відповідає макету. В усіх завданнях (де є test report link) завжди потрібно слідкувати, щоб тести задеплоїлись і лінка працювала.

Також зверни увагу, що хедер відображається коректно тільки на широких екранах, а при адаптиві починаються проблеми. Для списку також варто додати display: flex, а якщо центрувати елементи через line-height - ми отримаємо некоректний результат, коли слово розтягується на два рядки.

Також, якби ти запустив тести, то міг би помітити, що у елементів меню повинні бути відступи в 20px ЛИШЕ МІЖ СОБОЮ. Тобто, у першого елементу не повинно бути 10px зліва, а у останннього не повинно бути 10px справа.

2021-12-31 12:19 UTC, varseniuk commented on src/style.css
> +  line-height: 60px;
Ось приклад, чому центрувати текст за допомогою line-height - погана ідея. Якщо в нас текст складається із двох слів і переноситься на два рядка, то и отримуємо ДВА line-height 60px, що в сумі складає 120px. А це не той результат, який очікується. Тому краще центрувати за допомогою 
```
display:flex;
justify-content: center;
align-items: center;
```
<img width="1242" alt="Снимок экрана 2021-12-31 в 13 56 38" src="https://user-images.githubusercontent.com/66570142/147822431-f461b96f-1e2b-458a-b5a9-c63444062bfb.png">

2021-12-31 12:19 UTC, varseniuk commented on src/style.css
> +  /* top: 4.6em; */
```suggestion
```
коменти потрібно видаляти

2021-12-31 12:19 UTC, varseniuk commented on src/style.css
> +  margin: 0 10px;
Зараз у всіх елементів є відступи по 10 пікселів із обох боків. Але якщо запустити тести, то ми побачиимо, що по бокам у крайніх елементів не повинно бути відступів. Мають бути тільки відступи 20px між алементами, але не по краям.
Це вирішується, наприклад, якщо для `.nav_item` задати `margin-right: 20px`, а для останнього елементу `nav_item:last-child`  обнуляти марджини (margin-right: 0)

2021-12-31 15:02 UTC, varseniuk approved these changes
🔥 🧨 👍

2021-12-31 15:02 UTC, varseniuk commented on src/style.css
> +}
```suggestion
.is-active,
.nav_link:hover {
  color: #00acdc;
}
```
Це можна об'єднати

2024-12-11 13:42 UTC, closed without merging