Created MOYO navigation tab
mate-academy/layout_moyo-header pull request #1164
Opened 2022-01-03 18:46 UTC by OstTomash

https://osttomash.github.io/layout_moyo-header/
https://OstTomash.github.io/layout_moyo-header/report/html_report/

2022-01-04 15:30 UTC, vkryvytskyy requested changes

2022-01-04 15:30 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://OstTomash.github.io/layout_moyo-header/)
![image](https://user-images.githubusercontent.com/38065883/148082196-4d2ad34c-ec5a-4de2-bdf6-5f0aa24a2fbd.png)
В дизайне у хедера есть box-shadow, тут я его не вижу

2022-01-04 15:30 UTC, vkryvytskyy commented on readme.md
> +- [TEST REPORT LINK](https://OstTomash.github.io/layout_moyo-header/report/html_report/)
https://user-images.githubusercontent.com/38065883/148082324-924d1be2-64f8-40f9-acd9-476431e66fba.mov

Твой хедер по высоте меньше чем нужно, или есть какие-то отступы, которые делают его меньше и обрезают подчеркивание у is-active

2022-01-04 15:30 UTC, vkryvytskyy commented on src/style.css
> +  transform: translateX(-100%);
Зачем это? тут не нужен transform

2022-01-04 15:30 UTC, vkryvytskyy commented on src/style.css
> +  width: 37px;
Ширина должна адаптироваться под ссылки, под которыми она будет появляться, а не быть фиксированно 37px

2022-01-04 15:30 UTC, vkryvytskyy commented on src/style.css
> +  padding: 22.5px 0;
Дробные паддинги устанавливать не надо, округляй значения

2022-01-04 15:30 UTC, vkryvytskyy commented on src/style.css
> +  width: 753px;
Такую ширину тоже не надо явно указывать, пусть хедер растягивается как ему будет нужно

2022-01-04 15:30 UTC, vkryvytskyy commented on src/style.css
> +  padding: 5px 0;
Зачем тут паддинги по пять пикселей сверху?

2022-01-05 12:36 UTC, varseniuk approved these changes

2023-11-09 16:25 UTC, closed without merging