First commit Header Moyo
mate-academy/layout_moyo-header pull request #1177
Opened 2022-01-14 20:01 UTC by valdesin

Помогите вроде сделал все правильно но тесты не проходят

2022-01-17 15:58 UTC, varseniuk requested changes
Якщо подивитись на тести, то головні відмінності - це те, що логотип знаходиться всередині навігації, хоча мав би бути ззовні. А також елементи навігації мають мати висоту.

https://user-images.githubusercontent.com/66570142/149802197-119b8ba3-8c22-42b9-a9f5-cc809865153d.mov

2022-01-17 15:58 UTC, varseniuk commented on src/index.html
> +          <img src="./images/logo.png" alt="logo" class="logo-site">
Логотип має бути за межами навігації

2022-01-17 15:58 UTC, varseniuk commented on src/style.css
> +  display: flex;
```suggestion
.nav {
  display: flex;
```

2022-01-17 15:58 UTC, varseniuk commented on src/style.css
> +  width: 36px;
```suggestion
  width: 100%;
```
Цей елемент має бути на всю ширину лінка

2022-01-17 15:58 UTC, varseniuk commented on src/style.css
> +  bottom: -23px;
```suggestion
  bottom: 0;
```
Звідки така цифра? Цей  псевдо-елемент має бути знизу елемента nav__link

2022-01-17 15:58 UTC, varseniuk commented on src/style.css
> +  margin-top: 10px;
```suggestion
```
Це не потрібно

2022-01-17 15:58 UTC, varseniuk commented on src/style.css
> +  margin-top: 6px;
```suggestion
```
Це не потрібно

2022-01-17 15:58 UTC, varseniuk commented on src/style.css
> +  line-height: 23px;
```suggestion
```
Це не потрібно. Навігаційний лінк має мати висоту 60px і вся ця висота повинна бути клікабельна.
Цього можна досягти, задавши для .nav__link
```
display: flex;
height: 60px;
justify-content: center;
align-items: center;
```

2022-01-17 15:58 UTC, varseniuk commented on src/style.css
> +  margin-right: 20px;
margin-right має бути у всіх елементів, окрім останнього

2022-01-17 15:58 UTC, varseniuk commented on src/style.css
> +.is-active::after {
<img width="1774" alt="Снимок экрана 2022-01-17 в 17 52 04" src="https://user-images.githubusercontent.com/66570142/149802281-2ad361d2-e8d9-4e4b-ab51-09c2ee6dc914.png">

Зараз цей after чомусь знаходиться взагалі за межами html

2022-01-17 20:34 UTC, valdesin commented on src/style.css
> +.is-active::after {
Дуже вам дякую!
Все круто об’яснили !

2022-01-18 12:39 UTC, vkryvytskyy approved these changes

2022-01-18 12:39 UTC, vkryvytskyy commented on src/index.html
> +            <a href="#laptopAndPC" class="nav__link" data-qa="hover">НОУТБУКИ И КОМПЬЮТЕРЫ</a>
Тут текст пиши обычным кеглем, а через css делай uppercase

2022-03-04 18:09 UTC, closed without merging