mojo
mate-academy/layout_moyo-header pull request #1230
Opened 2022-02-06 19:40 UTC by irkruts

2022-02-07 11:27 UTC, danylo-onishchuk requested changes
на тестах видно, что многие стили не совпадают

посмотри внимательно на макет в фигме

2022-02-10 10:10 UTC, danylo-onishchuk requested changes
<img width="1440" alt="Screenshot 2022-02-10 at 12 09 46" src="https://user-images.githubusercontent.com/78209611/153385233-0bcfa313-8854-4b07-a67a-ec47b91b8493.png">
 что то пошло не так
 
 + жирность текста и размер псевдоэлемента не соответвует дизайну

2022-02-12 19:15 UTC, irkruts commented
все равно несколько миллиметров не проходит...не могу понять в чем дело

2022-02-14 15:00 UTC, varseniuk requested changes

2022-02-14 15:00 UTC, varseniuk commented on src/style.css
> +  right: 22.5px;
Чому така цифра? Справда від навігації має бути 50 пікселів. Це можна зробити падінгами для хедера

2022-02-14 15:00 UTC, varseniuk commented on src/style.css
> +  top: 10px;
Для позиціонування самого логотипа можна використати 
display: flex 
justify-content: center
align-items: center

2022-02-14 15:00 UTC, varseniuk commented on src/style.css
> +  padding-bottom: 22.5px;
Задай висоту 60 пікселів і центруй контент за допомогою властивостей флексбокса (як я писав вище)

2022-02-14 15:00 UTC, varseniuk commented on src/style.css
> +}
```suggestion
```
Це не потрібно

2022-02-14 15:00 UTC, varseniuk commented on src/index.html
> +          <li>
Для li також створи клас, і зроби відступи між ними у 20 пікселів. Зверни увагу, що відступи мають бути тільки МІЖ елементами, а не з обох боків (тобто у першого не має бути відступів зліва, а у останнього - справа)

2023-04-14 20:44 UTC, closed without merging