Initial commit#2
mate-academy/layout_moyo-header pull request #1260
Opened 2022-02-16 13:24 UTC by plankton9991

- [DEMO LINK](https://plankton9991.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://plankton9991.github.io/layout_moyo-header/report/html_report/)

2022-02-18 15:28 UTC, illiarerun requested changes
Good job, now let's work on fixes:

2022-02-18 15:28 UTC, illiarerun commented on src/style.css
> +  /* height: 60px; */
don't leave commented code
```suggestion
```

2022-02-18 15:28 UTC, illiarerun commented on src/style.css
> +  padding: 23px 0 19px;
links shouldn't have horizontal paddings, it should be a margin for list items

2022-02-18 15:28 UTC, illiarerun commented on src/style.css
> +  transform: translateY(19px);
bottom: 0?

2022-02-18 15:28 UTC, illiarerun commented on src/style.css
> +}
combine these selectors

2022-02-22 10:30 UTC, MaksimusCRS approved these changes

2023-03-10 14:43 UTC, closed without merging