moyo-header is done
mate-academy/layout_moyo-header pull request #1360
Opened 2022-04-06 12:40 UTC by MaxShylo

- [DEMO LINK](https://MaxShylo.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://MaxShylo.github.io/layout_moyo-header/report/html_report/)

2022-04-07 09:27 UTC, ArtemTopolskyi requested changes
![image](https://user-images.githubusercontent.com/57574816/162167468-1cc162f9-35e4-4713-97f4-db6e265a9989.png)
хедер не должен быть захардкожен по ширине, он должен растягиваться на всю ширину экрана

2022-04-07 09:27 UTC, ArtemTopolskyi commented on src/index.html
> +                APPLE
```suggestion
                Apple
```
используй text-transform: uppercase

2022-04-07 09:27 UTC, ArtemTopolskyi commented on src/style.css
> +  /* border: 5px solid orange; */
не оставляй комментарии в коде

2022-04-11 18:26 UTC, marina-tilniak approved these changes

2022-09-17 14:24 UTC, closed without merging