moyo-header
mate-academy/layout_moyo-header pull request #1364
Opened 2022-04-15 11:21 UTC by p-omogit-e

[DEMO LINK](https://p-omogit-e.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://p-omogit-e.github.io/layout_moyo-header/report/html_report/)

2022-04-15 19:04 UTC, ArturErmolenko requested changes
add all files with changes, you add just image

<img width="1502" alt="Screenshot 2022-04-15 at 22 03 34" src="https://user-images.githubusercontent.com/94292654/163621839-a83fcd43-bb85-4e1b-aa8f-6905491af9c3.png">

2022-04-18 11:44 UTC, ArtemTopolskyi requested changes

2022-04-18 11:44 UTC, ArtemTopolskyi commented on src/index.html
> +          <a  href="url" class="item">Samsung</a>
```suggestion
          <a href="url" class="item">
            Samsung
          </a>
```

2022-04-18 11:44 UTC, ArtemTopolskyi commented on src/style.css
> +  padding-right: 30px;
думаю это должны быть margin

2022-04-18 11:44 UTC, ArtemTopolskyi commented on src/style.css
> +  position: absolute;
здесь нет необходимости в absolute. Можешь просто сделать картинку и container элементами flex блока - и тогда они сами встанут в один ряд. + необходимо задать эту блоку align-items: space-between

2022-04-18 18:15 UTC, p-omogit-e commented
Перепрошую за три коміта, міняла комп'ютер, тож була проблема з тим щоб запушити.

2022-04-19 10:14 UTC, ArtemTopolskyi approved these changes
Коммиты не проблема, можно делать столько, сколько тебе необходимо

2022-04-19 10:14 UTC, ArtemTopolskyi commented on src/index.html
> +        class="moyo-img">
```suggestion
        class="moyo-img"
      >
```

2022-04-19 10:14 UTC, ArtemTopolskyi commented on src/style.css
> +  content: " ";
```suggestion
  content: "";
```

2022-04-19 10:14 UTC, ArtemTopolskyi commented on src/style.css
> +  content: " ";
```suggestion
  content: "";
```

2025-12-17 21:24 UTC, closed without merging