Solution Andriy Bahayev
mate-academy/layout_moyo-header pull request #1367
Opened 2022-04-17 12:53 UTC by ABfeMate

- [DEMO LINK](https://ABfeMate.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://ABfeMate.github.io/layout_moyo-header/report/html_report/)

2022-04-18 12:58 UTC, aliceblunt8 requested changes
please deploy to GitHub pages (npm run deploy)

2022-04-21 07:59 UTC, Bohdan-Maksymiuk requested changes
Remove default visited styles for links
and remove title...

2022-05-04 06:38 UTC, ABfeMate commented
For some reason I cannot push send my code. I see this error message.
![image](https://user-images.githubusercontent.com/92830530/166633151-afd460dc-d0d1-4ec4-957b-814199696755.png)

2022-05-05 11:22 UTC, Bohdan-Maksymiuk requested changes
`git push origin develop -f`
If you have some troubles you can describe problem in fe_chat or your personal chat with mentors. You have no need to wait for review if solution is not ready

2022-05-13 19:47 UTC, marina-tilniak requested changes

2022-05-13 19:47 UTC, marina-tilniak commented on src/index.html
> +          <li class="nav__item">
there shouldn’t be empty line between child and parent element

2022-05-13 19:47 UTC, marina-tilniak commented on src/style.css
> +.nav__list .nav__item:first-child .nav__link {
don't use so much specificity

2022-05-13 19:47 UTC, marina-tilniak commented on src/style.css
> +.nav__list .nav__link {
```suggestion
.nav__link {
```

2022-05-17 07:50 UTC, Bohdan-Maksymiuk approved these changes
Great job 👏 
Keep going!

2022-05-17 07:50 UTC, Bohdan-Maksymiuk commented on src/index.html
> +            >
```suggestion
            <a
              href="#laptops"
              class="nav__link"
              data-qa="hover"
            >
```

2024-04-22 13:31 UTC, closed without merging