Develop
mate-academy/layout_moyo-header pull request #1383
Opened 2022-04-26 11:24 UTC by Yevhen-Pavlovskyi

2022-04-26 19:36 UTC, ArturErmolenko requested changes
demo link не работает ты делал деплой?

2022-04-27 12:24 UTC, Yevhen-Pavlovskyi commented
- [DEMO LINK](https://yevhen-pavlovskyi.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://yevhen-pavlovskyi.github.io/layout_moyo-header/report/html_report/)

2022-04-27 12:24 UTC, Yevhen-Pavlovskyi commented
[99bdfe6](https://github.com/mate-academy/layout_moyo-header/pull/1383/commits/99bdfe6643c2305c9a71a5ad8d86f391f0638c2f)

2022-04-28 21:09 UTC, vkryvytskyy requested changes

2022-04-28 21:09 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://yevhen-pavlovskyi.github.io/layout_moyo-header/)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/38065883/165846142-030a2b3d-2f0a-42fa-8fce-f90e3a71170f.png">
Box-shadow что-то не видно у хедера

2022-04-28 21:09 UTC, vkryvytskyy commented on src/index.html
> +          class="logo__img"
```suggestion
            src="images/logo.png"
            alt="logo"
            class="logo__img"
```

2022-04-28 21:09 UTC, vkryvytskyy commented on src/index.html
> +            <a href="#" class="menu__link" data-qa="hover">Ноутбуки и компьютеры</a>
```suggestion
            <a href="#" class="menu__link" data-qa="hover">
              Ноутбуки и компьютеры
            </a>
```

2022-04-29 06:46 UTC, closed without merging