add header
mate-academy/layout_moyo-header pull request #1399
Opened 2022-05-03 14:58 UTC by Pavlo000

- [DEMO LINK](https://Pavlo000.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Pavlo000.github.io/layout_moyo-header/report/html_report/)

2022-05-04 12:43 UTC, Olexandr6 requested changes
Smt went wrong with tests🤔, but the code is okay.
Check comments👇

2022-05-04 12:43 UTC, Olexandr6 commented on src/index.html
> +    <!-- <h1>Moyo header</h1> -->
Don't leave redundant comments in your code; delete this

2022-05-04 12:43 UTC, Olexandr6 commented on src/index.html
> +          <li class="item item-2">
Add blank line between `li` elements
```suggestion
          </li>
          
          <li class="item item-2">
```

2022-05-04 12:43 UTC, Olexandr6 commented on src/style.css
> +}
```suggestion
.logo {
  display: flex;
  padding: 10px 0;
  margin-left: 50px;
}
```

2022-05-06 15:13 UTC, mykola-koval approved these changes

2022-05-06 15:13 UTC, mykola-koval commented on src/style.css
>  /* Styles go here */
```suggestion
```

2022-05-06 15:13 UTC, mykola-koval commented on src/index.html
> +          <li class="list__item list_item-7">
```suggestion
          </li>
          
          <li class="list__item list_item-7">
```

2024-11-26 17:24 UTC, closed without merging