MOYO header
mate-academy/layout_moyo-header pull request #1406
Opened 2022-05-04 11:08 UTC by vsupruniuk

- [DEMO LINK](https://vsupruniuk.github.io/layout_moyo-header/)
- [DEMO LINK](https://vsupruniuk.github.io/layout_moyo-header/)

2022-05-04 12:48 UTC, Olexandr6 requested changes
You didn't add the` TEST REPORT LINK`, so you need to add it.
Also, check comments below👇

2022-05-04 12:48 UTC, Olexandr6 commented on src/index.html
> +    <header class="header">
Blank line isn't needed here
```suggestion
    <header class="header">
```

2022-05-04 12:48 UTC, Olexandr6 commented on src/index.html
> +          <li class="nav__item">
Add a blank line between `li` elements in all places in your code

2022-05-04 12:48 UTC, Olexandr6 commented on src/style.css
> +}
`.is-active` class has the same, let's combine them

2022-05-06 16:21 UTC, mykola-koval requested changes
<img width="567" alt="image" src="https://user-images.githubusercontent.com/90685701/167172812-350d4889-1bed-4ec4-902d-7e205c038a41.png">

2022-05-10 06:49 UTC, illiarerun requested changes
GJ, now let's work on some fixes:

2022-05-10 06:49 UTC, illiarerun commented on src/style.css
> +  top: 20px;
or `bottom: 0`

2022-05-10 06:49 UTC, illiarerun commented on src/style.css
> +}
same here
```suggestion
```

2022-05-10 06:49 UTC, illiarerun commented on src/style.css
> +  margin-right: 50px;
your tests didn't pass because nav shouldn't have any outside margins, make a 50px horizontal padding for your header instead
```suggestion
```

2022-05-10 06:49 UTC, illiarerun commented on src/style.css
> +  font-size: 12px;
put this on link class, not the nav one

2022-05-10 06:49 UTC, illiarerun commented on src/style.css
> +  padding: 0;
body doesn't have default paddings
```suggestion
```

2022-05-10 06:49 UTC, illiarerun commented on src/index.html
> +            >
Fix your indentation here. If you have more than 3 attributes, then each of them should be on a newline
```suggestion
            <a 
              href="#PC"
              data-qa="hover"
              class="nav__link"
            >
```

2022-05-10 19:09 UTC, jstmpelowycz commented on src/style.css
> +  height: min-content;
You don't need it

2022-05-10 19:14 UTC, jstmpelowycz requested changes
A few things to fix, and you're done

2022-05-10 19:14 UTC, jstmpelowycz commented on src/style.css
> +  list-style: none;
Should you add `list-style` to `<a>`?

2022-05-10 19:14 UTC, jstmpelowycz commented on src/style.css
> +  padding-right: 50px;
Let's simplify it
```suggestion
  padding: 0 50px;
```

2022-05-10 19:14 UTC, jstmpelowycz commented on src/style.css
> +  flex-direction: column;
Do you need it here?

2022-05-11 06:35 UTC, jstmpelowycz approved these changes

2022-05-11 07:15 UTC, illiarerun approved these changes

2022-05-11 09:03 UTC, jstmpelowycz approved these changes
Re-approve

2022-12-05 08:02 UTC, Olexandr6 approved these changes

2024-01-12 12:31 UTC, closed without merging