Moyo header
mate-academy/layout_moyo-header pull request #1477
Opened 2022-05-12 13:20 UTC by maksym-rudenko90

- [DEMO LINK](https://maksym-rudenko90.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://maksym-rudenko90.github.io/layout_moyo-header/report/html_report/)

2022-05-13 18:36 UTC, vkryvytskyy requested changes

2022-05-13 18:36 UTC, vkryvytskyy commented on src/index.html
> +    <header class="header">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/38065883/168345833-9402ba94-5033-49c9-988e-3a78d4dc98ba.png">
Полоска выглядит не так, как в дизайне

2022-05-13 18:36 UTC, vkryvytskyy commented on src/index.html
> +    <header class="header">
https://user-images.githubusercontent.com/38065883/168345944-332f4c44-6046-4c57-a3aa-8742c9cd4937.mov

Разницу думаю видно

2022-05-13 18:36 UTC, vkryvytskyy commented on src/style.css
> +}
Подчеркивание для первой ссылки делай через элемент after

2022-05-17 10:51 UTC, ArtemTopolskyi approved these changes

2022-05-23 06:35 UTC, closed without merging