MOYO menu
mate-academy/layout_moyo-header pull request #1679
Opened 2022-07-13 12:52 UTC by anna-kolmakova

- [DEMO LINK](https://anna-kolmakova.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://anna-kolmakova.github.io/layout_moyo-header/report/html_report/)

2022-07-13 13:03 UTC, danylo-onishchuk requested changes

2022-07-13 13:03 UTC, danylo-onishchuk commented on src/style.css
> +  height: 60px;
странно задавать для body высоту

2022-07-13 13:03 UTC, danylo-onishchuk commented on src/style.css
> +  width: 100%;
а разве по дефолту у body ширина не 100%?

2022-07-13 13:10 UTC, closed without merging

2022-10-11 08:16 UTC, anna-kolmakova commented
Спасибо, исправила)

Ср, 13 июля 2022 г. в 16:03, Danylo Onishchuk ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/style.css
> <https://github.com/mate-academy/layout_moyo-header/pull/1679#discussion_r920051855>
> :
>
> > @@ -1 +1,73 @@
>
> -/* Styles go here */
>
> +body {
>
> +  background-color: #fff;
>
> +  width: 100%;
>
> +  height: 60px;
>
>
> странно задавать для body высоту
> ------------------------------
>
> In src/style.css
> <https://github.com/mate-academy/layout_moyo-header/pull/1679#discussion_r920052111>
> :
>
> > @@ -1 +1,73 @@
>
> -/* Styles go here */
>
> +body {
>
> +  background-color: #fff;
>
> +  width: 100%;
>
>
> а разве по дефолту у body ширина не 100%?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_moyo-header/pull/1679#pullrequestreview-1037323235>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ2HEQG5SAHZ3HFNLXTCTLTVT25BBANCNFSM53OTZ3EA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>