task Moyo header
mate-academy/layout_moyo-header pull request #1702
Opened 2022-07-14 13:13 UTC by vladgusakovskiy

2022-07-14 15:03 UTC, danylo-onishchuk requested changes
<img width="1430" alt="Screenshot 2022-07-14 at 18 03 03" src="https://user-images.githubusercontent.com/78209611/179014116-e7a0edf1-26f0-4329-b2af-518560abe15d.png">

это не то что на макете и тесты показывают, что не так

2022-07-15 10:06 UTC, danylo-onishchuk requested changes
![Uploading Screenshot 2022-07-15 at 13.06.23.png…]()


ширина должна быть 100%

2022-07-15 14:22 UTC, danylo-onishchuk requested changes
не хватает линии под header

2022-07-18 06:16 UTC, dellachaise reviewed
Good job 👍

2022-07-18 06:19 UTC, dellachaise approved these changes

2024-01-15 20:10 UTC, closed without merging