need help
mate-academy/layout_moyo-header pull request #1766
Opened 2022-07-30 15:38 UTC by yurii-filiushkin

- [DEMO LINK](https://yurii-filiushkin.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://yurii-filiushkin.github.io/layout_moyo-header/report/html_report/)

Допоможіть, будь ласка, з нижньою синьою лінією. І не проходять інші тести.

2022-07-30 15:56 UTC, yurii-filiushkin commented
У фігмі СМАРФОН замість смарТфон

2022-08-07 10:37 UTC, yurii-filiushkin commented
- [DEMO LINK](https://yurii-filiushkin.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://yurii-filiushkin.github.io/layout_moyo-header/report/html_report/)

не проходять тести

2022-08-08 14:23 UTC, alexandra-protyanova requested changes
Если ты про тесты на гит хабе, то это не страшно

2022-08-08 14:23 UTC, alexandra-protyanova commented on src/index.html
> +        >
```suggestion
        <img 
          src="images/logo.png" 
          alt="logo" 
          class="image"
        >
```

2022-08-08 14:23 UTC, alexandra-protyanova commented on src/index.html
> +          <li class="list-item">
вот так нужно отформатировать все `li`

2022-08-08 14:23 UTC, alexandra-protyanova commented on src/style.css
> +  /* padding-inline-start: 0; */
delete

2022-08-08 15:14 UTC, yurii-filiushkin commented
Все працює

2024-03-05 09:36 UTC, closed without merging