Develop
mate-academy/layout_moyo-header pull request #1796
Opened 2022-08-09 11:24 UTC by F-u-n-H-o-u-s-e

- [DEMO LINK](https://F-u-n-H-o-u-s-e.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://F-u-n-H-o-u-s-e.github.io/layout_moyo-header/report/html_report/)

2022-08-09 14:26 UTC, Bohdan-Maksymiuk requested changes
header should be stretched in height by its content (you may use paddings for nav__items)

2022-08-09 14:26 UTC, Bohdan-Maksymiuk commented on src/style.css
> +  height: 60px;
```suggestion
  width: 100%;
```
do not hardcode height and width

2022-08-09 14:26 UTC, Bohdan-Maksymiuk commented on src/style.css
> +}
use class selectors

2022-08-09 14:26 UTC, Bohdan-Maksymiuk commented on src/style.css
> +}
use class selectors

2022-08-09 14:26 UTC, Bohdan-Maksymiuk commented on src/style.css
> +}*/
delete comments

2022-08-16 09:02 UTC, ArturErmolenko requested changes
Header must have 100 % width
<img width="1512" alt="Screenshot 2022-08-16 at 12 00 19" src="https://user-images.githubusercontent.com/94292654/184840778-327fc054-4e40-4dac-a1db-93e5f0d15b42.png">

2.Uppercase letters for nav__list are made with styles, not hardcoded into html (you should have usual text with first uppercase letter in html)

2022-08-18 04:30 UTC, F-u-n-H-o-u-s-e commented on src/index.html
> +            <a href="#" class="item SMARTPHONES">SMARTPHONES</a>
Made.

2022-08-25 08:55 UTC, closed without merging