commit1
mate-academy/layout_moyo-header pull request #1985
Opened 2022-09-20 15:28 UTC by Gintako666

- [DEMO LINK](https://Gintako666.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Gintako666.github.io/layout_moyo-header/report/html_report/)

Не понимаю что хочет от меня тест который по пиксель пёрфекту. Попытался сделать как по нормальному, то-есть при ховере на линк у него менялся цвет и появлялась полосочка внизу. Подскажите что нужно сделать)

2022-09-21 08:51 UTC, alexandra-protyanova requested changes
у тебя не работают ссылочки, нужно запустить команду `npm run deploy`

2022-09-22 10:00 UTC, alexandra-protyanova requested changes
Let us fix tests, looks like u failed in margins of elements

2022-09-22 10:00 UTC, alexandra-protyanova commented on src/style.css
> +  font-style: normal;
it is a default property, remove it

2022-09-26 10:04 UTC, valerii-derkach requested changes

2022-09-26 10:04 UTC, valerii-derkach commented on src/index.html
> +      </nav>
всередині навігації повинен бути список з лінками
```
<ul>
  <li>
    <a>
```

2022-09-28 07:58 UTC, valerii-derkach requested changes

2022-09-29 09:13 UTC, valerii-derkach requested changes
якщо є труднощі з реалізацією - пиши в чат

2022-09-29 09:13 UTC, valerii-derkach commented on src/style.css
> +  margin: 0 auto;
```suggestion

```

використовуй флекс

2022-09-29 09:13 UTC, valerii-derkach commented on src/style.css
> +}
для чого така велика специфічність? це нечитабельно

2022-09-29 09:13 UTC, valerii-derkach commented on src/style.css
> +  padding: 22.5px 0;
викорисовуй цілі числа

2022-10-03 12:09 UTC, alexandra-protyanova requested changes
у тебя не правильные марджины для элементов, посмотри эти отступы в фигме, и давай добавим `box-shadow` под навигацией как в макете

2022-10-03 13:17 UTC, alexandra-protyanova requested changes
у тебя должно быть по 50px марджинов, визуально у тебя намного больше

2022-10-03 18:21 UTC, Gintako666 commented
![image](https://user-images.githubusercontent.com/100702900/193650156-20118add-54dd-4194-9a5d-b57d751c83f3.png)

Отступы по 50 пх. Или я не о тои подумал?

2022-10-04 10:39 UTC, alexandra-protyanova approved these changes
По коду всё гуд, я думаю у тебя проект не передеплоился и там ещё марджины по 70

2022-10-04 10:39 UTC, alexandra-protyanova commented on src/style.css
> +  padding-right: 50px;
```suggestion
  padding: 0 50px;
```

2022-10-04 10:39 UTC, alexandra-protyanova commented on src/style.css
> +  font-family: "Roboto", sans-serif;
```suggestion
  font-family: inherit;
```

2026-09-10 20:16 UTC, closed without merging