Develop
mate-academy/layout_moyo-header pull request #2083
Opened 2022-10-05 12:39 UTC by maks-golovatyuk

https://maks-golovatyuk.github.io/layout_moyo-header/
https://maks-golovatyuk.github.io/layout_moyo-header/report/html_report/

2022-10-06 09:13 UTC, liliia-livandovskaya requested changes
Pay attention to the tests. They show you the difference between your code and the mockup.
<img width="993" alt="Screenshot 2022-10-06 at 12 12 40" src="https://user-images.githubusercontent.com/104769168/194274523-922634e0-f1c0-4582-838b-c0123bdcf7cf.png">

2022-10-12 10:38 UTC, Anastasiia-Svintsova requested changes
Good job! Just fix links issues

2022-10-12 10:38 UTC, Anastasiia-Svintsova commented on src/index.html
> +            <a href="*" class="nav__link is-active">
all your links lead to 404 page( Rewrite href atribute in all links
```suggestion
            <a href="#Apple" class="nav__link is-active">
```

2022-10-12 10:38 UTC, Anastasiia-Svintsova commented on src/style.css
> +  padding: 0;
delete this, it's useless here

2022-10-14 09:47 UTC, Anastasiia-Svintsova requested changes
Links still lead to 404 page. did you deploy after the changes?

2022-10-18 18:38 UTC, qoa11a requested changes
I see the same problems that were mentioned in previous comments.
Make sure you've deployed your changes. Otherwise, please, fix these mistakes, redeploy site and request review again.

2023-01-28 11:23 UTC, closed without merging