First commit
mate-academy/layout_moyo-header pull request #2098
Opened 2022-10-13 19:52 UTC by panianchuk

2022-10-16 08:45 UTC, SanyaBratashchuk requested changes
Fix your structure, it should look like `<header><img /><nav><ul><li><a> </a> </li>....</ul></nav></header>`

2022-10-16 08:45 UTC, SanyaBratashchuk commented on src/style.css
> +}
do not apply any styles to the `*` selector except `box-sizing`

2022-10-16 08:45 UTC, SanyaBratashchuk commented on src/index.html
> +      <div class="container">
why do you need this container?

2022-10-16 08:45 UTC, SanyaBratashchuk commented on src/index.html
> +    </div>
Why do you need this?

2022-10-16 09:24 UTC, panianchuk commented
changed

2022-10-16 15:02 UTC, ivanchuk-yurii requested changes

2022-10-16 15:02 UTC, ivanchuk-yurii commented on src/style.css
> +  padding: 0;
`body` doesn't have default padding

2022-10-16 15:02 UTC, ivanchuk-yurii commented on src/style.css
> +  height: 60px;
don't hardcode height

2022-10-17 12:07 UTC, alexandra-protyanova requested changes
add demo and test report links

2022-10-17 18:14 UTC, panianchuk commented
https://panianchuk.github.io/layout_moyo-header/
https://panianchuk.github.io/layout_moyo-header/report/html_report/

2022-10-18 10:50 UTC, alexandra-protyanova approved these changes

2023-12-29 10:51 UTC, closed without merging