Solution
mate-academy/layout_moyo-header pull request #2102
Opened 2022-10-17 12:12 UTC by IhorPokr

- [DEMO LINK](https://IhorPokr.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://IhorPokr.github.io/layout_moyo-header/report/html_report/)

2022-10-17 12:15 UTC, IhorPokr commented
I don't understand why mine - [DEMO LINK](https://IhorPokr.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://IhorPokr.github.io/layout_moyo-header/report/html_report/) do not work

2022-10-21 07:10 UTC, alexandra-protyanova requested changes
Your demo doesn't work as well, run `npm test` and `npm run deploy`

2022-10-21 18:02 UTC, IhorPokr commented
> Your demo doesn't work as well, run `npm test` and `npm run deploy`

Do I need to make a new pool request?

2022-10-31 09:48 UTC, alexandra-protyanova approved these changes
GJ!

2022-10-31 09:48 UTC, alexandra-protyanova commented on src/style.css
> +  font-style: normal;
it is default value u can delete it

2022-11-21 09:57 UTC, closed without merging