Develop
mate-academy/layout_moyo-header pull request #2143
Opened 2022-10-26 13:18 UTC by olenitut

- [DEMO LINK](https://olenitut.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://olenitut.github.io/layout_moyo-header/report/html_report/)

2022-10-27 12:43 UTC, stanislav-topikha requested changes
Visited links should be black
![image](https://user-images.githubusercontent.com/99331793/198286823-344a71f7-769e-4339-82a0-cb7115025b2f.png)

this one should not be blue always
![image](https://user-images.githubusercontent.com/99331793/198287386-cf519bb4-4b2d-4286-bf69-80c89e014698.png)

2022-10-27 12:43 UTC, stanislav-topikha commented on src/style.css
> +  font-family: "Roboto", sans-serif;
fallback fonts

2022-10-27 12:43 UTC, stanislav-topikha commented on src/style.css
> +  box-sizing: border-box;
set it in * selector

2022-10-27 12:43 UTC, stanislav-topikha commented on src/style.css
> +}
```suggestion
  justify-content: space-between;
}
```

2022-10-27 12:43 UTC, stanislav-topikha commented on src/style.css
> +  list-style: none;
```suggestion
.nav-list {
  margin: 0;
  padding: 0;
  display: flex;
  list-style: none;
```

2022-10-28 12:07 UTC, stanislav-topikha requested changes
visited links should be black 
![image](https://user-images.githubusercontent.com/99331793/198583389-b1a6c2cf-8c04-4f64-960a-10c648fc5e44.png)

2022-10-28 13:12 UTC, stanislav-topikha requested changes

2022-10-28 13:12 UTC, stanislav-topikha commented on src/style.css
> +}
```suggestion
* {
   box-sizing: border-box;
}

html {
  font-family: "Roboto", Helvetica, sans-serif;
}

body {
  marging: 0;
}
```

2022-10-28 13:12 UTC, stanislav-topikha commented on src/style.css
> +  color: #00acdc;
lets add var for repetitive color value

2022-10-29 08:37 UTC, SanyaBratashchuk requested changes

2022-10-29 08:37 UTC, SanyaBratashchuk commented on src/style.css
> +}
Fix it

2022-10-29 08:37 UTC, SanyaBratashchuk commented on src/style.css
> +  height: 60px;
do not hardcode height, use vertical paddings

2022-10-29 12:50 UTC, AlisaVlasova approved these changes

2023-10-18 14:06 UTC, closed without merging