Header was created
mate-academy/layout_moyo-header pull request #2308
Opened 2022-11-26 16:59 UTC by NazariiAlieksieiev

- [DEMO LINK](https://NazariiAlieksieiev.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://NazariiAlieksieiev.github.io/layout_moyo-header/report/html_report/)

2022-11-27 21:46 UTC, OlEzhA0 requested changes
Hey ✋🏼 
I left few comments, please check it

2022-11-27 21:46 UTC, OlEzhA0 commented on src/index.html
> +      <a href="#home" class="logo">
class `header__logo`, it's element of `header` block

2022-11-27 21:46 UTC, OlEzhA0 commented on src/style.css
> +  align-content: center;
it's redundant style

2022-11-27 21:46 UTC, OlEzhA0 commented on src/style.css
> +  flex-wrap: wrap;
are you sure we need `flex-wrap` style here?

2022-11-27 21:46 UTC, OlEzhA0 commented on src/style.css
> +  list-style: none;
you already added `type="none"` directly to tag

2022-11-27 21:46 UTC, OlEzhA0 commented on src/style.css
> +  padding-bottom: 23px;
why do we need `padding-bottom` here?

2022-11-28 17:53 UTC, Viktor-Kost requested changes
Hello!
A little changes needed

2022-11-28 17:53 UTC, Viktor-Kost commented on src/index.html
> +          <li  class="nav__item">
```suggestion
          <li class="nav__item">
```

2022-11-28 17:53 UTC, Viktor-Kost commented on src/style.css
> +.logo {
Do you use this class?

2022-11-28 18:04 UTC, NazariiAlieksieiev commented on src/style.css
> +.logo {
Ohhh.. One minute i will delete it.

2022-11-29 10:13 UTC, Virass approved these changes

2024-07-27 11:25 UTC, closed without merging