moyo header
mate-academy/layout_moyo-header pull request #2410
Opened 2022-12-12 20:44 UTC by andrii-petruk

[DEMO LINK](https://andrii-petruk.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://andrii-petruk.github.io/layout_moyo-header/report/html_report/)

2022-12-14 11:35 UTC, Bohdan-Maksymiuk requested changes
Good job 👍 
Pls, check my comments
Also check design - there is box-shadow for header

2022-12-14 11:35 UTC, Bohdan-Maksymiuk commented on src/style.css
> +  color: #00acdc;
move repeated colors to variables

2022-12-14 11:35 UTC, Bohdan-Maksymiuk commented on src/style.css
> +.logo {
```suggestion
.header__logo {
```
isn't this logo an element of header?

2022-12-18 11:30 UTC, DarkMistyRoom requested changes

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
```suggestion
            <a 
              href="#apple" 
              class="nav__link is-active"
            >
              Apple
            </a>
```

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
Please fix it everywhere

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
```suggestion
            <a href="#samsung" class="nav__link">Samsung</a>
```

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
You don't have to place less then 3 attributes on a new line

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
```suggestion
            <a 
              href="#laptops&computers" 
              class="nav__link" 
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
but if you do it, place each attribute on a separate line

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/index.html
> +          <li class="nav__item">
Add empty lines between multiline sibling blocks of HTML

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/style.css
> +  --color: #00acdc;
move `--color` to the `:root`

2022-12-18 11:30 UTC, DarkMistyRoom commented on src/style.css
> +  margin: 0;
why do you need to do it twice? `margin: 0;`

2022-12-20 17:48 UTC, SanyaBratashchuk approved these changes

2024-07-12 02:55 UTC, closed without merging