Solution
mate-academy/layout_moyo-header pull request #2426
Opened 2022-12-15 16:45 UTC by Khabailiuk

- [DEMO LINK](https://<your_account>.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://<your_account>.github.io/layout_moyo-header/report/html_report/)

2022-12-15 16:51 UTC, Khabailiuk commented
- [DEMO LINK](https://Khabailiuk.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Khabailiuk.github.io/layout_moyo-header/report/html_report/)

2022-12-16 08:54 UTC, TarasHoliuk commented
Pay attention to code style:
![image](https://user-images.githubusercontent.com/86923089/208060765-50176ec2-0f36-4232-86d3-940144842566.png)

2022-12-16 09:02 UTC, TarasHoliuk requested changes
Fix TEST REPORT LINK

2022-12-16 09:02 UTC, TarasHoliuk commented on src/index.html
> +      <nav class="nav">
what have you deployed?
![image](https://user-images.githubusercontent.com/86923089/208061811-e2991309-ad2c-4081-914d-dda4ac3f1619.png)

it doesn't match your code. please, deploy the latest version

2022-12-16 09:02 UTC, TarasHoliuk commented on src/style.css
> +line-height: 60px;
it's better to add padding instead

2022-12-16 09:02 UTC, TarasHoliuk commented on src/style.css
> +display: block;
remove it

2022-12-16 09:02 UTC, TarasHoliuk commented on src/style.css
> +font-style: normal;
redundant

2022-12-16 09:02 UTC, TarasHoliuk commented on src/style.css
> +flex-wrap: wrap;
why do you need it?

2022-12-18 13:04 UTC, closed without merging