header was created
mate-academy/layout_moyo-header pull request #2437
Opened 2022-12-19 16:13 UTC by vanyachyzh

- [DEMO LINK](vanyachyzh.github.io/layout_moyo-header/)
- [TEST REPORT LINK](vanyachyzh.github.io/layout_moyo-header/report/html_report/)

2022-12-20 02:49 UTC, OlEzhA0 commented
Preview links unavailable, please don't remove `https://` from the begging of the link in the Readme.md file

2022-12-20 03:00 UTC, OlEzhA0 requested changes
Hey! Please check my comments

2022-12-20 03:00 UTC, OlEzhA0 commented on src/style.css
> +  background-color: #00acdc;
move repeating color to the variable

2022-12-20 03:00 UTC, OlEzhA0 commented on src/style.css
> +  top: 56px;
```suggestion
  bottom: 0;
```

2022-12-20 03:00 UTC, OlEzhA0 commented on src/style.css
> +  display: block;
```suggestion
  left: 0;
```

2022-12-21 13:39 UTC, liliia-livandovskaya commented on src/index.html
> +      <a class="img-link" href="#home">
```suggestion
    <header class="header">
      <a class="img-link" href="#home">
```

2022-12-21 13:39 UTC, liliia-livandovskaya commented on src/index.html
> +          </li>
```suggestion
          <li class="nav-list__item">
            <a href="#" class="is-active link">Apple</a>
          </li>
          
          <li class="nav-list__item">
            <a href="#" class="link">Samsung</a>
          </li>
```

2022-12-21 13:40 UTC, liliia-livandovskaya approved these changes
Great job! 👍 Pay attention to the code style

2024-03-07 18:46 UTC, closed without merging