moyo commit
mate-academy/layout_moyo-header pull request #2458
Opened 2022-12-28 13:17 UTC by Faridun92

2022-12-29 09:05 UTC, DarkMistyRoom requested changes
- There is some box-shadow on the mockup

![image](https://user-images.githubusercontent.com/98764641/209927743-a97aefa1-5c56-4bd5-93c7-d7c89462ec76.png)

- The logo should be a link too
![image](https://user-images.githubusercontent.com/98764641/209928105-239ed05b-c2a4-4b7d-b72a-fb41a9c6d7fb.png)

2022-12-29 09:05 UTC, DarkMistyRoom commented on src/index.html
> +          <li class="nav__item">
Add empty lines between multiline sibling blocks of HTML

2022-12-29 09:05 UTC, DarkMistyRoom commented on src/style.css
> +  width: 37px;
```suggestion
  width: 100%;
```

2022-12-29 09:05 UTC, DarkMistyRoom commented on src/style.css
> +  width: 37px;
to make it work correctly with all links

2022-12-29 09:05 UTC, DarkMistyRoom commented on src/style.css
> +  height: 60px;
don't set the height to the header. set it to link, then you won't need to set 100% to all descendants

2022-12-29 17:29 UTC, loralevitska requested changes
almost done)

2022-12-29 17:29 UTC, loralevitska commented on src/index.html
> +      >
```suggestion
<a href="#" class="logo">
   <img 
        src="./images/logo.png" 
        alt="Moyo logo"
        class="logo__image"
    >
</a>
      
```

2022-12-29 17:29 UTC, loralevitska commented on src/index.html
> +      >
Not fixed previous comment 
![image](https://user-images.githubusercontent.com/70009205/209987815-ab588d01-468e-4851-9a07-1e0d1d9b70c1.png)
Please fix it

2022-12-29 17:29 UTC, loralevitska commented on src/index.html
> +        </ul>
"Add empty lines between multiline sibling blocks of HTML" - yes, you did right (but not for first and last element)

```suggestion
        <ul class="nav__list">
          <li class="nav__item">
            <a href="#apple" class="nav__link is-active">Apple</a>
          </li>

          <li class="nav__item">
            <a href="#samsung" class="nav__link">Samsung</a>
          </li>

          <li class="nav__item">
            <a href="#smartphones" class="nav__link">Smartphones</a>
          </li>

          <li class="nav__item">
            <a href="#laptops&computers" class="nav__link"
              data-qa="hover"
            >
              Laptops & computers
            </a>
          </li>

          <li class="nav__item">
            <a href="#gadgets" class="nav__link">Gadgets</a>
          </li>

          <li class="nav__item">
            <a href="#tablets" class="nav__link">Tablets</a>
          </li>

          <li class="nav__item">
            <a href="#photo" class="nav__link">Photo</a>
          </li>

          <li class="nav__item">
            <a href="#video" class="nav__link">Video</a>
          </li>
        </ul>
```

2022-12-30 17:27 UTC, SanyaBratashchuk approved these changes

2022-12-30 17:27 UTC, SanyaBratashchuk commented on src/style.css
> +  height: 60px;
Do not harcode height use vertical paddings instead

2026-08-18 22:34 UTC, closed without merging