MOYO header
mate-academy/layout_moyo-header pull request #2488
Opened 2023-01-07 12:36 UTC by SergeyShapovalenko

[DEMO LINK](https://SergeyShapovalenko.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://SergeyShapovalenko.github.io/layout_moyo-header/report/html_report/)

2023-01-08 10:43 UTC, SanyaBratashchuk requested changes

2023-01-08 10:43 UTC, SanyaBratashchuk commented on src/index.html
> +        </a>
```suggestion
        <a 
          href="#laptops_computers" 
          data-qa="hover" 
          class="top-link"
        >
            Laptops & Computers
        </a>
```

2023-01-08 10:43 UTC, SanyaBratashchuk commented on src/index.html
> +</html>
```suggestion
</html>    

```

2023-01-08 10:43 UTC, SanyaBratashchuk commented on src/style.css
> +}
Do not apply any rules to the `*` selector except `box-sizing`

2023-01-08 10:43 UTC, SanyaBratashchuk commented on src/style.css
> +  font-family: Roboto, Arial, Helvetica, sans-serif;
move font-family to the `hmtl` tag selector

2023-01-08 10:43 UTC, SanyaBratashchuk commented on src/index.html
> +        <a href="#apple" class="is-active">Apple</a>
```suggestion
        <a href="#apple" class="top-link is-active">Apple</a>
```

2023-01-10 16:08 UTC, agniya-i approved these changes

2023-11-15 11:46 UTC, closed without merging