header was created
mate-academy/layout_moyo-header pull request #2544
Opened 2023-01-22 13:30 UTC by BilokonYaroslav

- [DEMO LINK](https://BilokonYaroslav.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://BilokonYaroslav.github.io/layout_moyo-header/report/html_report/)

2023-01-22 13:41 UTC, mykhalenych requested changes
Your links aren't working

2023-01-22 13:41 UTC, mykhalenych commented on src/style.css
> +a,
use classnames instead of tag selector

2023-01-22 13:41 UTC, mykhalenych commented on src/style.css
> +  font-family: "Roboto", sans-serif;
move to html selector, also font-weight

2023-01-22 13:41 UTC, mykhalenych commented on src/style.css
> +  font-weight: 500;
and delete here

2023-01-22 14:08 UTC, BilokonYaroslav commented
Links are not working but I dont know why
Mentor right now try to help me
Have some problem with 'npm run deploy'

2023-01-22 15:36 UTC, BilokonYaroslav commented
Links are working!

2023-01-23 13:55 UTC, Virass approved these changes

2023-12-10 12:25 UTC, closed without merging