created layout_moyo-header
mate-academy/layout_moyo-header pull request #2600
Opened 2023-01-29 06:11 UTC by romahawk

Completed **"Moyo header"** task from Mate Academy HTML + CSS Advanced / Flexbox Module
- [DEMO LINK](https://romahawk.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://romahawk.github.io/layout_moyo-header/report/html_report/)

2023-01-30 08:04 UTC, polosanya requested changes
Almost done!

2023-01-30 08:04 UTC, polosanya commented on src/index.html
> +          class="img">
```suggestion
        <img 
          src="./images/logo.png" 
          alt="logo" 
          class="img"
        >
```
Closing tag should be just under the opening

2023-01-30 08:04 UTC, polosanya commented on src/index.html
> +            </a>
```suggestion
            <a 
              href="#" 
              class="nav__link" 
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```
Fix all cases

2023-01-30 08:04 UTC, polosanya commented on src/style.css
> +.header,
You already have styles for the header above. Move margin there and place styles for body near the html

2023-01-30 17:10 UTC, Viktor-Kost approved these changes
Nice!

2023-01-31 07:53 UTC, romahawk commented
> Nice!

Thank you:)

2026-02-08 11:04 UTC, closed without merging