Add 2 header
mate-academy/layout_moyo-header pull request #2785
Opened 2023-03-02 20:20 UTC by genakorytov

Can you suggest what needs to be fixed?

2023-03-03 09:13 UTC, OlEzhA0 requested changes
we need only 1 header. that stretched for full width. and don't change background, just leave default white
<img width="1258" alt="Screenshot 2023-03-03 at 11 12 28 AM" src="https://user-images.githubusercontent.com/60295799/222680061-4c098bc0-a60e-48e6-8c51-7b0427061165.png">

2023-03-03 09:13 UTC, OlEzhA0 commented on readme.md
> +- [TEST REPORT LINK](https://genakorytov.github.io/layout_moyo-header/report/html_report/)
copy this links to your PR description

2023-03-03 09:13 UTC, OlEzhA0 commented on src/index.html
> +        >
```suggestion
        <img
          class="icon" 
          src="images/logo.png" 
          alt="Moyo"
        >
```

2023-03-06 19:18 UTC, genakorytov commented
- [DEMO LINK](https://genakorytov.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://genakorytov.github.io/layout_moyo-header/report/html_report/)

2023-03-06 19:47 UTC, VitaliyBondarenko1982 requested changes
please first of all compare design and your solution.
also compare in test reference and test example.
if you will have any questions - feel free to ask in fe_chat3

![Screenshot from 2023-03-06 21-45-49](https://user-images.githubusercontent.com/33029864/223214786-09b52d19-6f72-4c7c-b582-30d05193045e.png)

2023-03-06 19:47 UTC, VitaliyBondarenko1982 commented on src/index.html
> +        >
logo should be before nav

2023-03-06 19:47 UTC, VitaliyBondarenko1982 commented on src/index.html
> +            <a href="http://SAMSUNG.html">SAMSUNG</a>
```suggestion
            <a href="#samsung">Samsung</a>
```
please fix all links

2023-03-06 19:47 UTC, VitaliyBondarenko1982 commented on src/style.css
> +  src: url(Roboto/Roboto-Black.ttf);
where did the Roboto-Black.ttf file come from?
wrong path to file

2023-03-20 16:16 UTC, closed without merging