Develop
mate-academy/layout_moyo-header pull request #2800
Opened 2023-03-06 11:15 UTC by PavlovaOlena

[DEMO LINK](https://PavlovaOlena.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://PavlovaOlena.github.io/layout_moyo-header/report/html_report/)

2023-03-06 14:04 UTC, qoa11a requested changes
Add a box-shadow to header according to the design.

2023-03-06 14:04 UTC, qoa11a commented on src/style.css
> +  border: 0;
Why do you reset padding and border? Do body and HTML have them?

2023-03-06 14:49 UTC, witflash requested changes
Let's try to fix all tests.

1. Add padding for the `<a>` elements instead of `<li>`.
![image](https://user-images.githubusercontent.com/25587299/223143687-326de61e-5861-4e80-bffe-689d2bfb7e35.png)

2. Use `position: absolute` for the `after` pseudo element and `relative` for the `<a>`.

3. Remove the left padding for the first item and the right padding for the last item:
![image](https://user-images.githubusercontent.com/25587299/223144401-f7d21d0a-d01e-452a-b97a-9e257d292cfc.png)

If you still have any questions feel free to ask in `fe_chat` in Slack.

2023-03-06 14:49 UTC, witflash commented on src/index.html
> +            <label>
You don't need an additional `label` wrapper here.
Follow the next structure:
```
<ul>
  <li>
    <a>
  </li>
  ...
  <li>
    <a>
  </li>
</ul>
```

2023-03-06 14:49 UTC, witflash commented on src/index.html
> +        <label class="link__home nav__item">
Don't use `label` here. Use `div` instead if you need any wrapper.

2023-03-06 14:49 UTC, witflash commented on src/index.html
> +        <nav class="navigation">
It should be `<nav class="nav">` if you use `nav__list` naming for BEM elements.

2023-03-06 14:49 UTC, witflash commented on src/index.html
> +                <a class="link__nav" href="#apple">Apple</a>
According to the BEM methodology, this element class name should be `nav__link`.

2023-03-06 17:29 UTC, agniya-i requested changes
There are still some failed tests, try to fix them 

Follow previous comments and pay attention that link should not have left/right padding, and should have the same height as the container
<img width="94" alt="Screenshot 2023-03-06 at 18 23 03" src="https://user-images.githubusercontent.com/32853034/223185390-4d30198b-a89a-4e50-aecf-f2f8b7092dac.png">

2023-03-09 07:40 UTC, polosanya requested changes

2023-03-09 07:40 UTC, polosanya commented on src/style.css
> +  width: 641px;
Same here. I don't think that it's a good idea to hardcore this value. Just add the correct margins between nav items

2023-03-09 12:22 UTC, anstsot requested changes
Looks good from code perspective but you still have failed tests. Try to check the font

2023-03-09 12:45 UTC, anstsot approved these changes
The tests seems to be failed still but I'm approving the PR

2023-03-09 13:18 UTC, closed without merging