request
mate-academy/layout_moyo-header pull request #2872
Opened 2023-03-18 17:58 UTC by karynabotvina

[DEMO LINK](https://karynabotvina.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://karynabotvina.github.io/layout_moyo-header/report/html_report/)

2023-03-18 18:32 UTC, ivanchuk-yurii requested changes

2023-03-18 18:32 UTC, ivanchuk-yurii commented on src/index.html
> +          <li><a href="">Apple</a></li>
```suggestion
          <li><a href="#">Apple</a></li>
```
add classes so you can select them in css instead of tags

2023-03-18 18:32 UTC, ivanchuk-yurii commented on src/index.html
> +        <img src="images/logo.png" alt="">
set alt attribute

2023-03-18 18:32 UTC, ivanchuk-yurii commented on src/style.css
> +    display: flex;
```suggestion
  display: flex;
```
2 spaces

2023-03-18 18:32 UTC, ivanchuk-yurii commented on src/style.css
> +    height: 60px;
don't hardcode `height`, add `padding` instead

2023-03-18 18:32 UTC, ivanchuk-yurii commented on src/style.css
> +    background-color: #00ACDC;
move colors into variables

2023-03-18 18:32 UTC, ivanchuk-yurii commented on src/style.css
> +    position: sticky;
why is it sticky?

2023-03-18 18:32 UTC, ivanchuk-yurii commented on src/style.css
> +    padding: 0;
everything except `box-sizing` is forbidden in `*`

2023-03-18 18:34 UTC, ivanchuk-yurii commented
change urls in demo and do npm run deploy so I can see demo
<img width="659" alt="image" src="https://user-images.githubusercontent.com/53611910/226129261-dafe95e9-4e15-428c-8f37-9cb4ef32af39.png">

2023-03-18 20:52 UTC, karynabotvina reviewed
[DEMO LINK](https://karynabotvina.github.io/layout_moyo-header/)

2023-03-18 20:54 UTC, karynabotvina commented
> [DEMO LINK](https://karynabotvina.github.io/layout_moyo-header/)

I made corrections to my work, please check it

2023-03-18 20:55 UTC, karynabotvina commented
> [DEMO LINK](https://karynabotvina.github.io/layout_moyo-header/)
> 
> * [TEST REPORT LINK](https://karynabotvina.github.io/layout_moyo-header/report/html_report/)

New [DEMO LINK](https://karynabotvina.github.io/layout_moyo-header/)

2023-03-28 07:22 UTC, polosanya requested changes
Test link still doesn't work. Please make sure that it works before re-requesting the review.
Ask for help in fe_chat if you have any difficulties 🙂 
![image](https://user-images.githubusercontent.com/96409563/228156096-7762ae04-fe48-45f0-96d4-6bf05ab801c0.png)
Also, please compare your work with the design. It doesn't really match it
https://www.figma.com/file/1sog2rmfyCjnVxkeZ3ptnc/MOYO-%2F-Header?node-id=0-1&t=iFNdGU6Mq1vilV9V-0
![image](https://user-images.githubusercontent.com/96409563/228155576-3f6ccc0d-fa4d-4843-9811-d236506a3dcd.png)
![image](https://user-images.githubusercontent.com/96409563/228155644-335b0679-4b27-4bd7-bf75-9793778763ac.png)

2023-03-31 11:35 UTC, karynabotvina commented
Hello, my test link does not work, sorry. I asked for help in the group chat. One lady said I can create a new pr, but we are still thinking about how to figure out this problem. Tests were successfully started

2023-03-31 11:54 UTC, anstsot requested changes
Previous comments aren't fixed. If you have any questions, feel free to ask them in the `fe_chat`

2025-07-01 07:51 UTC, closed without merging