add task solution
mate-academy/layout_moyo-header pull request #2971
Opened 2023-04-12 17:22 UTC by MaxSchmide

https://maxschmide.github.io/layout_moyo-header/
https://maxschmide.github.io/layout_moyo-header/report/html_report/

2023-05-24 15:56 UTC, ManoylovAC requested changes
Hi 👋 
Good time to some improvements.
Please recheck requirements, for example your layout haven't fit on different widths (1024px, 1200px). And also fix my suggestion in comment I left
Hint: for adaptive styles you can youse media-queries

2023-05-24 15:56 UTC, ManoylovAC commented on src/index.html
> +          <a class="nav__item is-active">Apple</a>
oops, you missing `li` tags, please check it out again

2023-05-24 18:11 UTC, MaxSchmide commented
> Hi 👋 Good time to some improvements. Please recheck requirements, for example your layout haven't fit on different widths (1024px, 1200px). And also fix my suggestion in comment I left Hint: for adaptive styles you can youse media-queries

What exactly is wrong on different screen sizes? I looked at mockup and all difference is distance between logo and nav, which auto fixing by flex and justify-content: space-between. Other spaces are the same. So, what I missed?

2023-05-29 07:36 UTC, tetiana-ivanchenko requested changes

2023-05-29 07:36 UTC, tetiana-ivanchenko commented on src/style.css
> +}
![image](https://github.com/mate-academy/layout_moyo-header/assets/59209337/a16633d7-9fd7-4a23-b253-7c204a1e8e1f)

2023-05-29 07:36 UTC, tetiana-ivanchenko commented on src/style.css
> +  font-family: "Roboto", sans-serif;
![image](https://github.com/mate-academy/layout_moyo-header/assets/59209337/788d9343-4a67-4a76-93a0-1e88d6e71022)

2023-05-29 07:36 UTC, tetiana-ivanchenko commented on src/style.css
> +  color: #00acdc;
move repeatable colors in the variables

2023-05-29 07:37 UTC, tetiana-ivanchenko commented on src/index.html
> +        alt="logo"
![Uploading image.png…]()

2023-05-29 12:50 UTC, anstsot requested changes
Let’s add the last fixes to improve your code

2023-05-29 12:50 UTC, anstsot commented on src/index.html
> +            <a class="nav__link is-active">Apple</a>
all links should have `href` attribute. please add it to all needed elements

2023-05-30 07:19 UTC, tetiana-ivanchenko commented on src/index.html
> +            </a>
```suggestion
            <a
              class="nav__link"
              href="#"
              data-qa="hover"
            >
              laptops & computers
            </a>
```

2023-09-12 11:58 UTC, closed without merging