TIC1
mate-academy/layout_moyo-header pull request #2984
Opened 2023-04-16 13:01 UTC by timohahaaa

https://timohahaaa.github.io/layout_moyo-header/report/html_report/

https://timohahaaa.github.io/layout_moyo-header/

I'm so sorry, but I created a new pull request cause the last one had a glitch on my PC!

2023-04-16 17:02 UTC, Volodymyr-Melnyk-Fron10der requested changes
Pls try to fix failed report points. If you have any troubles - feel free to ask them in the Slack

2023-04-16 17:02 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +  padding: 0;
there is no default padding for body, so there is no need to reset it

2023-04-16 17:02 UTC, Volodymyr-Melnyk-Fron10der commented on src/style.css
> +  font-family: "Roboto", sans-serif;
just set it for html selector and inherit it

2023-04-18 18:41 UTC, polosanya requested changes
A few more comments to fix

2023-04-18 18:41 UTC, polosanya commented on src/index.html
> +          alt="#"
The `alt` attribute for the logo image should descriptive. Something like "Moyo logo" would be great

2023-04-18 18:41 UTC, polosanya commented on src/style.css
> +  align-items: center;
The 'align-items' property is used with a flex container, but '.nav__link' is not a flex container. Consider removing it, as it does not have any effect on the element

2023-04-18 18:41 UTC, polosanya commented on src/style.css
> +  padding-bottom: 19px;
Paddings should be added to the links, not li, so links are clickable for the whole height

2023-04-19 19:16 UTC, closed without merging