Header
mate-academy/layout_moyo-header pull request #3059
Opened 2023-04-27 14:17 UTC by bardyuzha

https://bardyuzha.github.io/layout_moyo-header/
https://bardyuzha.github.io/layout_moyo-header/report/html_report/

2023-04-27 15:20 UTC, mykhalenych requested changes

2023-04-27 15:20 UTC, mykhalenych commented on src/index.html
> +            <a
```suggestion
            <a
              href="#Apple"
              class="menu__link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2023-04-27 15:20 UTC, mykhalenych commented on src/style.css
> +  color: #00acdc;
better to create variable with color and use variable in two places

2023-04-29 08:03 UTC, OleziO requested changes

2023-04-29 08:03 UTC, OleziO commented on src/index.html
> +            >Apple</a>
```
<a
  href="#Apple"
  class="menu__link is-active"
>
  Apple
</a>
```

Сheck all similar cases and fix them.

2023-04-30 13:36 UTC, VitaliyBondarenko1982 approved these changes

2024-07-04 14:27 UTC, closed without merging