add moyo header
mate-academy/layout_moyo-header pull request #3114
Opened 2023-05-10 23:46 UTC by Yuliia-Hrinchenko1

- [DEMO LINK](https://Yuliia-Hrinchenko1.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Yuliia-Hrinchenko1.github.io/layout_moyo-header/report/html_report/)

2023-05-11 07:53 UTC, vlad-demchuk requested changes

2023-05-11 07:53 UTC, vlad-demchuk commented on src/style.css
> +  --blue-color: #00acdc;
move variables to `:root` pseudo class

2023-05-11 07:53 UTC, vlad-demchuk commented on src/style.css
> +  /* display: flex; */
remove comments

2023-05-11 07:53 UTC, vlad-demchuk commented on src/style.css
> +  font-family: Roboto, sans-serif;
move `font-family` to `html` selector

2023-05-12 13:32 UTC, volodymyr-soltys97 requested changes
Good job 👍 
But let's make your code more readable

2023-05-12 13:32 UTC, volodymyr-soltys97 commented on src/style.css
> +
Remove the empty line for consistent formatting.

2023-05-12 13:32 UTC, volodymyr-soltys97 commented on src/style.css
> +}
Remove the empty line for consistent formatting.

2023-05-12 13:32 UTC, volodymyr-soltys97 commented on src/index.html
> +            <a href="#gadjets" class="nav__link">Gadgets</a>
Fix the typo in the href attribute value, change 'gadjets' to 'gadgets'.

2023-05-12 13:32 UTC, volodymyr-soltys97 commented on src/index.html
> +          class="logo__image">
Remember about code style. Check it everywhere
```suggestion
        <img
          src="images/logo.png"
          alt="logo-image"
          class="logo__image"
        >
```

2023-05-12 13:32 UTC, volodymyr-soltys97 commented on src/index.html
> +              class="nav__link is-active">Apple</a>
```suggestion
            <a href="#apple" class="nav__link is-active">Apple</a>
```

2023-05-12 13:43 UTC, volodymyr-soltys97 approved these changes
Awesome 🔥

2023-12-18 18:00 UTC, closed without merging