add task solution moyo header
mate-academy/layout_moyo-header pull request #3116
Opened 2023-05-11 19:02 UTC by EdwardYatos

- [DEMO LINK] https://EdwardYatos.github.io/layout_moyo-header/
- [TEST REPORT LINK] https://EdwardYatos.github.io/layout_moyo-header/report/html_report/

2023-05-12 06:03 UTC, mykhalenych requested changes

2023-05-12 06:03 UTC, mykhalenych commented on src/style.css
> +ul {
```suggestion
```
delete it

2023-05-12 06:03 UTC, mykhalenych commented on src/style.css
> +  align-items: center;
```suggestion
  align-items: center;
  padding: 0;
  margin: 0;
  list-style-type: none;
```

2023-05-12 06:03 UTC, mykhalenych commented on src/style.css
> +a.is-active {
you already have class for link use instead of tag name

2023-05-13 08:58 UTC, YegorKorenkov requested changes

2023-05-13 08:58 UTC, YegorKorenkov commented on src/style.css
> +.nav-items a {
please use class selector instead of `a`

2023-05-13 08:58 UTC, YegorKorenkov commented on src/index.html
> +      <div class="container">
this container redundant, it doesn't do anything, please delete

2023-05-13 08:58 UTC, YegorKorenkov commented on src/style.css
> +  height: 60px;
Tru to not hardcode height

2023-05-13 13:38 UTC, VitaliyBondarenko1982 requested changes
Looks like your code and your demo linkd not consistent
try to deploy your changes
![Screenshot from 2023-05-13 16-37-29](https://github.com/mate-academy/layout_moyo-header/assets/33029864/c254e35b-32f3-4ace-af55-5ff0b3ddbfc4)

2023-05-13 14:34 UTC, VitaliyBondarenko1982 approved these changes

2023-11-30 19:22 UTC, closed without merging