add task solution
mate-academy/layout_moyo-header pull request #3148
Opened 2023-05-18 15:30 UTC by ISamofalov

- [DEMO LINK](https://isamofalov.github.io/layout_moyo-header)
- [TEST REPORT LINK](https://isamofalov.github.io/layout_moyo-header/report/html_report/)

2023-05-19 06:40 UTC, vlad-demchuk requested changes
GJ

2023-05-19 06:40 UTC, vlad-demchuk commented on src/style.css
> +.nav__item:first-child {
you can use not instead of reset for the first child

2023-05-19 06:40 UTC, vlad-demchuk commented on src/style.css
> +  background-color: #00acdc;
move color to variable

2023-06-08 14:25 UTC, volodymyr-soltys97 commented on src/index.html
> +            <a href="#" class="nav__link is-active">Apple</a>
You can make the links more informative
```suggestion
            <a href="#apple" class="nav__link is-active">Apple</a>
```

2023-06-09 18:12 UTC, ISamofalov commented on src/index.html
> +            <a href="#" class="nav__link is-active">Apple</a>
please check, i made changes

2023-08-22 09:03 UTC, closed without merging