add task solution
mate-academy/layout_moyo-header pull request #3180
Opened 2023-05-24 18:56 UTC by daria-sazon

2023-05-24 19:10 UTC, Viktor-Kost requested changes
Nice!
Some moments can be improved

2023-05-24 19:10 UTC, Viktor-Kost commented on src/index.html
> +      <div class="logo">
It would be better to use a more descriptive class name like 'header__logo' instead of 'logo' for better understanding in the context of the header.

2023-05-24 19:10 UTC, Viktor-Kost commented on src/index.html
> +          <li class="nav__li">
```suggestion
          <li class="nav__item">
```

2023-05-24 19:10 UTC, Viktor-Kost commented on src/index.html
> +          </li>
```suggestion
          <li class="nav__li">
            <a 
              href="#" class="nav__link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
          </li>
```

2023-05-24 19:10 UTC, Viktor-Kost commented on src/index.html
> +          <li class="nav__li">
add an empty line between _multiline_ siblings
```suggestion
          </li>
          
          <li class="nav__li">
```

2023-05-24 19:10 UTC, Viktor-Kost commented on src/style.css
> +}
it's not a good practice to use display: none for h1 tag. Either use [visually hidden snippet](https://levimcg.com/blog/visually-hidden-snippet/) or just remove h1 for this task

2023-05-24 19:10 UTC, Viktor-Kost commented on src/style.css
> +.nav__list {
remove default margin for list

2023-05-24 19:10 UTC, Viktor-Kost commented on src/style.css
> +  line-height: 3;
```suggestion
  display: inline-block;
```

2023-05-24 19:10 UTC, Viktor-Kost commented on src/style.css
> +}
redundant
```suggestion
```

2023-05-24 19:10 UTC, Viktor-Kost commented on src/style.css
> +}
redundant
```suggestion
```

2023-05-24 19:42 UTC, daria-sazon commented
Hi! Thanks for the feedback. I have added improvements to the code. I hope everything is correct)

2023-05-24 19:49 UTC, daria-sazon commented
Hi! Thanks for the feedback. I`ve added improvements to the code. I hope everything is correct)

2023-05-25 11:42 UTC, sTorba24 requested changes
Good work! Lets improve a little :)

2023-05-25 11:42 UTC, sTorba24 commented on src/index.html
> +              data-qa="hover"
```suggestion
              href="#" 
              class="nav__link"
              data-qa="hover"
```

2023-05-25 11:42 UTC, sTorba24 commented on src/index.html
> +              data-qa="hover"
move every attribute to new line when you started it :)

2023-05-25 11:42 UTC, sTorba24 commented on src/style.css
> +  --link-color-hover: rgba(0, 172, 220, 1);
would be good to move variables to `:root` selector

2023-05-25 11:42 UTC, sTorba24 commented on src/style.css
> +}
you don't have class logo now, no?

2023-05-25 11:42 UTC, sTorba24 commented on src/style.css
> +}
can be removed i think

2023-05-25 14:06 UTC, mykhalenych approved these changes

2025-11-17 21:52 UTC, closed without merging