add Moyo Header task
mate-academy/layout_moyo-header pull request #3239
Opened 2023-05-29 17:22 UTC by TamaraShukalo

- [DEMO LINK](https://<your_account>.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://<your_account>.github.io/layout_moyo-header/report/html_report/)

2023-05-29 17:54 UTC, ManoylovAC requested changes
Hey - good start 👋 
Let's make some improvements by comments I left for you.
Good luck!

2023-05-29 17:54 UTC, ManoylovAC commented on src/index.html
> +            data-qa="hover">Laptops & Computers</a>
please fix your indentations
check code style for html in your [checklist](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md) (13 point)
if you want to keep attributes on separate line, please keep all of them in that way for current case
```suggestion
            <tag
               attr1
               ...
            >
             Laptops & Computers
           </a>
```

2023-05-29 17:54 UTC, ManoylovAC commented on src/style.css
> +  color: #00acdc;
please create and use variables for color-values you using several times
```suggestion
  color: var(--some-variable-name);
```

2023-05-29 17:54 UTC, ManoylovAC commented on src/style.css
> +    padding: 0 50px;
by requirements you need to work with `width` here
this padding the same as [main rule](https://github.com/mate-academy/layout_moyo-header/pull/3239/files#diff-1104bdfdc4d3b01a85d7af489598121125db6bc016db2a48a083ef654c97b0f5R11) so no need to use it here
<img width="836" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/6568745/f49a3b50-c538-4d93-9523-bb117320d2b0">

2023-05-29 17:54 UTC, ManoylovAC commented on src/style.css
> +    padding: 0 50px;
you need to work with width here as well

2023-05-30 07:59 UTC, tetiana-ivanchenko requested changes

2023-05-30 07:59 UTC, tetiana-ivanchenko commented on src/index.html
> +            >
![image](https://github.com/mate-academy/layout_moyo-header/assets/59209337/f4a7212b-900a-483b-9632-5c070e62169b)

2023-05-30 07:59 UTC, tetiana-ivanchenko commented on src/style.css
> +  background: #fff;
it's default value, so here it's redundant

2023-05-30 10:02 UTC, YegorKorenkov approved these changes
Nice work! 🔥 Also don't forget read checklist carefully

2023-05-30 10:02 UTC, YegorKorenkov commented on src/style.css
> +  font-family: "Roboto", sans-serif;
Don't forget to add more fallback fonts!

2024-03-25 08:31 UTC, closed without merging