Moyo Header
mate-academy/layout_moyo-header pull request #3343
Opened 2023-06-12 19:52 UTC by AndriiZhovtko

- [DEMO LINK](https://AndriiZhovtko.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://AndriiZhovtko.github.io/layout_moyo-header/report/html_report/)

Remarking code with your advice.

2023-06-13 14:44 UTC, loralevitska requested changes
Please redeploy your solution for review. Before re-request review check links on GIT
![image](https://github.com/mate-academy/layout_moyo-header/assets/70009205/26696eda-08fd-4991-82c1-fcd3d619e64b)

2023-06-13 14:44 UTC, loralevitska commented on src/index.html
> +            >
this tag can be written in one line provided that there are less than 3 attributes in the tag (it's up to you)

2023-06-13 14:44 UTC, loralevitska commented on src/style.css
> +  font-style: normal;
Remove redundant  default styles

2023-06-13 18:55 UTC, AndriiZhovtko commented
[DEMO LINK](https://andriizhovtko.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://andriizhovtko.github.io/layout_moyo-header/report/html_report/)
Remarking code with your advice__2

2023-06-14 18:31 UTC, SanyaBratashchuk requested changes
Links are not working
![image](https://github.com/mate-academy/layout_moyo-header/assets/97547824/a1c47f15-2bcf-4e76-b259-4b45f9cb9b22)

2023-06-15 18:36 UTC, closed without merging