add task solution
mate-academy/layout_moyo-header pull request #3358
Opened 2023-06-16 10:35 UTC by oleksij-omelchenko

[DEMO LINK](https://oleksij-omelchenko.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://oleksij-omelchenko.github.io/layout_moyo-header/report/html_report/)

2023-06-16 13:08 UTC, Anastasiia-Svintsova requested changes
Good start! Check my comments, please

2023-06-16 13:08 UTC, Anastasiia-Svintsova commented on src/index.html
> +        class="header__icon">
Check the code style everywhere. No need to wrap attributes if there are 2 or less
```suggestion
      <a href="#home" class="header__icon">
```

2023-06-16 13:08 UTC, Anastasiia-Svintsova commented on src/index.html
> +      <nav class="nav">
Don't forget to add empty lines between multiline sibling blocks of HTML
```suggestion
      </a>
      
      <nav class="nav">
```

2023-06-16 13:08 UTC, Anastasiia-Svintsova commented on src/style.css
> +ul {
use class names instead

2023-06-16 13:08 UTC, Anastasiia-Svintsova commented on src/style.css
> +  background: #fff;
Seems that background is white by default

2023-06-16 13:08 UTC, Anastasiia-Svintsova commented on src/style.css
> +  height: 40px;
You can create a variable for the logo size as well

2023-06-16 13:08 UTC, Anastasiia-Svintsova commented on src/style.css
> +  height: 100%;
Height is 100% by default. You can remove redundant styles. The display property seems redundant as well

2023-06-16 13:08 UTC, Anastasiia-Svintsova commented on src/style.css
> +  height: 100%;
The same about the height property

2023-06-16 13:08 UTC, Anastasiia-Svintsova commented on src/style.css
> +}
Seems redundant

2023-06-20 07:41 UTC, polosanya requested changes
Hi, I see you haven't fixed previous comments, maybe you did not push your changes?

If you have any questions, please ask them in fe_chat and tag mentors 🙂

2023-06-20 07:41 UTC, polosanya commented on src/index.html
> +      <a href="#home"
```suggestion
    <header class="header">
      <a href="#home"
```
Don't add empty line between parent and child elements

2023-06-20 07:41 UTC, polosanya commented on src/index.html
> +            </a>
```suggestion
            <a 
              href="#Laptops & Computers"
              class="nav__link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```
Fix all cases
![image](https://github.com/mate-academy/layout_moyo-header/assets/96409563/8e5b7335-e7cf-4e50-9f54-d3a8c37d5286)

2023-07-10 10:02 UTC, closed without merging