made task 'moyo header'
mate-academy/layout_moyo-header pull request #3401
Opened 2023-06-27 04:12 UTC by TKuts

- [DEMO LINK](https://TKuts.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://TKuts.github.io/layout_moyo-header/report/html_report/)

2023-06-27 10:17 UTC, SerhiiKirik requested changes
Well done 🔥 
Let's deploy your tests 🧑‍💻 
![image](https://github.com/mate-academy/layout_moyo-header/assets/91411692/d6dadcd4-7849-4baa-8005-12c9824f8225)

2023-06-27 10:17 UTC, SerhiiKirik commented on src/index.html
> +      <nav class="navigation">
```suggestion
      </div>
      
      <nav class="navigation">
```

2023-06-27 10:17 UTC, SerhiiKirik commented on src/index.html
> +          <li class="nav__item">
Do it for more readable
```suggestion
          <li class="nav__item">
            <a href="#" class="nav__link is-active">Apple</a>
          </li>
          
          <li class="nav__item">
            <a href="#" class="nav__link">Samsung</a>
          </li>
          
          <li class="nav__item">
            <a href="#" class="nav__link">Smartphones</a>
          </li>
          
          <li class="nav__item">
```

2023-06-27 10:17 UTC, SerhiiKirik commented on src/index.html
> +            <a href="#" class="nav__link" >Laptops & Computers</a>
```suggestion
            <a href="#" class="nav__link">Laptops & Computers</a>
```

2023-06-27 10:17 UTC, SerhiiKirik commented on src/index.html
> +          <li class="nav__item ">
```suggestion
          <li class="nav__item">
```

2023-06-27 10:17 UTC, SerhiiKirik commented on src/style.css
> +* {
These classes should be in the `html` selector
```suggestion
html {
```

2023-06-27 10:17 UTC, SerhiiKirik commented on src/style.css
> +  left: 0;
Let's try to organize your CSS
I recommend you take a look at these styles code and use it in the feature
[9elements](https://9elements.com/css-rule-order) or [htmlAcademy](https://codeguide.academy/html-css.html#css-order)

2023-06-28 14:04 UTC, TKuts commented
Fixed the errors and used this link (htmlAcademy) to style the code

- [DEMO LINK](https://TKuts.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://TKuts.github.io/layout_moyo-header/report/html_report/)

2023-06-28 16:48 UTC, sTorba24 requested changes
Almost good! Fix tests please

add `data-cy` attributes where it needed

2023-06-29 11:01 UTC, Anastasiia-Svintsova requested changes
- The header should have a full width according to the mockup. The spaces between the header and screen edges should be the same for all screens.
![image](https://github.com/mate-academy/layout_moyo-header/assets/99403198/81f5e5f4-e291-4d8c-91a1-09fcfc9b5fae)

2023-06-29 11:01 UTC, Anastasiia-Svintsova commented on src/style.css
> +header {
Use classes instead 
![image](https://github.com/mate-academy/layout_moyo-header/assets/99403198/0e7eb995-0cc0-4f1b-b2b5-18330a9d4c3d)

2023-06-29 11:02 UTC, Anastasiia-Svintsova requested changes
Check my comments, please

2023-06-29 11:02 UTC, Anastasiia-Svintsova commented on src/index.html
> +            data-qa="hover">Laptops & Computers</a>
Fix the code style 
```suggestion
            <a 
              href="#"
              class="nav__link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2023-06-29 20:22 UTC, TKuts commented
> eader {

![image](https://github.com/mate-academy/layout_moyo-header/assets/109001274/2c80a141-19ba-4818-aef6-51e40ebf8614)

I disagree with this comment, because the layout clearly shows that the content is smaller. And the basic 1200px is already with content and indents.

I corrected the rest of the comments.

2023-06-30 07:13 UTC, polosanya approved these changes
Nice!

2023-06-30 07:13 UTC, polosanya commented on src/index.html
>  </html>
```suggestion
  </body>
</html>
```
Don't add empty lines between parent and child elements

2023-08-15 20:38 UTC, closed without merging