solution
mate-academy/layout_moyo-header pull request #3450
Opened 2023-07-03 14:35 UTC by olegpaunov

2023-07-03 14:39 UTC, olegpaunov commented
nice task

2023-07-17 12:36 UTC, Moroz-Dmytro requested changes
Nice progress 🔥 
But added some comments to improve your code
Also, try to fix this on smaller screens
<img width="803" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/86789161/4b2e645c-7fb2-4786-b456-d74ce069e837">

2023-07-17 12:36 UTC, Moroz-Dmytro commented on src/index.html
> +            <a href="#" class="nav__link is-active">Apple</a>
```suggestion
            <a href="#apple" class="nav__link is-active">Apple</a>
```

2023-07-17 12:36 UTC, Moroz-Dmytro commented on src/index.html
> +            <a href="#" class="nav__link is-active">Apple</a>
Fix all links

2023-07-17 12:36 UTC, Moroz-Dmytro commented on src/style.css
> +  font-size: 12px;
Better will be to set this as default font styles for page, under html selector

2023-07-17 12:36 UTC, Moroz-Dmytro commented on src/style.css
> +.nav__link.is-active {
```suggestion
.is-active {
```

2023-07-17 12:36 UTC, Moroz-Dmytro commented on src/style.css
> +.nav__link.is-active {
<img width="950" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/86789161/4be65b36-8041-46bd-8db2-59f9fa07d358">

2023-07-17 12:36 UTC, Moroz-Dmytro commented on src/style.css
> +  color: #00acdc;
create variables for repeatable values

2023-07-19 09:09 UTC, closed without merging