add task solution
mate-academy/layout_moyo-header pull request #3512
Opened 2023-07-10 18:12 UTC by bkostanetskyi

file:///C:/Users/kbs20/projects/layout_moyo-header/backstop_data/html_report/index.html
https://bkostanetskyi.github.io/layout_moyo-header/

2023-07-10 18:23 UTC, Andriy-Shymkiv requested changes
better to use prefix `nav__` for your header items to keep clear BEM methodology here

2023-07-10 18:23 UTC, Andriy-Shymkiv commented on src/index.html
> +
please pay attention to formatting your code. look at [checklist](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md)

2023-07-10 18:23 UTC, Andriy-Shymkiv commented on src/style.css
> +}
no need to set max width here. logo is already 40px

2023-07-10 18:23 UTC, Andriy-Shymkiv commented on src/style.css
> +.list {
reset margin for your list

2023-07-10 18:23 UTC, Andriy-Shymkiv commented on src/style.css
> +}
you can just:
```css
.item:not(:last-child) {
  margin-right: 20px;
}
```

2023-07-15 09:49 UTC, Andriy-Shymkiv requested changes
1. pay attention to your tests, because they are failing
2. request a review only after all comments fixes from mentors.
3. if you need some help, please ask it in your group chat or  QnA session

2023-07-15 09:49 UTC, Andriy-Shymkiv commented on src/index.html
> +
[checklist](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md) rule number 5 and 13. pay attention to your code style!

2023-07-15 09:49 UTC, Andriy-Shymkiv commented on src/style.css
> +  margin: 0;
no need to reset margin for nav, it is zero by default

2023-07-15 09:49 UTC, Andriy-Shymkiv commented on src/style.css
> +  background-color: #00acdc;
you repeating yourself at least three times. so better to move this to some variable

2023-07-15 09:49 UTC, Andriy-Shymkiv commented on src/style.css
> +  margin: 22.5px 0 ;
not a good approach. better to center your items with flexbox

2023-07-15 09:50 UTC, Andriy-Shymkiv commented on src/index.html
> +
not fixed!

2023-07-17 17:40 UTC, Andriy-Shymkiv requested changes
please apply all changes

2023-07-17 17:40 UTC, Andriy-Shymkiv commented on src/style.css
> +  margin: 22.5px 0 ;
set margin to zero here:
```css
margin: 0;
```

2023-07-24 13:19 UTC, xiimiik commented on src/index.html
> +          <li class="nav__item"><a href="#" class="nav__link">Samsung</a></li>
lets improve code style

```suggestion
          <li class="nav__item">
            <a href="#" class="nav__link is-active">Apple</a>
          </li>

          <li class="nav__item">
            <a href="#" class="nav__link">Samsung</a>
          </li>
```

2023-07-24 13:19 UTC, xiimiik commented on src/index.html
> +           data-qa="hover">Laptops & Computers</a>
```suggestion
            <a 
              href="#"
              class="nav__link "
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2023-07-24 13:21 UTC, xiimiik commented on src/style.css
> +
```suggestion
```

2023-07-24 13:21 UTC, xiimiik commented on src/style.css
> +.nav__item :hover {
```suggestion
.nav__item:hover {
```

2023-07-24 16:40 UTC, closed without merging