add task solution
mate-academy/layout_moyo-header pull request #3580
Opened 2023-07-18 08:59 UTC by SmartSergiZ

- [DEMO LINK](https://SmartSergiZ.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://SmartSergiZ.github.io/layout_moyo-header/report/html_report/)

2023-07-18 13:35 UTC, alexander-ignatow commented on src/style.css
> +  box-sizing: border-box;
Setting `box-sizing` individually for each class is not a great idea - as there are few scenarios when one needs to vary it.

In most cases, including yours, it is better to set a single box-sizing value for all elements and vary it only when needed

Try to fix this issue - it looks minor in this task but may become painful in large projects.

Here is a good article on box-sizing: https://css-tricks.com/box-sizing/

And here is a good way to set box-sizing: https://css-tricks.com/box-sizing/#aa-good-better-and-probably-best-box-sizing-reset-methods

2023-07-18 13:38 UTC, alexander-ignatow commented on src/style.css
> +  color: #00acdc;
It is better to set colors via CSS variables - to be able to control them.  This even more important if the color is reused.
Check this: https://www.w3schools.com/css/css3_variables.asp

2023-07-18 13:39 UTC, alexander-ignatow commented on src/style.css
> +  border-radius: 8px;
The border-radius is bigger than the height - an obvious typo here :)
It does not have any effect in this case, still please fix it.

2023-07-18 13:40 UTC, alexander-ignatow requested changes
Good solution! Visually everything is ok, but let's improve the code quality a bit.

2023-07-18 18:32 UTC, SmartSergiZ commented
tnx)
all changes have already been added

2023-07-19 09:24 UTC, roman-mirzoian approved these changes
Well done 👍

2023-07-31 09:23 UTC, alexander-ignatow requested changes
Very good - some things are fixed, still some remain

Also pleas make sure to deploy your latest solution ☝️

2023-07-31 09:23 UTC, alexander-ignatow commented on src/style.css
> +  box-sizing: border-box;
box-sizing is not inherited - you should set it globally via `*`

2023-07-31 09:23 UTC, alexander-ignatow commented on src/style.css
> +  margin: 0;
No margins on BEM blocks

2023-08-07 16:15 UTC, BudnikOleksii approved these changes
Good job👍

2023-09-22 12:35 UTC, closed without merging