Develop
mate-academy/layout_moyo-header pull request #3613
Opened 2023-07-25 10:26 UTC by Metra25

2023-08-01 16:45 UTC, Esceype requested changes
Overall GJ !!!! Add demo link and report tests link to the description of PR

2023-08-01 16:45 UTC, Esceype commented on src/index.html
> +        <img class="img"
And change the name of your class
```suggestion
        <img
          class="img"
```

2023-08-01 16:45 UTC, Esceype commented on src/index.html
> +            </a>
Checklist 13

2023-08-01 16:45 UTC, Esceype commented on src/style.css
> +}
Checklist 10, 11

2023-08-01 18:46 UTC, Metra25 commented on src/style.css
> +  bottom: 0;
Не совсем понял, чего тут много))

2023-08-08 13:38 UTC, xiimiik requested changes
I see code changes, but u forgot to deploy ur changes

2023-08-08 13:38 UTC, xiimiik commented on src/style.css
> +  margin-left: 20px;
edge elements should not be indented

2023-08-08 13:38 UTC, xiimiik commented on src/style.css
> +  margin: 0;
ul have padding also

2023-08-08 15:48 UTC, mykhalenych requested changes

2023-08-08 15:48 UTC, mykhalenych commented on src/style.css
> +  padding: 23px 0 ;
<img width="1127" alt="Screenshot 2023-08-08 at 18 41 58" src="https://github.com/mate-academy/layout_moyo-header/assets/53228259/7507e2a7-d953-4e9c-9b11-4eea61cb630e">

check your padding

2023-11-01 15:03 UTC, closed without merging