add task solution
mate-academy/layout_moyo-header pull request #3616
Opened 2023-07-25 14:22 UTC by Daniil-A4

2023-07-27 08:13 UTC, denys-danyliuk requested changes

2023-07-27 08:13 UTC, denys-danyliuk commented on src/style.css
> +  font-family: Roboto, sans-serif;
3'rd point in checklist

2023-07-27 08:13 UTC, denys-danyliuk commented on src/index.html
> +                data-qa="hover">Laptops & Computers</a>
13'th point in checklist

2023-07-27 08:13 UTC, denys-danyliuk commented on src/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,700;0,900;1,100;1,200;1,300;1,400;1,500;1,800;1,900&family=Roboto:wght@100;500&display=swap" rel="stylesheet">
do you need Montserrat font? 
you don't actually use it

2023-07-29 10:22 UTC, Andriy-Shymkiv requested changes

2023-07-29 10:22 UTC, Andriy-Shymkiv commented on src/index.html
> +        <div class="header__body">
don't understand why you need this wrappers? you can do the same with only header

2023-07-29 10:22 UTC, Andriy-Shymkiv commented on src/index.html
> +                >
```suggestion
                <a 
                  href="#laptopsComputers"
                  class="nav__link"
                  data-qa="hover"
                >
```

2023-07-29 10:22 UTC, Andriy-Shymkiv commented on src/style.css
> +.is-active {
```suggestion
.nav__link {
```

2023-07-31 08:25 UTC, denys-danyliuk requested changes

2023-07-31 08:25 UTC, denys-danyliuk commented on src/style.css
> +  font-family: "Roboto", sans-serif;
3'rd point in checklist

2023-07-31 08:25 UTC, denys-danyliuk commented on src/index.html
> +          </li>
```suggestion
        <ul class="nav__list">
          <li class="nav__item">
            <a href="#apple" class="nav__link is-active">Apple</a>
          </li>
          
          <li class="nav__item">
            <a href="#samsung" class="nav__link">Samsung</a>
          </li>
```
add spaces between multiline sibling blocks

2023-07-31 08:25 UTC, denys-danyliuk commented on src/style.css
> +  position: relative;
should position change on hover?

2023-08-02 08:20 UTC, denys-danyliuk approved these changes

2023-08-02 08:32 UTC, denys-danyliuk approved these changes

2023-08-30 21:40 UTC, closed without merging