created header
mate-academy/layout_moyo-header pull request #3691
Opened 2023-08-11 15:08 UTC by iLavruk

2023-08-11 15:45 UTC, xiimiik requested changes
add deploy and links to description  (demo & tests)
![image](https://github.com/mate-academy/layout_moyo-header/assets/104684446/2516f049-a9c8-48ab-beba-8f73af8268f0)

2023-08-11 15:45 UTC, xiimiik commented on src/index.html
> +              data-qa="hover">Laptops & Computers</a>
checklist point 13

2023-08-11 15:45 UTC, xiimiik commented on src/style.css
> +}
just add margin for one side

2023-08-11 17:52 UTC, Esceype requested changes
Redeploy the task and provide the DEMO link for the task and tests report link in the PR description

2023-08-11 17:52 UTC, Esceype commented on src/style.css
> +}
Still not fixed

2023-08-11 17:52 UTC, Esceype commented on src/style.css
> +}
Not fixed

2023-08-12 10:50 UTC, Andriy-Shymkiv requested changes

2023-08-12 10:50 UTC, Andriy-Shymkiv commented on src/index.html
> +      <nav class="nav">
```suggestion
      </div>
      
      <nav class="nav">
```

2023-08-12 10:50 UTC, Andriy-Shymkiv commented on src/index.html
> +              data-qa="hover">Laptops & Computers</a>
```suggestion
            <a
              href="#"
              class="nav__link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2023-08-12 13:26 UTC, lerastarynets requested changes
Well done with fixing comments) Only several things need to be improved before approval

2023-08-12 13:26 UTC, lerastarynets commented on src/index.html
> +            alt="Logo">
checklist point 13

2023-08-12 13:26 UTC, lerastarynets commented on src/index.html
> +              data-qa="hover">
```suggestion
              data-qa="hover"
              >
```

2023-08-13 07:50 UTC, Andriy-Shymkiv approved these changes

2025-10-28 07:59 UTC, closed without merging