Develop
mate-academy/layout_moyo-header pull request #3703
Opened 2023-08-13 12:03 UTC by Mollinn

- [DEMO LINK](https://Mollinn.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Mollinn.github.io/layout_moyo-header/report/html_report/)

2023-08-13 12:17 UTC, Mollinn commented
Чому коли робиш краще функціональніше і тд не заходить  а так як зараз то будь ласка
5 версій цієї шапки було

2023-08-14 07:51 UTC, denys-danyliuk requested changes
Good job overall, pay attention to the comments and the requirements for the task

2023-08-14 07:51 UTC, denys-danyliuk commented on src/index.html
> +            <li class="header__item">
```suggestion
      <div class="header__container">
        <a href="#home" class="header__logo">
          <img src="../src/images/logo.png" alt="moyo logo">
        </a>
        
        <nav class="nav__menu">
          <ul class="header__list">
            <li  class="header__item">
              <a href="#" class="header__link is-active">
                Apple
              </a>
            </li>
            
            <li class="header__item">
```

2023-08-14 07:51 UTC, denys-danyliuk commented on src/index.html
> +    <header class="header">
it should be in the middle of the screen
<img width="1365" alt="Знімок екрана 2023-08-14 о 10 46 26" src="https://github.com/mate-academy/layout_moyo-header/assets/106310796/db00cf19-8981-4106-9bf4-6b0b853b0e19">

2023-08-14 07:51 UTC, denys-danyliuk commented on src/style.css
> +@import url("https://fonts.googleapis.com/css?family=Roboto:500&display=swap");
```suggestion
@import url("https://fonts.googleapis.com/css?family=Roboto:500&display=swap");
```

2023-08-14 07:51 UTC, denys-danyliuk commented on src/style.css
> +  height: 60px;
![Знімок екрана 2023-08-14 о 10 48 15](https://github.com/mate-academy/layout_moyo-header/assets/106310796/1546ab3f-e073-45cb-ae60-55167caa1cb4)

2023-08-14 07:51 UTC, denys-danyliuk commented on src/style.css
> +  text-decoration: none;
add transition to make your changes smooth on hover

2023-08-14 07:51 UTC, denys-danyliuk commented on src/style.css
> +  width: 1100px;
don't hardcode exact width, let content dictate it

2023-08-14 07:51 UTC, denys-danyliuk commented on src/style.css
> +  font-family: Roboto, sans-serif;
3'rd point in checklist

2023-08-14 08:57 UTC, Mollinn commented on src/style.css
> +@import url("https://fonts.googleapis.com/css?family=Roboto:500&display=swap");
Добрий день, я був зробив просто класну шапку перед цією але вона не проходила тести
Там було все як Ви написали 
Тести обов’язково мають бути?

2023-08-14 16:01 UTC, closed without merging