Develop
mate-academy/layout_moyo-header pull request #3718
Opened 2023-08-16 07:12 UTC by DamianAdamczewski

- [DEMO LINK](https://DamianAdamczewski.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://DamianAdamczewski.github.io/layout_moyo-header/report/html_report/)

2023-08-21 12:10 UTC, mykhalenych requested changes
Check comments, also check design
https://www.figma.com/file/1sog2rmfyCjnVxkeZ3ptnc/MOYO-%2F-Header?type=design&node-id=0-1&mode=design&t=Q95Hh3VXA4NIYJo9-0

2023-08-21 12:10 UTC, mykhalenych commented on src/index.html
> +        <img class="icon"
<img width="1336" alt="Screenshot 2023-08-21 at 15 06 07" src="https://github.com/mate-academy/layout_moyo-header/assets/53228259/b105244f-0039-4873-95c2-7cf771f892dc">

2023-08-21 12:10 UTC, mykhalenych commented on src/style.css
> +  /* border: 5px solid pink; */
delete comments

2023-08-21 12:10 UTC, mykhalenych commented on src/style.css
> +.rectangle {
you don't have class rectangle

2023-08-21 12:10 UTC, mykhalenych commented on src/style.css
> +a {
add classname for a tags and use .classname instead

2023-08-21 12:10 UTC, mykhalenych commented on src/style.css
> +a:active {
use .is-active::after and create line with position absolute, also add position relative for .is-active

2023-08-24 15:46 UTC, closed without merging

2023-09-12 07:46 UTC, OleziO requested changes
Header must be full screen width.
![image](https://github.com/mate-academy/layout_moyo-header/assets/56752562/4107e954-21e9-4e1a-8113-4fc51b790858)

2023-09-12 07:46 UTC, OleziO commented on src/index.html
> +      >
```suggestion
        <img
          src="./images/logo.png"
          alt="logo moyo"
        >
```

2023-09-12 07:46 UTC, OleziO commented on src/index.html
> +            </a>
```suggestion
            <a 
              href="#apple"
              class="nav__link
              is-active"
            >
             Apple
           </a>
```

2023-09-12 07:46 UTC, OleziO commented on src/index.html
> +             class="nav__link">
```suggestion
            <a 
               href="#samsung"
               class="nav__link"
             >
```

2023-09-12 07:46 UTC, OleziO commented on src/index.html
> +             class="nav__link">
Check all other similar cases.

2023-09-12 07:46 UTC, OleziO commented on src/style.css
> +  background-color: #00acdc;
Move all repeatable colors to the CSS variables.

[More info.](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

2023-09-12 18:57 UTC, plodnikate requested changes
Good job, but use scss nesting and also check and follow approach ([CSS_order-rule](https://9elements.com/css-rule-order/))

2023-09-13 14:49 UTC, mykhalenych requested changes

2023-09-13 14:49 UTC, mykhalenych commented on src/index.html
> +            <a
```suggestion
            <a
              href="#"
              class="nav__link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2023-09-13 14:49 UTC, mykhalenych commented on src/style.css
> +.nav__link:active::after {
it is redundant

2023-09-13 15:06 UTC, DamianAdamczewski commented on src/index.html
> +            <a
done :)

2023-09-13 15:32 UTC, mykhalenych approved these changes
Nice work!