Develop_Moyo_header_Serdiuk_Max
mate-academy/layout_moyo-header pull request #3741
Opened 2023-08-22 11:35 UTC by serdiukm

2023-08-22 12:02 UTC, Viktor-Kost requested changes

2023-08-22 12:02 UTC, Viktor-Kost commented on src/style.css
> +.nav__item {
first item shouldn't have margin
```suggestion
.nav__item:not(:first-child) {
```

2023-08-22 12:02 UTC, Viktor-Kost commented on src/index.html
> +            <a href="index.html" class="is-active">Apple</a>
```suggestion
            <a href="index.html" class="nav__link is-active">Apple</a>
```

2023-08-22 12:02 UTC, Viktor-Kost commented on src/index.html
> +            <a href="index.html" class="link">Samsung</a>
```suggestion
            <a href="index.html" class="nav__link">Samsung</a>
```

2023-08-22 12:02 UTC, Viktor-Kost commented on src/style.css
> +  background: #00acdc;
move repeated colors to variables

2023-08-22 12:02 UTC, Viktor-Kost commented on src/style.css
> +a:hover {
style class selectors instead of tag ones

2023-08-22 12:02 UTC, Viktor-Kost commented on src/style.css
> +  bottom: -20px;
```suggestion
  bottom: 0;
```

2023-08-22 12:02 UTC, Viktor-Kost commented on src/style.css
> +  color: black;
use hex names instead of reserved words to set a color

2023-08-23 07:37 UTC, maxim2310 requested changes
Yor demo link is not working, please fix it and make request review again

2023-08-25 21:00 UTC, serdiukm commented
> _ No description provided. _

2023-08-25 21:00 UTC, closed without merging