add task solution
mate-academy/layout_moyo-header pull request #3771
Opened 2023-08-29 14:59 UTC by IlliaAstakhov

- [DEMO LINK](https://IlliaAstakhov.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://IlliaAstakhov.github.io/layout_moyo-header/report/html_report/)

2023-08-29 15:03 UTC, IlliaAstakhov commented
Дуже хотілося б отримати комент щодо того, чи немає зайвого коду в стилях. 
Є підозра, що все ж таки є)

2023-08-29 15:29 UTC, anastasiiavorobiova requested changes
Great work! Added comments to fix

2023-08-29 15:29 UTC, anastasiiavorobiova commented on src/index.html
> +            class="nav_link"
```suggestion
              class="nav_link"
```
Consider fixing indentations according to the code style guide

2023-08-29 15:29 UTC, anastasiiavorobiova commented on src/index.html
> +            data-qa="hover"
```suggestion
              data-qa="hover"
```

2023-08-29 15:29 UTC, anastasiiavorobiova commented on src/index.html
> +            href="#"
```suggestion
              href="#"
```

2023-08-29 15:29 UTC, anastasiiavorobiova commented on src/style.css
> +  /*width: var(--width);*/
Consider removing unused styles and empty lines before closing the bracket

2023-08-29 15:29 UTC, anastasiiavorobiova commented on src/style.css
> +  --color: hsl(193, 100%, 43%);
Consider using hex values for colors

2023-08-29 15:29 UTC, anastasiiavorobiova commented on src/style.css
> +  font-style: normal;
```suggestion

```
It's a default browser styling, no need to write it

2023-08-29 15:29 UTC, anastasiiavorobiova commented on src/style.css
> +
You can use relative positioning just for active class

2023-09-07 06:52 UTC, maxim2310 approved these changes
Good work!!!

2024-12-26 13:34 UTC, closed without merging