add task solution
mate-academy/layout_moyo-header pull request #3778
Opened 2023-08-30 15:56 UTC by mariiamad

2023-08-31 06:39 UTC, maxim2310 requested changes
Good job! Let's improve your code a bit)
And try to restart your tests and pass them all

2023-08-31 06:39 UTC, maxim2310 commented on src/index.html
> +            <a href="#Laptops&Computers" class="nav__link data-qa">Laptops & Computers</a>
```suggestion
            <a href="#Laptops&Computers" class="nav__link" data-qa="hover">Laptops & Computers</a>
```
![image](https://github.com/mate-academy/layout_moyo-header/assets/96265844/b660e24a-daa9-409c-baef-c0f0fb0948b3)

2023-08-31 06:39 UTC, maxim2310 commented on src/style.css
> +  margin-right: auto;
you just need to set justify-content: space-between; for .header instead this
![image](https://github.com/mate-academy/layout_moyo-header/assets/96265844/3a6dc71f-4153-4612-b9bd-15a14ffb0327)

2023-08-31 06:39 UTC, maxim2310 commented on src/style.css
> +  z-index: 50;
```suggestion
  position: relative;

```

2023-08-31 06:39 UTC, maxim2310 commented on src/style.css
> +  z-index: 40;
dont use so huge z-index its can cause for unexpected behavior,
and why do you need this before?

2023-08-31 06:39 UTC, maxim2310 commented on src/style.css
> +  outline: 2px solid #00acdc;
#00acdc this color must be variable

2023-08-31 06:39 UTC, maxim2310 commented on src/style.css
> +  color: blue;
use #00acdc this color like variable

2023-08-31 06:39 UTC, maxim2310 commented on src/style.css
> +  flex-shrink: 0;
```suggestion
```

2023-09-01 15:19 UTC, mariiamad commented
Thanks for checking! I improved my code)
I restarted my tests and  passed tham all.

2023-09-06 15:52 UTC, closed without merging