added moyo header landing
mate-academy/layout_moyo-header pull request #3800
Opened 2023-09-04 15:34 UTC by yulabakun

- [DEMO LINK](https://yulabakun.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://yulabakun.github.io/layout_moyo-header/report/html_report/)

2023-09-05 09:02 UTC, StasSokolov requested changes
Good job, let's improve your code a bit more!

First of all add please `box-shadow` property for header
![261038093-211b8a6d-29d4-4eff-9374-117eafaeab69](https://github.com/mate-academy/layout_moyo-header/assets/75898310/a53d145e-0a76-4769-8955-ff0d167d915d)
![Снимок экрана 2023-09-05 в 11 00 16](https://github.com/mate-academy/layout_moyo-header/assets/75898310/84c20643-60ac-4702-931d-3365a903d952)

2023-09-05 09:02 UTC, StasSokolov commented on src/style.css
> +  background-color: lightgray;
let's set to `white` as in the design

2023-09-06 07:07 UTC, superpooperxxx requested changes
Hey, good job🔥 Most of the notes are recommendation, but the lines 35-37 in styles.css should be fixed, because this goes agains checklist

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +  box-sizing: border-box;
* {
    box-sizing: border-box;
}

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +  width: 100%;
redundant

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +}
It is redundant, because `<a>` inside anyway has `cursor: pointer`

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +  list-style: none;
I recommend moving all `reset type` styles to the top, later they all will lay in `reset.css`, so get used to separating

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +}
CHECKLIST p.1

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +  line-height: 15px;
What do you think of setting the `height` property instead ?

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +  cursor: pointer;
`cursor: pointer;` redundant

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +}
Let's combine the styles for setting `color`

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +  width: 100%;
Redundant, because `left: 0; + right: 0` will stretch the element to 100% width

2023-09-06 07:07 UTC, superpooperxxx commented on src/style.css
> +  margin: 0 auto;
redundant

2023-09-06 13:18 UTC, superpooperxxx approved these changes
Good job🔥 For the future, get rid of styles that are redundant, this will make your code cleaner and easier to understand. The same goes for reset styles

2025-02-13 12:40 UTC, closed without merging