layout_moyo_headet
mate-academy/layout_moyo-header pull request #3836
Opened 2023-09-09 08:56 UTC by DmytroKrylov

[DEMO LINK](https://DmytroKrylov.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://DmytroKrylov.github.io/layout_moyo-header/report/html_report/)

2023-09-09 10:03 UTC, Anastasiia-Svintsova requested changes
Good start! 

- It doesn't look good on small screens. Fix it, please. Prohibit block from shrink.
![image](https://github.com/mate-academy/layout_moyo-header/assets/99403198/5330847d-671c-44ff-b3db-6a65d5a78357)

2023-09-09 10:03 UTC, Anastasiia-Svintsova commented on src/index.html
> +          <li class="nav-item"><a class="nav-link" href="index.html">Samsung</a></li>
The page shouldn't reload on the link click. Use anchor links instead 
```suggestion
          <li class="nav-item">
            <a class="nav-link" href="#Samsung">Samsung</a>
          </li>
```

2023-09-09 10:03 UTC, Anastasiia-Svintsova commented on src/index.html
> +              href="index.html">Laptops & Computers</a>
Fix the code style 
```suggestion
            <a 
              class="nav-link"
              data-qa="hover"
              href="index.html"
            >
              Laptops & Computers
            </a>
```

2023-09-09 10:03 UTC, Anastasiia-Svintsova commented on src/style.css
> +header {
![image](https://github.com/mate-academy/layout_moyo-header/assets/99403198/4a6ce5b0-39a9-493b-8af8-3e38a1ba05ec)

2023-09-11 07:55 UTC, etojeDenys requested changes

2023-09-11 07:55 UTC, etojeDenys commented on src/index.html
> +            </a>
```suggestion
            <a 
              class="nav-link"
              data-qa="hover"
              href="#"
            >
              Laptops & Computers
            </a>
```
fix it everywhere

2023-09-11 11:19 UTC, mykhalenych requested changes

2023-09-11 11:19 UTC, mykhalenych commented on src/index.html
> +          <li
```suggestion
          <li class="nav-item"> <a class="nav-link is-active" href="#">Apple</a></li>
```

2023-09-11 11:19 UTC, mykhalenych commented on src/index.html
> +           class="nav-item"> <a class="nav-link" href="#">Samsung</a>
fix all

2023-09-11 11:19 UTC, mykhalenych commented on src/index.html
> +          <li class="nav-item">
```suggestion
          <li class="nav-item">
            <a 
             class="nav-link"
             data-qa="hover"
             href="#"
            >
              Laptops & Computers
            </a>
          </li>
```

2023-09-11 14:23 UTC, mykhalenych approved these changes

2025-07-17 19:20 UTC, closed without merging