add task solution
mate-academy/layout_moyo-header pull request #3909
Opened 2023-10-04 18:22 UTC by pasha30061

- [DEMO LINK](https://pasha30061.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://pasha30061.github.io/layout_moyo-header/report/html_report/)

2023-10-04 18:26 UTC, Viktor-Kost requested changes
GJ!
Some minor fixes needed

2023-10-04 18:26 UTC, Viktor-Kost commented on src/index.html
> +            data-qa="hover">Laptops & Computers</a>
```suggestion
            <a 
              href="#laptops&computers" 
              class="nav_link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2023-10-04 18:26 UTC, Viktor-Kost commented on src/style.css
> +  height: 60px;
it's not a good practice to hardcode height for elements with content inside. just use padding

2023-10-04 18:26 UTC, Viktor-Kost commented on src/style.css
> +a.is-active::after {
use class selectors instead of tag ones

2023-10-04 18:26 UTC, Viktor-Kost commented on src/index.html
> +            <a href="#apple" class="nav_link is-active">Apple</a>
according to BEM methodology
```suggestion
      <nav class="nav">
        <ul class="nav__list">
          <li class="nav__item">
            <a href="#apple" class="nav__link is-active">Apple</a>
```

2023-10-04 18:26 UTC, Viktor-Kost commented on src/style.css
> +}
this tag is a block by default
```suggestion
```

2023-10-04 19:14 UTC, pasha30061 commented
[corrected the details]
[DEMO LINK](https://pasha30061.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://pasha30061.github.io/layout_moyo-header/report/html_report/)

2023-10-05 06:52 UTC, etojeDenys requested changes

2023-10-05 06:52 UTC, etojeDenys commented on src/index.html
> +          </li>
```suggestion
            <a
              href="#laptops & computers"
              class="nav__link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
          </li>
```

2023-10-05 07:22 UTC, pasha30061 commented
add new commit

2023-10-05 07:25 UTC, etojeDenys approved these changes
good job

2024-10-03 19:15 UTC, closed without merging