created MOYO-header
mate-academy/layout_moyo-header pull request #3911
Opened 2023-10-05 16:13 UTC by Pavel6331

[DEMO LINK](https://<your_account>.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://<your_account>.github.io/layout_moyo-header/report/html_report/)

2023-10-05 16:29 UTC, etojeDenys requested changes

2023-10-05 16:29 UTC, etojeDenys commented on readme.md
> +- [TEST REPORT LINK](https://Pavel6331.github.io/layout_moyo-header/report/html_report/)
provide these links in PR description

2023-10-05 16:29 UTC, etojeDenys commented on src/index.html
> +            </a>
```suggestion
            <a 
              href="#LAPTOP&COMPUTERS"
              class="nav-link"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2023-10-05 16:29 UTC, etojeDenys commented on src/style.css
> +}
we can join it using the comma

2023-10-05 16:29 UTC, etojeDenys commented on src/style.css
> +  font-style: normal;
it's default value so we can remove it

2023-10-05 16:29 UTC, etojeDenys commented on src/style.css
> +  /*height: 60px;*/
remove all comments

2023-10-06 13:04 UTC, VitaliyBodnar requested changes

2023-10-06 13:04 UTC, VitaliyBodnar commented on src/style.css
> +  color: #00acdc;
color '#00acdc' is duplicated, so please move all duplicated styles to the variables

2023-10-06 13:04 UTC, VitaliyBodnar commented on src/style.css
> +  display: block;
Let's try to organize your CSS
I recommend you take a look at these styles code and use it in the feature
[9elements](https://9elements.com/css-rule-order) or [htmlAcademy](https://codeguide.academy/html-css.html#css-order)

2023-10-06 13:17 UTC, denys-danyliuk approved these changes
Good job

2023-10-06 13:17 UTC, denys-danyliuk commented on src/style.css
> +.data-qa {
```suggestion
.nav-link:hover {
```
you don't have this class

2023-10-06 13:17 UTC, denys-danyliuk commented on src/style.css
> +  font-family: Roboto, sans-serif;
add fallback fonts, check code style - fallback fonts

2025-02-06 14:33 UTC, closed without merging