MOYO header
mate-academy/layout_moyo-header pull request #3925
Opened 2023-10-09 15:57 UTC by DanielYurchenco

2023-10-09 16:15 UTC, Viktor-Kost requested changes

2023-10-09 16:15 UTC, Viktor-Kost commented on src/index.html
> +      <a href="https://www.google.com.ua/?hl=ru" class="logo">
```suggestion
      <a href="#" class="logo">
```

2023-10-09 16:15 UTC, Viktor-Kost commented on src/index.html
> +        <ul class="navbar">
```suggestion
        <ul class="nav__list">
```

2023-10-09 16:15 UTC, Viktor-Kost commented on readme.md
> +- [TEST REPORT LINK](https://DanielYurchenco.github.io/layout_moyo-header/report/html_report/)
please add these links to a PR description

2023-10-09 16:15 UTC, Viktor-Kost commented on src/index.html
> +          </li>
1. apply code styling recommendations from a checklist to other items as well
2. use BEM methodology for naming classes
3. no needs to set a link. You can just use `#`
4. use lowercase at html and change this value at css
```suggestion
          <li class="nav__item">
            <a 
              href="#laptops&computers"
              class="nav__link"
              data-qa="hover"
            >
              laptops & computers
            </a>
          </li>
```

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +  margin: 10px 50px;
```suggestion
  padding: 0 50px;
```

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +.navlist {
first item shouldn't have margin. use `:not(:first-child)`

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +  color: black;
apply `hex` instead of reserved color words

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +  padding-bottom: 15px;
links should have a bigger padding value
```suggestion
  padding: 23px 0;
```

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +  bottom: -1px;
```suggestion
  bottom: 0;
```

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +  height: 3px;
```suggestion
  height: 4px;
```

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +  background-color: #00acdc;
move repeated colors to variables

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +.nav {
you can just make your header as `flex` and use `justify-content: space-between`

2023-10-09 16:15 UTC, Viktor-Kost commented on src/style.css
> +.is-active::before {
if you have repeated styles for a few selectors you can just use them as a list

```
.selector1, 
.selector2 {
  {{rules}}
}
```

2023-10-10 08:04 UTC, DanielYurchenco commented
> _ No description provided. _

- [DEMO LINK](https://DanielYurchenco.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://DanielYurchenco.github.io/layout_moyo-header/report/html_report/)

2023-10-10 08:32 UTC, DarkMistyRoom requested changes
the links don't work(

2023-10-10 08:32 UTC, DarkMistyRoom commented on src/index.html
> +      <nav class="nav">
```suggestion
      </a>
      
      <nav class="nav">
```

2023-10-10 08:32 UTC, DarkMistyRoom commented on src/index.html
> +      <nav class="nav">
Add empty lines between multiline sibling blocks of HTML

2023-10-10 08:32 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
```suggestion
            <a
              href="#"
              class="nav__link is-active"
            >
              apple
            </a>
```

2023-10-10 08:32 UTC, DarkMistyRoom commented on src/index.html
> +            </a>
fix it everywhere

2023-10-10 15:15 UTC, Viktor-Kost requested changes
Nice!
Minor fixes needed. 
Plus check this unresolved conversation
https://github.com/mate-academy/layout_moyo-header/pull/3925#discussion_r1350509501

2023-10-10 15:15 UTC, Viktor-Kost commented on src/index.html
> +          </li>
apply code styling recommendations from a checklist all over the page
```suggestion
        <ul class="nav__list">
          <li class="nav__item">
            <a
              href="#"
              class="nav__link is-active"
            >
              apple
            </a>
          </li>
```

2023-10-12 08:00 UTC, volodymyr-soltys97 requested changes
Demo link, you need to make a deploy
<img width="801" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/64750958/378c23bc-8399-42a9-b50f-7501c3843d4b">

2023-10-12 08:00 UTC, volodymyr-soltys97 commented on readme.md
> +- [TEST REPORT LINK](https://DanielYurchenco.github.io/layout_moyo-header/report/html_report/)
Add these links to the pr description

2023-10-12 08:17 UTC, closed without merging