solution to a task
mate-academy/layout_moyo-header pull request #3929
Opened 2023-10-09 18:30 UTC by Timi2424

https://<Timi2424>.github.io/layout_moyo-header/
https://<Timi2424>.github.io/layout_moyo-header/report/html_report/

2023-10-10 06:43 UTC, mbruhler requested changes
Hi,
Please add links to your test and github pages.

2023-10-10 06:43 UTC, mbruhler commented on src/index.html
> +        <img
Please refer to this [guideline](https://mate-academy.github.io/style-guides/htmlcss.html#html-line-wrapping) and fix the formatting

2023-10-10 06:43 UTC, mbruhler commented on src/index.html
> +      <ul class="nav">
It's not using BEM, please use it

2023-10-10 06:43 UTC, mbruhler commented on src/style.css
> +  background-color: aqua;
use color hex instead of name

2023-10-10 06:43 UTC, mbruhler commented on src/style.css
> +  text-decoration-color: blue;
use color hex instead of name and move them to CSS Variables

2023-10-10 06:43 UTC, mbruhler commented on src/style.css
> +  size: 40px 40px;
move size also to css variables

2023-10-12 12:06 UTC, mbruhler requested changes
Your links still don't work. Please refer to documentation in the readme to solve this problem.

Also your new changes don't include my past requests. Please include them in the next update.

2023-10-12 12:06 UTC, mbruhler commented on src/style.css
> +  height: 40px;
Please move this to css variables

2023-10-12 12:06 UTC, mbruhler commented on src/style.css
> +  height: 40px;
Then you can use this variable here

2023-10-12 12:06 UTC, mbruhler commented on src/style.css
> +  background-color: #00acdc;
Colors are still not in variables

2023-10-13 08:14 UTC, mvjl000 requested changes
Hey, could you re-deploy your solution? Your DEMO and report is not working (404)

2023-10-13 09:09 UTC, mbruhler approved these changes
Good job!
Approved :)

2024-07-05 16:52 UTC, closed without merging