create moyo-header
mate-academy/layout_moyo-header pull request #4155
Opened 2023-11-27 13:42 UTC by Manankin

- [DEMO LINK](https://manankin.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://manankin.github.io/layout_moyo-header/report/html_report/)

2023-11-27 14:55 UTC, Manankin commented
attempt #2

2023-11-27 15:48 UTC, dinaminahi requested changes
Good job 👍  Few points to fix and check the tests, please

2023-11-27 15:48 UTC, dinaminahi commented on src/index.html
> +          <li class="nav-item">
Please, check if the code follows all code style rules 
![image](https://github.com/mate-academy/layout_moyo-header/assets/46566190/8fc2d56c-9e16-4c4b-a515-25e8f56e883a)

2023-11-27 15:48 UTC, dinaminahi commented on src/style.css
> +ul {
![image](https://github.com/mate-academy/layout_moyo-header/assets/46566190/abed7052-0140-464d-a3fc-31d0e0c78f21)

2023-11-27 16:34 UTC, Manankin commented
updated styles format and html format

2023-11-28 11:11 UTC, artemforsoff requested changes
the code doesn't match what is deployed, so it is impossible to test
update the branch `develop` 👌🏻

2023-11-28 15:04 UTC, SerhiiKirik approved these changes
Well done 🔥 
On the future - try to organize your CSS
I recommend you take a look at these styles code and use it in the feature
[9elements](https://9elements.com/css-rule-order) or [htmlAcademy](https://codeguide.academy/html-css.html#css-order)

2023-11-28 15:04 UTC, SerhiiKirik commented on src/index.html
> +      <nav class="nav-block">
Don't forget to put empty line in such cases
```suggestion
      </a>
      
      <nav class="nav-block">
```

2026-03-04 07:23 UTC, closed without merging