add task solution
mate-academy/layout_moyo-header pull request #4156
Opened 2023-11-27 14:12 UTC by YevhenOstrovskiy

- [DEMO LINK](https://YevhenOstrovskiy.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://YevhenOstrovskiy.github.io/layout_moyo-header/report/html_report/)

2023-11-27 15:52 UTC, dinaminahi requested changes
Good job ⭐ Just few moments to fix

2023-11-27 15:52 UTC, dinaminahi commented on src/style.css
> +  width: 100%;
Let`s place it before  the variable to avoid unnecessary empty line

2023-11-27 15:52 UTC, dinaminahi commented on src/index.html
> +          <li class="menu-item">
Check the code style rules, please
![image](https://github.com/mate-academy/layout_moyo-header/assets/46566190/0af06b78-0e3c-4820-8bca-437abfeff2cb)

2023-11-28 10:51 UTC, YevhenOstrovskiy commented on src/style.css
> +  box-sizing: border-box;
StyleLint error "Expected '*' to have no more than 0 universal selectors (selector-max-universal)" That rule restricts the usage of universal selectors (*) in my CSS.

2023-11-28 15:13 UTC, YevhenOstrovskiy commented
Understand! Thank you)

вт, 28 нояб. 2023 г. в 17:11, Anastasiia Otrubchak ***@***.***
>:

> ***@***.**** approved this pull request.
>
> approving✨
> But pay more attention to code formatting rules
> ------------------------------
>
> In src/index.html
> <https://github.com/mate-academy/layout_moyo-header/pull/4156#discussion_r1407924854>
> :
>
> > +          </li>
> +
> +          <li class="menu-item">
> +            <a href="#" class="menu-link">Samsung</a>
> +          </li>
> +
> +          <li class="menu-item">
> +            <a href="#" class="menu-link">Smartphones</a>
> +          </li>
> +
> +          <li class="menu-item">
> +            <a
> +              href="#"
> +              class="menu-link"
> +              data-qa="hover"
> +            >Laptops & Computers</a>
>
> please, pay more attention to code formatting rules
> ⬇️ Suggested change
>
> -            >Laptops & Computers</a>
> +            >
> +              Laptops & Computers
> +            </a>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_moyo-header/pull/4156#pullrequestreview-1753150785>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWDBQBCRQ43LZ3RGROLVQATYGX5LPAVCNFSM6AAAAAA74DDZRCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONJTGE2TANZYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-31 17:57 UTC, closed without merging