task solution 'moyo logo'
mate-academy/layout_moyo-header pull request #4171
Opened 2023-11-27 18:45 UTC by marichkamt

- [DEMO LINK](https://marichkamt.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://marichkamt.github.io/layout_moyo-header/report/html_report/)

2023-11-27 19:43 UTC, Viktor-Kost requested changes

2023-11-27 21:14 UTC, marichkamt commented on src/index.html
> +
ok,but then i get a linter error.

<img width="1440" alt="Screenshot 2023-11-27 at 10 12 55 PM" src="https://github.com/mate-academy/layout_moyo-header/assets/149372044/3c2c769a-8f75-4d22-a30d-c81a5eb9ba64">

2023-11-28 11:30 UTC, anastasiiavorobiova requested changes
Great work! Make sure to deploy your page 
<img width="224" alt="Screenshot 2023-11-28 at 13 21 51" src="https://github.com/mate-academy/layout_moyo-header/assets/135232001/d7711769-25b6-44dc-b966-12518f000740">

2023-11-28 11:30 UTC, anastasiiavorobiova commented on src/index.html
> +            >Apple</a>
```suggestion
            <a 
              class="nav-link is-active"
              href="#"
            >
              Apple
            </a>
```
Consider fixing indents according to the code style guide

2023-11-28 11:30 UTC, anastasiiavorobiova commented on src/index.html
> +            >Samsung</a>
```suggestion
            <a 
              class="nav-link"
              href="#"
            >
              Samsung
            </a>
```
Also, consider fixing similar issues further in the code

2023-11-28 12:07 UTC, closed without merging