header-of-moyo
mate-academy/layout_moyo-header pull request #4192
Opened 2023-11-30 19:12 UTC by Prokopovych16

- [DEMO LINK](https://Prokopovych16.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Prokopovych16.github.io/layout_moyo-header/report/html_report/)

2023-12-01 07:55 UTC, volodymyr-soltys97 requested changes
Hi, your demo link doesn't work, you need to make a deploy
<img width="833" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/64750958/7cf25441-346b-4163-923f-cb37ea4c48ee">

2023-12-01 07:55 UTC, volodymyr-soltys97 commented on src/index.html
> +      <a href=""><img src="images/logo.png" alt="" class="img_header"></a>
```suggestion
    <header class="header">
      <a href="">
        <img
          src="images/logo.png"
          alt="Moyo logo"
          class="header__logo"
        >
      </a>
```

2023-12-01 07:55 UTC, volodymyr-soltys97 commented on src/index.html
> +          <li class="li_header"> <a href="" class="a__li">Apple</a></li>
Need to fix it everywhere
```suggestion
      <nav class="nav">
        <ul class="nav__list">
          <li class="nav__item">
            <a href="" class="nav__link">Apple</a>
          </li>
          
```

2023-12-01 07:55 UTC, volodymyr-soltys97 commented on src/style.css
> +  --height-for-header: 60px;
Create a variable with root selector

2023-12-01 07:55 UTC, volodymyr-soltys97 commented on src/style.css
> +  /* background-color: hotpink; */
Remove comments everywhere
```suggestion
```

2023-12-01 07:55 UTC, volodymyr-soltys97 commented on src/style.css
> +  color: #00ACDC;
Create a variable for this color and use it everywhere

2023-12-07 14:42 UTC, anastasiiavorobiova requested changes
Great work! Almost done! Make sure to deploy your page

2023-12-07 14:42 UTC, anastasiiavorobiova commented on src/index.html
> +            >Laptops & Computers</a>
```suggestion
            <a
              data-qa="hover"
              href="#"
              сlass="nav__link"
            >
              Laptops & Computers
            </a>
```
Consider fixing indents according to the code style guide

2023-12-07 14:42 UTC, anastasiiavorobiova commented on src/index.html
> +    href="https://fonts.gstatic.com">
```suggestion
    <link 
      rel="preconnect"
      href="https://fonts.gstatic.com"
    >
```

2023-12-07 14:42 UTC, anastasiiavorobiova commented on src/style.css
> +  text-transform: uppercase;
```suggestion

```
This should be applied just to links

2023-12-07 14:42 UTC, anastasiiavorobiova commented on src/style.css
> +.nav__item:nth-child(4) a:hover {
```suggestion
.nav__link:hover {
```

2023-12-07 14:52 UTC, Prokopovych16 commented
I don't understand what is wrong with 'npm run deploy'. It doesn't connect css to html.

2023-12-07 16:55 UTC, closed without merging