Develop
mate-academy/layout_moyo-header pull request #4246
Opened 2023-12-11 14:29 UTC by RSydorenko322

- [DEMO LINK](https://RSydorenko322.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://RSydorenko322.github.io/layout_moyo-header/report/html_report/)

2023-12-11 15:49 UTC, VitaliyBodnar requested changes

2023-12-11 15:49 UTC, VitaliyBodnar commented on src/style.css
> +
Redundant spaces
```suggestion
```

2023-12-11 15:49 UTC, VitaliyBodnar commented on src/style.css
> +[data-qa="hover"]:hover {
Use class active for that

2023-12-11 15:49 UTC, VitaliyBodnar commented on src/index.html
> +            data-qa="hover">Laptops & computers</a>
Code is not aligned 
Check the check list

2023-12-11 16:29 UTC, RSydorenko322 commented
[image: image.png]
after redoing I had that kind of problem in MA (while checking the test)
can you help ?

пн, 11 дек. 2023 г. в 16:49, VitaliyBodnar ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/style.css
> <https://github.com/mate-academy/layout_moyo-header/pull/4246#discussion_r1422690314>
> :
>
> > +
> +
>
> Redundant spaces
> ⬇️ Suggested change
>
> -
> -
>
> ------------------------------
>
> In src/style.css
> <https://github.com/mate-academy/layout_moyo-header/pull/4246#discussion_r1422697585>
> :
>
> > +.video {
> +  margin-right: 0;
> +}
> +
> +.nav__item.is-active.apple::after {
> +  content: "";
> +  position: absolute;
> +  bottom: 0;
> +  width: 100%;
> +  height: 4px;
> +  flex-shrink: 0;
> +  border-radius: 8px;
> +  background: var(--need-color);
> +}
> +
> +[data-qa="hover"]:hover {
>
> Use class active for that
> ------------------------------
>
> In src/index.html
> <https://github.com/mate-academy/layout_moyo-header/pull/4246#discussion_r1422698909>
> :
>
> > +            <a href="#" class="nav__item laptops"
> +            data-qa="hover">Laptops & computers</a>
>
> Code is not aligned
> Check the check list
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_moyo-header/pull/4246#pullrequestreview-1775487649>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEJYYR4OSABYKI5WZHCIY23YI4TRVAVCNFSM6AAAAABAP3QBAKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONZVGQ4DONRUHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-11 16:59 UTC, sTorba24 requested changes

2023-12-11 16:59 UTC, sTorba24 commented on src/index.html
> +        class="logo__image">
```suggestion
        <img
          src="/src/images/logo.png"
          alt="logo"
          class="logo__image"
        >
```

2023-12-11 16:59 UTC, sTorba24 commented on src/index.html
> +        class="logo__image">
every attribute should be on new line if you started moving it(with +2 indentation)

You can move them if you have more than 2 attrs

2023-12-11 16:59 UTC, sTorba24 commented on src/index.html
> +        class="logo__image">
fix everywhere please

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  --need-color: #00ACDC;
use :root selector to declare variables

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  right: 50px;
why do you need it?

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  flex-shrink: 1;
remove it

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  padding: 0;
```suggestion
  padding: 0 50px;
```

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  padding: 0;
it'll squeeze the content inside and make side padding 50px. What you need

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  font-style: normal;
default value, can be removed

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  display: flex;
block is enough

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  margin: 0 10px;
use one-side margin,
margin-left or margin-right

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +.nav__item.apple{
use is-active selector

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  margin-left: 0;
nav-item:first-child

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  margin: 0 0 0 100px;
you don't need it

2023-12-11 16:59 UTC, sTorba24 commented on src/style.css
> +  background-color: lightgray;
remove it

2023-12-11 17:46 UTC, RSydorenko322 commented on src/style.css
> +  flex-shrink: 0;
the blue element. If i delete it it will disappear, really don`t know extra options to set it into position

2023-12-13 07:12 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
Need to add blue color when hovering for all links
<img width="716" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/64750958/6c88a519-2bf6-4bb6-971f-8b9eb046b648">

2023-12-13 07:12 UTC, volodymyr-soltys97 commented on src/index.html
> +        class="logo__image">
```suggestion
        <img
          src="/src/images/logo.png"
          alt="Moyo logo"
          class="logo__image"
        >
```

2023-12-13 07:12 UTC, volodymyr-soltys97 commented on src/index.html
> +      <nav class="nav">
```suggestion
      </a>
      
      <nav class="nav">
```

2023-12-13 07:12 UTC, volodymyr-soltys97 commented on src/index.html
> +          <li>
Add classes everywhere for tag li
```suggestion
          <li class="nav__item">
```

2023-12-13 07:12 UTC, volodymyr-soltys97 commented on src/index.html
> +            </a>
Need to fix it everywhere
```suggestion
            <a href="#apple" class="is-active nav__link">
              Apple
            </a>
```

2023-12-13 07:12 UTC, volodymyr-soltys97 commented on src/index.html
> +            </a>
```suggestion
            <a
              href="#laptops"
              class="nav__link"
              data-qa="hover"
            >
              Laptops & computers
            </a>
```

2023-12-13 07:12 UTC, volodymyr-soltys97 commented on src/style.css
> +}
```suggestion
```

2023-12-13 11:08 UTC, lerastarynets approved these changes
You're making excellent progress!

2024-04-02 19:22 UTC, closed without merging