Develop
mate-academy/layout_moyo-header pull request #4351
Opened 2024-01-08 20:48 UTC by jdifek

- [DEMO LINK](https://jdifek.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://jdifek.github.io/layout_moyo-header/report/html_report/)

2024-01-09 08:57 UTC, lerastarynets requested changes
Almost there, just one problem left)

2024-01-09 08:57 UTC, lerastarynets commented on src/index.html
> +      alt="logo">
<img width="357" alt="attrCheklist" src="https://github.com/mate-academy/layout_moyo-header/assets/77551820/9124bbfe-b5b7-4f79-9ccb-dddd7f10b967">

**PLS DO THE SAME FOR ALL SUCH CASES IN THE PROJECT**

2024-01-09 19:39 UTC, anastasiia-tilikina requested changes
Please read carefully [style guide](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md)

And fix code style. now it is formated wrong. The previous comment didn't fixed.

2024-01-09 20:00 UTC, Viktor-Kost requested changes

2024-01-09 20:00 UTC, Viktor-Kost commented on src/index.html
> +      </a>
code styling fixes needed
```suggestion
      <a href="#HOME">
        <img
          class="logo"
          src="images/logo.png"
          alt="logo"
        >
      </a>
```

2024-01-09 20:00 UTC, Viktor-Kost commented on src/index.html
> +            </a>
```suggestion
            <a
              class="nav_link"
              href="#laptops_computers"
              data-qa="hover"
            >
              Laptops & Computers
            </a>
```

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +  text-transform: uppercase;
it's not a good practice to set this rule to the full page. set only for links

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +  --header-height: 60px;
it's not a good practice to hardcode height for elements with content inside. use padding for your links instead

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +  color: #00ACDC;
repeated colors to variables

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +.header {
add `padding: 0 50px` to avoid using margin for `img` and `nav`

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +  height: var(--header-height);
```suggestion
```

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +  margin-left: 50px;
```suggestion
```

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +img {
style class selectors not tag ones

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +}
```suggestion
```

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +a:hover {
style class selectors not tag ones

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +  background: #00acdc;
variables

2024-01-09 20:00 UTC, Viktor-Kost commented on src/style.css
> +  margin-left: 0;
```suggestion
.is-active {
  position: relative;
```

2024-01-10 09:05 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2024-01-10 09:05 UTC, volodymyr-soltys97 commented on src/style.css
> +.nav_link[data-qa="hover"]:hover {
No need to use attributes as css selector

2024-01-10 21:19 UTC, closed without merging