Lesson 5, task 2 'MOYO Header' - Done!
mate-academy/layout_moyo-header pull request #438
Opened 2020-08-31 13:50 UTC by Atteroot

- [DEMO LINK](https://Atteroot.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Atteroot.github.io/layout_moyo-header/report/html_report/)

2020-08-31 15:08 UTC, danheim requested changes
good start

2020-08-31 15:08 UTC, danheim commented on src/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400&display=swap">
ты подключаешь шрифты, не стили

2020-08-31 15:08 UTC, danheim commented on src/index.html
> +          </li>
nav
nav__list
nav__item
nav__link

2020-08-31 15:08 UTC, danheim commented on src/style.css
> +}
для этого используется файл reset.css, на будущее

2020-08-31 15:08 UTC, danheim commented on src/style.css
> +}
логотип должен идти после хедера

2020-08-31 15:08 UTC, danheim commented on src/style.css
> +  background-color: #fff;
по-умолчанию какой цвет?

2020-08-31 16:09 UTC, Atteroot commented on src/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400&display=swap">
Пытался подключить шрифты через @font-face локально, менял stylesheet на preload с as="font" - шрифты съезжают и тесты не проходятся.

2020-08-31 16:09 UTC, Atteroot commented on src/index.html
> +          </li>
Исправил!

2020-08-31 16:09 UTC, Atteroot commented on src/style.css
> +}
Попробовал подключить, вроде сработало.

2020-08-31 16:09 UTC, Atteroot commented on src/style.css
> +}
Исправлено!

2020-08-31 16:09 UTC, Atteroot commented on src/style.css
> +  background-color: #fff;
Убрал лишнее.

2020-09-01 10:11 UTC, danheim commented on src/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400&display=swap">
моя ошибка, не обращай внимание на комментарий

2020-09-01 10:11 UTC, danheim approved these changes
Nice

2021-03-23 18:57 UTC, closed without merging