Develop
mate-academy/layout_moyo-header pull request #4392
Opened 2024-01-16 10:33 UTC by Rusik-best86

- [x] Header height is set in 1 place (for the links)
- [x] Content is vertically centered (for any header height)
- [x] CSS is used to show all letters in Uppercase (don't type them in HTML)
- [x] Logo is an image wrapped with a link
- [x] CSS Variable is used for a blue color
- [x] Pseudo-element is used for a blue line below the active link
- [x] Code follows all the [Code Style Rules ❗️](https://github.com/Rusik-best86/layout_moyo-header/blob/master/checklist.md)

2024-01-24 16:57 UTC, BudnikOleksii requested changes
Good work 👍 
Check the [checklist](https://github.com/Rusik-best86/layout_moyo-header/blob/develop/checklist.md) and fix your code accordingly.
And add links to the demo and test report in the PR:
![image](https://github.com/mate-academy/layout_moyo-header/assets/63243136/8c79a4ee-6312-4cbf-99fc-310cbaf73393)

2024-01-24 16:57 UTC, BudnikOleksii commented on src/index.html
> +        <a class="header__logo" href="#"> <img src="/src/images/logo.png" alt="logo"></a>
[Checklist](https://github.com/Rusik-best86/layout_moyo-header/blob/develop/checklist.md):
- alt attribute should describe the image content
![image](https://github.com/mate-academy/layout_moyo-header/assets/63243136/137c6759-8320-4a63-a31f-0e4527872ee9)
- And fix formatting, don't put nested elements in the parent line

2024-01-24 16:57 UTC, BudnikOleksii commented on src/index.html
> +            <li class="nav__item"> <a class="nav__link" href="#smartphones">Smartphones</a> </li>
- Add empty lines between multiline sibling blocks of HTML
![image](https://github.com/mate-academy/layout_moyo-header/assets/63243136/211fb52c-7b85-4ab0-9638-cba3fbbe2b80)

2024-01-24 16:57 UTC, BudnikOleksii commented on src/index.html
>    </body>
- But don't add them between parent and child elements.
![image](https://github.com/mate-academy/layout_moyo-header/assets/63243136/1620ddf9-ac34-4602-8065-bc38a5c2933b)

2024-01-24 17:24 UTC, closed without merging

2024-01-24 17:54 UTC, Rusik-best86 commented
kikikik

2024-01-24 17:54 UTC, Rusik-best86 commented
ikikik

2024-01-25 08:13 UTC, Rusik-best86 commented
9l9l9l

2024-01-25 08:14 UTC, Rusik-best86 commented
l9l