add task solution
mate-academy/layout_moyo-header pull request #4419
Opened 2024-01-22 20:17 UTC by troleksii

- [DEMO LINK](https://troleksii.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://troleksii.github.io/layout_moyo-header/report/html_report/)

2024-01-22 20:31 UTC, Viktor-Kost requested changes

2024-01-22 20:31 UTC, Viktor-Kost commented on src/index.html
> +          <li class="add__marg">
change a class name
```suggestion
          <li class="nav__item">
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/index.html
> +             href="#laptops_&_computers">laptops & computers</a>
code styling
```suggestion
            <a 
              class="nav__link" 
              data-qa="hover"
              href="#laptops_&_computers"
            >
              laptops & computers
            </a>
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  --header-height: 60px;
no needs to hardcode height
```suggestion
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  --active-color: #00ACDC;
it's netter to move variables to the `root`

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  position: relative;
shouldn't be relative
```suggestion
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +
add `padding: 0 50px;` to avoid using positioning

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  left: 50px;
```suggestion
  display: block;
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +}
redundant
```suggestion
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  position: relative;
```suggestion
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +
```suggestion
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  line-height: var(--header-height);
set a correct line height from figma and to get height you need you can just use padding

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  position: relative;
move to `is-active`

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +}
```suggestion
.nav__item:not(:last-child) {
  margin-right: 20px;
}
```

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  color: #00ACDC;
reuse a color variable

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  background: #00ACDC;
color variable

2024-01-22 20:31 UTC, Viktor-Kost commented on src/style.css
> +  }
no needs
```suggestion
```

2024-01-22 21:28 UTC, troleksii commented on src/style.css
> +  position: relative;
@Viktor-Kost  when I moved that part to ".active" selector - nav links moved higher and lost style. should I move it?
<img width="662" alt="Знімок екрана 2024-01-22 о 22 28 15" src="https://github.com/mate-academy/layout_moyo-header/assets/150616349/1ebd07d7-c734-4eb2-8055-e898b5fd568a">

2024-01-22 22:03 UTC, Viktor-Kost commented on src/index.html
> +          <li class="add__marg">
not only to the first  `li` but for other ones as well

2024-01-22 22:07 UTC, Viktor-Kost commented on src/style.css
> +  position: relative;
You should also apply fixes from other comments to have a correct solution

`position: relative;` should be added only to `.is-active` selector.
So your pseudo-element `:after` will have `position: absolute;`

If you need any help with this issue feel free to ask at fe_chat

2024-01-22 22:07 UTC, Viktor-Kost requested changes
Nice!
I see no changes. check either you've push your commit or not
If you need any help with this issue feel free to ask at fe_chat

2024-01-23 07:13 UTC, etojeDenys approved these changes
good job

2024-04-23 11:31 UTC, closed without merging