added task solution
mate-academy/layout_moyo-header pull request #4471
Opened 2024-01-29 17:59 UTC by Yan-Chan-py

https://Yan-Chan-py.github.io/layout_moyo-header/
https://Yan-Chan-py.github.io/layout_moyo-header/report/html_report/

2024-01-31 13:13 UTC, Moroz-Dmytro requested changes
Good progress 👍 
But let's improve it

I should see hover effect when I hover below or above the text, not only when I hover the text

https://github.com/mate-academy/layout_moyo-header/assets/86789161/0b063a16-a290-4df2-92bb-1bb9158c2812

2024-01-31 13:13 UTC, Moroz-Dmytro commented on src/index.html
> +        >
<img width="1055" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/86789161/7c98d9ca-f658-45ea-8fce-45990b784620">

2024-01-31 13:13 UTC, Moroz-Dmytro commented on src/index.html
> +          </li>
<img width="1122" alt="Spaces between tags" src="https://github.com/mate-academy/layout_moyo-header/assets/86789161/fa515810-e535-4895-ae9e-d49fa118a2d8">

2024-01-31 13:13 UTC, Moroz-Dmytro commented on src/index.html
> +          >
<img width="1069" alt="Attributes formatting" src="https://github.com/mate-academy/layout_moyo-header/assets/86789161/1eec6828-9f21-4445-b443-1b0fd56aa31a">

2024-01-31 13:13 UTC, Moroz-Dmytro commented on src/index.html
> +          </li>
Fix in all places

2024-01-31 13:13 UTC, Moroz-Dmytro commented on src/style.css
> +
```suggestion
```

2024-01-31 13:13 UTC, Moroz-Dmytro commented on src/style.css
> +a:hover{
Use classname instead of 'a'

2024-01-31 13:13 UTC, Moroz-Dmytro commented on src/style.css
> +.item:nth-child(8){
:last-child

2024-01-31 13:13 UTC, Moroz-Dmytro commented on src/style.css
> +.item:nth-child(1){
:first-child

2024-02-01 09:41 UTC, stassokolov1 requested changes
Almost done, the issue with hover still exists as mentioned by @Moroz-Dmytro

2024-02-01 09:41 UTC, stassokolov1 commented on src/index.html
> +            </a>
```suggestion
            <a class="link" href="#">
              Samsung
            </a>
```

check formatting, please in all places

2024-02-01 09:43 UTC, stassokolov1 requested changes
Almost done, let's improve you code a bit more

2025-03-04 15:14 UTC, closed without merging