Add task solution
mate-academy/layout_moyo-header pull request #4569
Opened 2024-02-16 13:59 UTC by andreinik1

- [DEMO LINK] (https://andreinik1.github.io/layout_moyo-header/)
- [TEST REPORT LINK] (https://andreinik1.github.io/layout_moyo-header/report/html_report/)

- [x] Header height is set in 1 place (for the links)
- [x] Content is vertically centered (for any header height)
- [x] CSS is used to show all letters in Uppercase (don't type them in HTML)
- [x] Logo is an image wrapped with a link
- [x] CSS Variable is used for a blue color
- [x] Pseudo-element is used for a blue line below the active link
- [x] Code follows all the [Code Style Rules ❗️](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md)

2024-02-16 14:04 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-02-16 14:04 UTC, anastasiiavorobiova commented on src/index.html
> +        <a href="./index.html"><img src="./images/logo.png" alt="MOYO Logo image"></a>
```suggestion
        <a href="./index.html">
          <img src="./images/logo.png" alt="MOYO Logo image">
        </a>
```

2024-02-16 14:04 UTC, anastasiiavorobiova commented on src/index.html
> +              </a>
```suggestion
              <a 
                href="./index.html" 
                data-qa="hover"
                class="nav__link"
              >
                Laptops & Computers
              </a>
```

2024-02-16 14:04 UTC, anastasiiavorobiova commented on src/style.css
> +.container img {
Consider using class to style the image

2024-02-17 17:39 UTC, andreinik1 commented
- [DEMO LINK] (https://andreinik1.github.io/layout_moyo-header/)
- [TEST REPORT LINK] (https://andreinik1.github.io/layout_moyo-header/report/html_report/)

- [x] Header height is set in 1 place (for the links)
- [x] Content is vertically centered (for any header height)
- [x] CSS is used to show all letters in Uppercase (don't type them in HTML)
- [x] Logo is an image wrapped with a link
- [x] CSS Variable is used for a blue color
- [x] Pseudo-element is used for a blue line below the active link
- [x] Code follows all the [Code Style Rules ❗️](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md)

2024-02-17 17:40 UTC, closed without merging