solution
mate-academy/layout_moyo-header pull request #462
Opened 2020-11-02 23:08 UTC by Layrovell

[DEMO LINK](https://Layrovell.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://Layrovell.github.io/layout_moyo-header/report/html_report/)

2020-11-03 11:32 UTC, Denchepornyuk requested changes

2020-11-03 11:32 UTC, Denchepornyuk commented on src/index.html
> +          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```suggestion
    <meta
        name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```

2020-11-03 11:32 UTC, Denchepornyuk commented on src/index.html
> +      <a class="nav-list__logo" href="#"><img src="./images/logo.png" alt="logo">
в одній лінії коду має бути один тег

2020-11-03 11:32 UTC, Denchepornyuk commented on src/style.css
> +  padding: 0;
тут точно має бути `padding: 0;` ??

2020-11-03 11:32 UTC, Denchepornyuk commented on src/style.css
> +}
не стилізуй теги, стилізуємо тільки класи

2020-11-03 15:22 UTC, Layrovell commented on src/style.css
> +}
это reset, в дальнейшем буду выносить его отдельным файлом

2020-11-03 16:11 UTC, irenhh requested changes

2020-11-03 16:11 UTC, irenhh commented on src/index.html
> +      <a class="nav-list__logo" href="#">
there is no parent with nav-list class => wrong BEM

2020-11-03 16:11 UTC, irenhh commented on src/index.html
> +            <a class="nav-list__link" href="#">ВИДЕО</a>
this is usually achieved with `text-transform: uppercase`

2020-11-04 07:57 UTC, irenhh approved these changes

2020-11-11 12:47 UTC, mgrinko requested changes
Небольшое замечание
А что так и было задумано???
https://prnt.sc/vhdwps

2020-11-16 09:56 UTC, Denchepornyuk approved these changes

2023-04-05 21:23 UTC, closed without merging