add task solution
mate-academy/layout_moyo-header pull request #4683
Opened 2024-03-05 18:50 UTC by ser1stydent

- [DEMO LINK](https://ser1stydent.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://ser1stydent.github.io/layout_moyo-header/report/html_repor

2024-03-05 18:58 UTC, loralevitska requested changes
Please redeploy test report link 
![image](https://github.com/mate-academy/layout_moyo-header/assets/70009205/067201c6-6021-4c9e-9c6c-9c4166116a22)

2024-03-05 18:58 UTC, loralevitska commented on src/index.html
> +             href="#laptops s computers">Laptops & Computers</a>
```suggestion
            <a 
              class="nav__link laptops" 
              data-qa="hover"
              href="#laptops s computers"
            >
              Laptops & Computers
            </a>
```

2024-03-05 18:58 UTC, loralevitska commented on src/style.css
> +  align-items: center;
Rewrite styles in correct orders https://9elements.com/css-rule-order/
Fix all cases

2024-03-05 18:58 UTC, loralevitska commented on src/style.css
> + .logo {
Fix all cases (remove redundant whitespaces)
```suggestion
.logo {
```

2024-03-06 15:36 UTC, ser1stydent commented
- [DEMO LINK](https://ser1stydent.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://ser1stydent.github.io/layout_moyo-header/report/html_report/)

2024-03-06 15:36 UTC, ser1stydent commented
- [DEMO LINK](https://ser1stydent.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://ser1stydent.github.io/layout_moyo-header/report/html_report/)

2024-03-06 15:38 UTC, ser1stydent commented on src/index.html
> +             href="#laptops s computers">Laptops & Computers</a>
- [DEMO LINK](https://ser1stydent.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://ser1stydent.github.io/layout_moyo-header/report/html_report/)

2024-03-06 15:39 UTC, ser1stydent commented
> * [DEMO LINK](https://ser1stydent.github.io/layout_moyo-header/)
> * [TEST REPORT LINK](https://ser1stydent.github.io/layout_moyo-header/report/html_repor

2024-03-06 17:43 UTC, Esceype requested changes
Your demo now works but the issues are still the same, fix it and don`t forget to commit them and push

2024-03-07 20:18 UTC, closed without merging