Develop
mate-academy/layout_moyo-header pull request #4714
Opened 2024-03-09 02:42 UTC by Victor-Mirandas

- [DEMO LINK](https://Victor-Mirandas.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Victor-Mirandas.github.io/layout_moyo-header/report/html_report/)

2024-03-09 12:46 UTC, Viktor-Kost requested changes

2024-03-09 12:46 UTC, Viktor-Kost commented on src/index.html
> +          <li>
add seelctors
```suggestion
        <ul class="nav__list">
          <li class="nav__item">
```

2024-03-11 15:21 UTC, Victor-Mirandas commented
[DEMO LINK](https://victor-mirandas.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://victor-mirandas.github.io/layout_moyo-header/report/html_report/)

2024-03-12 01:45 UTC, closed without merging

2024-03-13 02:44 UTC, Victor-Mirandas commented
[DEMO LINK](https://victor-mirandas.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://victor-mirandas.github.io/layout_moyo-header/report/html_report/)

2024-03-13 02:45 UTC, Victor-Mirandas commented
[DEMO LINK](https://victor-mirandas.github.io/layout_moyo-header/)
[TEST REPORT LINK](https://victor-mirandas.github.io/layout_moyo-header/report/html_report/)

2024-03-14 02:17 UTC, Victor-Mirandas reviewed
- [DEMO LINK](https://Victor-Mirandas.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Victor-Mirandas.github.io/layout_moyo-header/report/html_report/)

2024-03-14 02:19 UTC, Victor-Mirandas commented
- [DEMO LINK](https://Victor-Mirandas.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Victor-Mirandas.github.io/layout_moyo-header/report/html_report/)