moyo header
mate-academy/layout_moyo-header pull request #4716
Opened 2024-03-09 16:31 UTC by julilut18

- [DEMO LINK](https://julilut18.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://julilut18.github.io/layout_moyo-header/report/html_report/)

- [x]Header height is set in 1 place (for the links)
- [x]Content is vertically centered (for any header height)
- [x]CSS is used to show all letters in Uppercase (don’t type them in HTML)
- [x]Logo is an image wrapped with a link
- [x]CSS Variable is used for a blue color
- [x]Pseudo-element is used for a blue line below the active link
- [x]Code follows all the [Code Style Rules ❗️](https://ivansierov.github.io/layout_moyo-header/checklist.html)

2024-03-09 19:25 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
Need to remove horizontall scroll
<img width="1512" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/64750958/e953060b-9aad-4b70-9db2-9e27aed96752">

Also, the other links should have only blue color when hovering without a line
<img width="720" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/64750958/4b28ef62-eb81-4677-9a80-8c93f8738ee8">

The height for the header must be only 60px
<img width="1108" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/64750958/0d9d3d64-7ac1-4f9d-ad9b-71e726fe523c">

2024-03-09 19:25 UTC, volodymyr-soltys97 commented on src/index.html
> +      <nav class="nav">
```suggestion
      </a>
      
      <nav class="nav">
```

2024-03-09 19:25 UTC, volodymyr-soltys97 commented on src/index.html
> +          <li class="nav_item"><a href="#">Samsung</a></li>
Fix code style everywhere
```suggestion
          <li class="nav_item">
            <a href="#">Samsung</a>
          </li>
```

2024-03-09 19:25 UTC, volodymyr-soltys97 commented on src/style.css
> +.header {
Need to add it for fix scroll
```suggestion
}

* {
  box-sizing: border-box;
}

.header {
```

2024-03-09 19:25 UTC, volodymyr-soltys97 commented on src/style.css
> +  background-color: #fff;
Default color, so you can just remove it
```suggestion
```

2024-03-09 19:25 UTC, volodymyr-soltys97 commented on src/style.css
> +a[data-qa='hover'] {
No need to use attributes as css selector, fix it

2024-03-09 19:25 UTC, volodymyr-soltys97 commented on src/style.css
> +.nav_item a.is-active::after {
```suggestion
.is-active::after {
```

2024-03-09 19:25 UTC, volodymyr-soltys97 commented on src/style.css
> +a.is-active {
Use the classes selector

2024-03-09 19:25 UTC, volodymyr-soltys97 commented on src/style.css
> +a:hover {
Use the classes selector

2024-03-10 07:10 UTC, julilut18 commented on src/style.css
> +a[data-qa='hover'] {
Якщо я його видаляю, або намагаюсь якось змінити у мене зникає синій колір зі слів laptops and computers

2024-03-10 07:15 UTC, julilut18 commented
Я не розумію, як виділили горизонтальну прокрутку. І також не розумію, як видалити голубий колір при наведенні миші. Можете, будь ласка, наштовхнути на думку? Будь-які дії ламають мій хедер

2024-03-10 15:44 UTC, VitaliyBondarenko1982 requested changes
Almost done.
Please check comments and fix some styles according comment.
It should help to fix tests.

2024-03-10 15:44 UTC, VitaliyBondarenko1982 commented on src/style.css
> +}
```suggestion

.nav_list {
  margin: 0;
  padding: 0;
  list-style: none;
  display: flex;
}

```

2024-03-10 15:44 UTC, VitaliyBondarenko1982 commented on src/style.css
> +}
```suggestion
```

2024-03-10 15:44 UTC, VitaliyBondarenko1982 commented on src/style.css
> +.nav_link.hover {
```suggestion
.nav_link:hover {
```

2024-03-11 07:25 UTC, etojeDenys approved these changes
good job

2024-03-11 07:25 UTC, etojeDenys commented on src/style.css
> +}
we don't need it

2025-02-20 08:01 UTC, closed without merging