add task solution
mate-academy/layout_moyo-header pull request #4867
Opened 2024-04-20 07:52 UTC by Grifion

- [DEMO LINK](https://Grifion.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Grifion.github.io/layout_moyo-header/report/html_report/)

- [x] Header height is set in 1 place (for the links)
- [x] Content is vertically centered (for any header height)
- [x] CSS is used to show all letters in Uppercase (don't type them in HTML)
- [x] Logo is an image wrapped with a link
- [x] CSS Variable is used for a blue color
- [x] Pseudo-element is used for a blue line below the active link
- [x] Code follows all the [Code Style Rules ❗️](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md)

2024-04-20 08:00 UTC, sTorba24 requested changes
Almost good! Lets improve it

2024-04-20 08:00 UTC, sTorba24 commented on src/style.css
> +  text-decoration: none;
you already have set it for .nav__link

2024-04-20 12:35 UTC, SanyaBratashchuk requested changes

2024-04-20 12:35 UTC, SanyaBratashchuk commented on src/style.css
> +  text-decoration: none;
```suggestion
```

2024-04-20 12:35 UTC, SanyaBratashchuk commented on src/style.css
> +  flex-direction: row;
```suggestion
```
default value

2024-04-24 18:22 UTC, SanyaBratashchuk approved these changes

2026-05-17 17:35 UTC, closed without merging