Moyo header
mate-academy/layout_moyo-header pull request #4880
Opened 2024-04-24 20:43 UTC by pvnovikova

- [DEMO LINK](https://pvnovikova.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://pvnovikova.github.io/layout_moyo-header/report/html_report/)

 [x] Header height is set in 1 place (for the links)
 [x] Content is vertically centered (for any header height)
 [x] CSS is used to show all letters in Uppercase (don't type them in HTML)
 [x] Logo is an image wrapped with a link
 [x] CSS Variable is used for a blue color
 [x] Pseudo-element is used for a blue line below the active link
 [x] Code follows all the [Code Style Rules ❗️](https://github.com/pvnovikova/layout_moyo-header/blob/master/checklist.md)

2024-04-25 05:35 UTC, etojeDenys requested changes
try to pass all tests, then re-request the review

or feel free to ask for some help in the chat

2024-04-25 05:35 UTC, etojeDenys commented on src/style.css
> +}
<img width="1103" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/70220667/30a437fe-8b02-4173-a131-8cba7442b0af">

2024-04-25 05:35 UTC, etojeDenys commented on src/style.css
> +}
```suggestion
.nav__link:hover,
.nav__link:active,
.is-active {
  color: #00acdc;
}
```

2024-04-25 05:35 UTC, etojeDenys commented on src/style.css
> +}
move this color to some var and reuse it everywhere

2024-05-03 13:52 UTC, l4st1m0za requested changes
Your test are still wierdly broken :( 
You can always write in FE chat, if you have anu difficulties!

2024-05-06 14:58 UTC, closed without merging

2024-05-06 15:00 UTC, GUSILLUS requested changes
GJ! Turn off draft mode, and fix a little bit codestyle

2024-05-06 15:00 UTC, GUSILLUS commented on src/style.css
> +  width: 40px;
you can move it to a variable

2024-05-06 15:29 UTC, pvnovikova commented
@GUSILLUS please review https://github.com/mate-academy/layout_moyo-header/pull/4928. Thank you