Moyo header
mate-academy/layout_moyo-header pull request #4969
Opened 2024-05-22 17:08 UTC by andrewsiemakin

2024-05-22 17:30 UTC, vasylhnatiuk requested changes
This answer was sent in wrong group

2024-05-22 17:40 UTC, andrewsiemakin commented
> This answer was sent in wrong group

So what i need to do right now?

2024-05-23 05:17 UTC, vsmutok requested changes
If you have changed your course track, please inform your coordinator.

2024-05-23 08:41 UTC, etojeDenys requested changes

2024-05-23 08:41 UTC, etojeDenys commented on readme.md
> +- [TEST REPORT LINK](https://<andrewsiemakin>.github.io/layout_moyo-header/report/html_report/)
```suggestion
- [TEST REPORT LINK](https://andrewsiemakin.github.io/layout_moyo-header/report/html_report/)
```
fix your links

2024-05-23 08:41 UTC, etojeDenys commented on src/style.css
> +}
```suggestion
.navbar__button:hover,
.navbar__button.is-active {
  color: var(--blue-color);
}
```

2024-05-23 08:56 UTC, lerastarynets approved these changes
Keep up the great work!

2026-03-04 11:30 UTC, closed without merging