add task solution
mate-academy/layout_moyo-header pull request #4971
Opened 2024-05-23 12:21 UTC by kriukvlad

[x] Header height is set in 1 place (for the links)
[x] Content is vertically centered (for any header height)
[x] CSS is used to show all letters in Uppercase (don't type them in HTML)
[x] Logo is an image wrapped with a link
[x] CSS Variable is used for a blue color
[x] Pseudo-element is used for a blue line below the active link
[x] Code follows all the [Code Style Rules ❗️](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md)

2024-05-23 12:40 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-05-23 12:40 UTC, anastasiiavorobiova commented on src/index.html
> +              <div class="line"></div>
```suggestion

```
No need to use an additional div here

2024-05-23 12:40 UTC, anastasiiavorobiova commented on src/style.css
> +  position: absolute;
```suggestion
  position: absolute;
  left: 0;
```

2024-05-24 07:47 UTC, volodymyr-soltys97 requested changes
Almost done!
Let's make your code better

2024-05-24 07:47 UTC, volodymyr-soltys97 commented on readme.md
> +- [TEST REPORT LINK](https://kriukvlad.github.io/layout_moyo-header/report/html_report/)
Add these links to the PR description 
<img width="981" alt="image" src="https://github.com/mate-academy/layout_moyo-header/assets/64750958/39a8f5ac-ad96-4e71-b887-9b4ebd30c20e">

2024-05-24 07:47 UTC, volodymyr-soltys97 commented on src/index.html
> +          <li class="nav__item">
Add the blank line between the links 
```suggestion
          </li>
          
          <li class="nav__item">
```

2024-05-24 07:47 UTC, volodymyr-soltys97 commented on src/style.css
> +  --main-bg-color: rgba(255, 255, 255, 1);
Create a css variables with root selector 
https://www.w3schools.com/css/css3_variables.asp

2024-05-24 07:47 UTC, volodymyr-soltys97 commented on src/style.css
> +  font-style: normal;
This value is default
```suggestion
```

2024-05-24 07:47 UTC, volodymyr-soltys97 commented on src/style.css
> +  text-transform: uppercase;
Move font styles to the html selector, it will be better

2024-05-24 08:52 UTC, kriukvlad commented
- [DEMO LINK](https://kriukvlad.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://kriukvlad.github.io/layout_moyo-header/report/html_report/)

[x] Header height is set in 1 place (for the links)
[x] Content is vertically centered (for any header height)
[x] CSS is used to show all letters in Uppercase (don't type them in HTML)
[x] Logo is an image wrapped with a link
[x] CSS Variable is used for a blue color
[x] Pseudo-element is used for a blue line below the active link
[x] Code follows all the [Code Style Rules ❗️](https://github.com/mate-academy/layout_moyo-header/blob/master/checklist.md)

2024-05-24 09:06 UTC, volodymyr-soltys97 approved these changes
GJ!

2024-05-24 09:17 UTC, closed without merging