add solution
mate-academy/layout_moyo-header pull request #5071
Opened 2024-06-20 08:44 UTC by TYaroslav20

- [DEMO LINK](https://TYaroslav20.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://TYaroslav20.github.io/layout_moyo-header/report/html_report/)

2024-08-06 11:44 UTC, Moroz-Dmytro requested changes

2024-08-06 11:44 UTC, Moroz-Dmytro commented on src/index.html
> +          alt="logo"
```suggestion
          alt="MOYO logo"
```

2024-08-06 11:44 UTC, Moroz-Dmytro commented on src/index.html
> +          href="./index.html"
```suggestion
          href="#apple"
```
Change all other links

2024-08-06 11:44 UTC, Moroz-Dmytro commented on src/style.css
> +  width: calc(100% - 100px);
Width should be 100%
Use `box-sizing: border-box` instead

2024-08-06 11:44 UTC, Moroz-Dmytro commented on src/style.css
> +  margin-right: 0 !important;
Don't use `!important`
Try to increase specificity instead

2024-08-07 10:59 UTC, polosanya requested changes
Keep up the good work)
Please fix all the comments from above.
Also, it would be great to add box-shadow property for header
![image](https://github.com/user-attachments/assets/7ddc1dc9-3d88-4cc0-ab93-77fd2fa4ba8c)

2024-08-07 13:26 UTC, polosanya requested changes
Comments above

2024-08-08 09:50 UTC, Moroz-Dmytro requested changes
Please, fix all comments above

2024-08-10 14:01 UTC, VenomMB requested changes
Please, fix all comments above

2024-08-10 14:01 UTC, VenomMB requested changes
.

2024-08-10 14:03 UTC, VenomMB requested changes
.

2024-08-11 07:02 UTC, BudnikOleksii requested changes
For some reason, this PR is on the review, but I don't see any new commits, looks like something is wrong with the status in the system. So, try to reject one more time

2024-08-12 12:08 UTC, VolodymyrKirichenko requested changes
this PR is under consideration, but there are no new commits
It seems that something is wrong with the system. So try reject again.
Dev-team are aware of this issue and will try to resolve it ASAP

2024-08-13 12:10 UTC, VolodymyrKirichenko requested changes
Please, fix all comments above

2024-08-13 15:33 UTC, Moroz-Dmytro requested changes
Please, fix all comments above

2024-09-02 16:55 UTC, VenomMB requested changes
Please, fix all comments above

2024-09-02 16:55 UTC, VenomMB requested changes
.

2024-09-09 10:01 UTC, igorkruz requested changes
Please, fix all comments above

2024-09-11 09:29 UTC, igorkruz requested changes
.

2025-02-24 12:50 UTC, closed without merging