Develop
mate-academy/layout_moyo-header pull request #5100
Opened 2024-06-30 20:27 UTC by RomanMartseniuk

- [DEMO LINK](https://RomanMartseniuk.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://RomanMartseniuk.github.io/layout_moyo-header/report/html_report/)

- [x] Header height is set in 1 place (for the links)
- [x] Content is vertically centered (for any header height)
- [x] CSS is used to show all letters in Uppercase (don't type them in HTML)
- [x] Logo is an image wrapped with a link
- [x] **CSS Variable** is used for a blue color
- [x] Pseudo-element is used for a blue line below the active link
- [x] Code follows all the [Code Style Rules ❗️](./checklist.md)

2024-07-01 05:58 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/index.html
> +      <div class="header__container">
This div is redundant
```suggestion
```

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/index.html
> +          <ul class="header__list">
```suggestion
        <nav class="nav">
          <ul class="nav__list">
```

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/index.html
> +            <li class="header__item is-active">
Fix classes everywhere
```suggestion
            <li class="nav__item">
```

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/index.html
> +                class="header__link is-active"
The same
```suggestion
                class="nav__link is-active"
```

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/index.html
> +            <li class="header__item">
Add the blank line between the links
```suggestion
            </li>
            
            <li class="header__item">
```

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/style.css
> +  --hover-color: #00acdc;
Create a variable with `:root` selector

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/style.css
> +  top: 0;
Don't need to use position here
```suggestion
```

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/style.css
> +.header__item.is-active::after {
```suggestion
.is-active::after {
```

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/style.css
> +  width: 37px;
```suggestion
  width: 100%;
```

2024-07-01 05:58 UTC, volodymyr-soltys97 commented on src/style.css
> +.header__link[data-qa='hover']:hover {
Use only classes selector
```suggestion
.header__link:hover {
```

2024-07-07 11:16 UTC, anastasiiavorobiova approved these changes
Great work!

2025-12-26 21:07 UTC, closed without merging