add task solution
mate-academy/layout_moyo-header pull request #5172
Opened 2024-07-24 21:29 UTC by labelsavchuk

- [DEMO LINK](https://labelsavchuk.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://labelsavchuk.github.io/layout_moyo-header/report/html_report/)

2024-08-07 07:29 UTC, Moroz-Dmytro requested changes

2024-08-07 07:29 UTC, Moroz-Dmytro commented on src/index.html
> +      <nav class="nav">
```suggestion
      </a>
      
      <nav class="nav">
```

2024-08-07 07:29 UTC, Moroz-Dmytro commented on src/index.html
> +          <li class="nav-list">
```suggestion
          </li>
          
          <li class="nav-list">
```

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/6d3e41ee-3799-46a9-b1f5-8e80d1b8e090">

2024-08-07 07:29 UTC, Moroz-Dmytro commented on src/index.html
> +              href="index.html"
```suggestion
              href="#samsung"
```
Change all links

2024-08-07 07:29 UTC, Moroz-Dmytro commented on src/style.css
> +ul > :last-of-type:last-of-type {
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/bb772f67-0955-40e1-aa13-15283ffa2a74">

2024-08-07 07:29 UTC, Moroz-Dmytro commented on src/style.css
> +  /* чтоб убрать лишнее место под картинкой в сылке */
Don't leave comments in code

2024-08-10 20:11 UTC, labelsavchuk commented
- [DEMO LINK](https://labelsavchuk.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://labelsavchuk.github.io/layout_moyo-header/report/html_report/)

2024-10-14 12:29 UTC, BudnikOleksii approved these changes
Good job 👍

2024-10-14 12:29 UTC, BudnikOleksii commented on src/style.css
> +  src: url(fonts/Roboto/Roboto-Medium.ttf);
You can use fonts from google fonts https://fonts.google.com/specimen/Roboto

2025-06-15 10:38 UTC, closed without merging