moyo-header solution
mate-academy/layout_moyo-header pull request #520
Opened 2021-01-15 16:30 UTC by yashnyi

- [DEMO LINK](https://yashnyi.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://yashnyi.github.io/layout_moyo-header/report/html_report/)

2021-01-18 16:26 UTC, Vladimir-Beliy requested changes

2021-01-18 16:26 UTC, Vladimir-Beliy commented on src/index.html
> +          <li class="header-nav__list-el">
```suggestion
      <nav class="nav">
        <ul class="nav__list">
          <li class="nav__item">
```

2021-01-18 16:26 UTC, Vladimir-Beliy commented on src/index.html
> +              class="header-nav__link header-nav__link--active is-active">Apple
```suggestion
              class="nav__link nav__link--active">Apple
```

2021-01-18 16:58 UTC, yashnyi commented on src/index.html
> +              class="header-nav__link header-nav__link--active is-active">Apple
клас .is-active вимагають тести, тому видалив .nav__link--active.

2021-01-19 11:37 UTC, Vladimir-Beliy approved these changes

2025-09-01 20:49 UTC, closed without merging