Develop
mate-academy/layout_moyo-header pull request #5346
Opened 2024-09-09 13:36 UTC by RareHelix

- [DEMO LINK](https://RareHelix.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://RareHelix.github.io/layout_moyo-header/report/html_report/)
- 
 Header height is set in 1 place (for the links)
 Content is vertically centered (for any header height). - [x]
 CSS is used to show all letters in Uppercase (don't type them in HTML) - [x]
 Logo is an image wrapped with a link - [x]
 CSS Variable is used for a blue color
 Pseudo-element is used for a blue line below the active link - [x]
 Code follows all the [Code Style Rules ❗️] - [x](https://github.com/RareHelix/layout_moyo-header/blob/master/checklist.md)

2024-09-09 13:40 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-09-09 13:40 UTC, anastasiiavorobiova commented on src/style.css
> +} */
```suggestion

```

2024-09-09 13:40 UTC, anastasiiavorobiova commented on src/style.css
> +  color: #00acdc;
Consider using variables for repeating colors

2024-09-09 14:20 UTC, RareHelix reviewed
Змінила ноуд на 20, можливо через це не пропускає

2024-09-09 15:46 UTC, RareHelix commented on src/style.css
> +}
Не розумію,що тут виправити?

2024-09-09 15:46 UTC, RareHelix commented on src/style.css
> +}
Не розумію,що тут виправити?

2024-09-09 15:46 UTC, RareHelix commented on src/style.css
> +}
Не розумію,що тут виправити?

2024-09-09 18:16 UTC, etojeDenys requested changes

2024-09-09 18:16 UTC, etojeDenys commented on src/style.css
> +}
видалити цей селектор

2024-09-09 18:16 UTC, etojeDenys commented on src/style.css
> +}
видалити теж

2024-09-09 18:16 UTC, etojeDenys commented on src/style.css
> +}
видалити

2024-09-10 07:32 UTC, etojeDenys requested changes
you still haven't fix all prev comments
<img width="725" alt="image" src="https://github.com/user-attachments/assets/33923c3f-32f5-4d59-814a-51f9826b3dda">

2024-09-10 08:01 UTC, volodymyr-soltys97 requested changes
Hi, you need to fix all comments from the previous review, if you need help feel free in the fe_chat

2024-09-10 08:03 UTC, RareHelix commented
I make changes and write, but they are not saved for some reason

вт, 10 вер. 2024 р. о 11:02 Volodymyr Soltys ***@***.***>
пише:

> ***@***.**** requested changes on this pull request.
>
> Hi, you need to fix all comments from the previous review, if you need
> help feel free in the fe_chat
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_moyo-header/pull/5346#pullrequestreview-2291670227>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BH4X7TNMODD5D2UFEE7BBATZV2RQDAVCNFSM6AAAAABN4SK7ECVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOJRGY3TAMRSG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-10 11:12 UTC, anastasiiavorobiova approved these changes
Great work!

2024-09-10 11:12 UTC, anastasiiavorobiova commented on src/style.css
> +.nav_list:first-child {
```suggestion
.nav__item:first-child {
```

2024-11-20 09:04 UTC, closed without merging