add tast solution
mate-academy/layout_moyo-header pull request #5419
Opened 2024-09-26 11:17 UTC by AnhelinaSh2001

- [DEMO LINK](https://AnhelinaSh2001.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://AnhelinaSh2001.github.io/layout_moyo-header/report/html_report/)

2024-09-26 11:17 UTC, mateacademy-ai-mentor approved these changes
Great work on your Pull Request! 🌟 There are a few suggestions to improve the code, such as considering responsive units for padding, not fixing container sizes, adding fallback fonts, and avoiding the universal selector for better performance. Also, watch out for the `href` attributes in your anchor tags and indentation in your HTML. These are minor issues and don't warrant a change request, but keep them in mind for future projects to make your code even better! Happy coding! 💻

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-09-26 11:17 UTC, mateacademy-ai-mentor commented on src/index.html
> +        </ul>
Add empty lines between multiline sibling blocks of HTML for better readability. There should be an empty line between each `<li>` block.

2024-09-26 11:17 UTC, mateacademy-ai-mentor commented on src/index.html
> +        </a>
Don't use spaces in `<a>` tag's `href` property for internal navigation. Use `#` followed by the anchor name or leave it empty if it's a placeholder.

2024-09-26 11:17 UTC, mateacademy-ai-mentor commented on src/index.html
> +            >
All `<a>` tags have `href` properties with `index.html` which might not be the intended behavior for navigation. If these are placeholder links, consider using `#` or `#some-anchor` format.

2024-09-26 11:17 UTC, mateacademy-ai-mentor commented on src/style.css
> +  box-sizing: border-box;
Don't use the `*` selector as it impacts performance. Set styles only for elements that require them. Consider setting `margin`, `padding`, and `box-sizing` in a more specific selector or element.

2024-09-26 11:17 UTC, mateacademy-ai-mentor commented on src/style.css
> +  font-family: Roboto, sans-serif;
Remember to use fallback fonts - alternative font-family in case the main one doesn't work. For example, `font-family: Roboto, Arial, sans-serif;`.

2024-09-26 11:17 UTC, mateacademy-ai-mentor commented on src/style.css
> +.logo-container {
Don't fix container size (if there is no such a requirement). Let the content size dictate it to avoid overflow or accidental scrollbar.

2024-09-26 11:17 UTC, mateacademy-ai-mentor commented on src/style.css
> +.nav__container {
Be cautious when using fixed `padding-left` values as they can cause layout issues on smaller screens. Consider using responsive units or CSS Grid/Flexbox properties to manage spacing.

2024-09-26 11:29 UTC, anastasiiavorobiova requested changes
Great work! Added comments to fix

2024-09-26 11:29 UTC, anastasiiavorobiova commented on src/index.html
> +              class="nav__link"
```suggestion
              class="nav__link is-active"
```

2024-09-26 11:29 UTC, anastasiiavorobiova commented on src/index.html
> +              class="nav__link is-active"
```suggestion
              class="nav__link"
```

2024-09-26 11:29 UTC, anastasiiavorobiova commented on src/style.css
> +  left: 50px;
```suggestion

```
Consider leveraging document flow

2024-09-26 11:29 UTC, anastasiiavorobiova commented on src/style.css
> +  color: rgba(0, 172, 220, 1);
Consider using variables for repeating colors

2024-09-26 11:29 UTC, anastasiiavorobiova commented on src/style.css
> +  padding-left: 419px;
```suggestion

```

2024-09-26 11:29 UTC, anastasiiavorobiova commented on src/style.css
> +.nav__container a {
Consider using classes for styling

2024-09-26 11:29 UTC, anastasiiavorobiova commented on src/style.css
> +  height: 23px;
The height should be 60px

2024-09-30 10:38 UTC, lerastarynets requested changes
Well done, pls try to pass all tests from backstop before asking for review again)
Pls ask for help in **fe_chat** if you don't understand something

2024-10-03 12:20 UTC, closed without merging