MOYO header GP first attempt
mate-academy/layout_moyo-header pull request #699
Opened 2021-05-26 05:50 UTC by gponomarenko

- [DEMO LINK](https://gponomarenko.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://gponomarenko.github.io/layout_moyo-header/report/html_report/)

2021-05-26 11:01 UTC, ArtemTopolskyi requested changes
Не пиши текст капсом, используй свойство text-transform: uppercase

2021-05-26 17:25 UTC, ArtemTopolskyi requested changes

2021-05-26 17:25 UTC, ArtemTopolskyi commented on src/index.html
> +            >Ноутбуки и компьютеры
```suggestion
            <a
              class="nav__link"
              href="#"
              data-qa="hover"
            >
              Ноутбуки и компьютеры
```

2021-05-26 17:25 UTC, ArtemTopolskyi commented on src/style.css
> +  right: 0;
Зачем эти свойства, у тебя ведь нет свойства position

2021-05-26 17:25 UTC, ArtemTopolskyi commented on src/style.css
> +  margin-left: -20px;
Не используй отрицательные margin без острой необходимости

2021-05-26 19:17 UTC, gponomarenko commented on src/style.css
> +  margin-left: -20px;
прибрав цей маржин

2021-05-26 19:18 UTC, gponomarenko commented on src/style.css
> +  right: 0;
ОК

2021-05-26 19:21 UTC, gponomarenko commented on src/index.html
> +            >Ноутбуки и компьютеры
відкориговано

2021-05-27 06:46 UTC, ArtemTopolskyi approved these changes

2021-05-27 06:46 UTC, ArtemTopolskyi commented on src/index.html
> +            >
```suggestion
            <a
              class="nav__link"
              href="#"
              data-qa="hover"
            >
```

2023-11-06 19:35 UTC, closed without merging