Fs may19 dmitry y
mate-academy/layout_moyo-header pull request #75
Opened 2019-05-30 00:34 UTC by danheim

Некоторые расхождения в шрифте, также не понимаю почему сдвигается при третей и четвёртой проверке. 

- [DEMO LINK](https://danheim.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://danheim.github.io/layout_moyo-header/report/html_report/)

2019-05-31 02:47 UTC, mgrinko commented on src/index.html
> +          <a href="" class="nav-link">Ппаншеты</a>
опечатка

2019-05-31 02:50 UTC, mgrinko commented on src/style.css
> +  font-family: "Roboto", Arial, sans-serif;
А нужны ли кавычки и Arial

2019-05-31 02:54 UTC, mgrinko commented on src/index.html
> +      <img src="./images/logo.png" alt="">
А может можно без обёртки вокруг картинки обойтись?
а почему пустой `alt` ?

2019-05-31 02:56 UTC, mgrinko commented on src/style.css
> +}
ссылка должна занимать всю высоту

2019-05-31 02:57 UTC, mgrinko commented on src/style.css
> +.is-active::after {
это любой элемент может быть is-active
Или только навигационная ссылка?

2019-05-31 02:59 UTC, mgrinko commented on src/style.css
> +  border-radius: 8px;
странно что border-radius больше высоты

2019-05-31 03:00 UTC, mgrinko commented on src/style.css
> +  padding: 23px 0;
я думаю тут всё решается line-height

2019-05-31 03:01 UTC, mgrinko commented on src/style.css
> +}
я обычно использую 
margin-bottom / margin-right

2019-05-31 03:01 UTC, mgrinko requested changes
Жду правок

2019-05-31 03:01 UTC, danheim commented
Благодарю, работаю.

2019-05-31 06:07 UTC, mgrinko commented on src/style.css
> +}
прям все картинки на странице будут с такими стилями
ты же этот код будешь на странице использовать

2019-05-31 06:08 UTC, mgrinko commented on src/style.css
> +}
и зачем теперь тут flex?

2019-05-31 06:08 UTC, mgrinko commented on src/style.css
> +  height: 60px;
а высота уже не нужна

2019-05-31 06:09 UTC, mgrinko commented on src/style.css
> +}
а что этот класс где угодно на странице так должен работать?

2019-05-31 06:09 UTC, mgrinko commented on src/style.css
> +  border-radius: 1px;
50%

2019-05-31 06:09 UTC, mgrinko requested changes
ещё один раунд

2019-06-03 04:18 UTC, mgrinko commented on src/scss/main.scss
> +    .nav-link {
не надо делать такую большую вложенность делать в стилях

2019-06-03 04:18 UTC, mgrinko commented on src/scss/main.scss
> +      border-radius: 1px;
2px

2019-06-03 04:19 UTC, mgrinko commented on src/scss/main.scss
> +// }
зачем тут столько закомментированного кода

2019-06-03 04:23 UTC, mgrinko commented on src/scss/main.scss
> +    margin-left: 20px;
right?

2019-06-03 04:23 UTC, mgrinko requested changes
Отступы поправь

2019-06-03 04:30 UTC, danheim commented on src/scss/main.scss
> +    margin-left: 20px;
@mgrinko
```
  .nav-item:not(:last-child) {
    margin-right: 20px;
  }
```
Разве что так? Не понимаю почему у меня в третьем и четвёртом съезжает влево. Съезжает даже если добавляю margin-right каждому nav-item.

2019-06-03 05:25 UTC, danheim commented
Изменил отступы на right, border-radius и удалил неиспользуемый код.

2019-06-03 05:58 UTC, mgrinko commented on src/scss/main.scss
> +body {  margin: 0;
перенос

2019-06-03 05:58 UTC, mgrinko approved these changes
принято

2026-08-23 16:51 UTC, closed without merging