moyo_header
mate-academy/layout_moyo-header pull request #757
Opened 2021-06-25 11:29 UTC by anton-forzun

2021-06-25 12:12 UTC, mykola-yarchuk requested changes

2021-06-25 12:12 UTC, mykola-yarchuk commented on src/index.html
> +      <div class="logo"></div>
це повинна бути клікабельна лінка

2021-06-25 12:12 UTC, mykola-yarchuk commented on src/style.css
> +  width: 37px;
якщо написати 100 % то буде працювати для любої ширини

2021-06-25 12:12 UTC, mykola-yarchuk commented on src/style.css
> +  top: 56px;
краще bottom 0

2021-06-25 12:12 UTC, mykola-yarchuk commented on src/style.css
> +  width: 1200px;
не задавай конкретне число, це хардкод, потрбіно щоб хедер просто був на всю ширину екрану

2021-06-29 09:57 UTC, anton-forzun commented on src/style.css
> +  top: 56px;
я замінюю на  bottom 0 і лінія знаходиться в самому низу?Не можу зрозуміти для чого це?

2021-06-29 09:58 UTC, anton-forzun commented on src/style.css
> +  width: 37px;
Якщо ставлю ширину 100 % то лінія йде по всій ширині а потрібно щоб була підкресоенна.Чи я не так зрозумів?

2021-06-29 12:42 UTC, vpolets requested changes

2021-06-29 12:42 UTC, vpolets commented on src/index.html
> +      <a href="" class="logo" ></a>
в лінку запхай картинку, вона не має бути просто фоном

2021-06-29 12:42 UTC, vpolets commented on src/style.css
> +  width: 37px;
щоб не йшла по всій ширині треба додати position: relative для батьківського елемента

2021-06-29 14:27 UTC, vpolets approved these changes

2021-06-29 14:27 UTC, vpolets commented on src/index.html
> +      <a href="./images/logo.png" class="logo" ></a>
```suggestion
      <a href="./images/logo.png" class="logo" >
        <img src... />
      </a>
```

2021-07-01 08:44 UTC, closed without merging