Develop
mate-academy/layout_moyo-header pull request #759
Opened 2021-06-27 11:11 UTC by Dinexpod

[DEMO LINK](https://Dinexpod.github.io/layout_moyo-header/)

2021-06-29 12:30 UTC, vkryvytskyy requested changes
![image](https://user-images.githubusercontent.com/38065883/123797202-9c3d2100-d8ee-11eb-9981-df456fcec6c6.png)
![image](https://user-images.githubusercontent.com/38065883/123797243-a828e300-d8ee-11eb-99e0-761b432fdff9.png)
Выглядит не так, как в дизайне, и вылезает за пределы хедера

2021-06-29 12:30 UTC, vkryvytskyy commented on readme.md
>      - [TEST REPORT LINK](https://<your_account>.github.io/layout_moyo-header/report/html_report/)
Ссылка на тесты тоже должна быть рабочей

2021-06-29 12:30 UTC, vkryvytskyy commented on src/index.html
> +    >
обычно logo это еще и ссылка на главную страницу

2021-06-29 12:30 UTC, vkryvytskyy commented on src/index.html
> +          </li>
Тут текст пиши обычным кеглем, а через css делай uppercase

2021-06-29 12:30 UTC, vkryvytskyy commented on src/style.css
> +li {
Не стилизуй теги, используй классы, тем более что у тебя есть ниже класс `.li`

2021-06-29 12:30 UTC, vkryvytskyy commented on src/style.css
> +}
Я уверен тебе надо что-то одно из этого

2021-06-29 12:30 UTC, vkryvytskyy commented on src/style.css
> +}
И тут только одно

2021-09-25 11:54 UTC, Dinexpod commented on readme.md
>      - [TEST REPORT LINK](https://<your_account>.github.io/layout_moyo-header/report/html_report/)
ok

2021-09-25 11:54 UTC, Dinexpod commented on src/index.html
> +    >
согласен)

2021-09-25 12:08 UTC, Dinexpod commented on src/index.html
> +          </li>
ага, делал апперкейс) просто этот текст перекопипастил с фигмы)

2021-09-25 12:22 UTC, Dinexpod commented on src/style.css
> +li {
окей

2021-09-25 12:23 UTC, Dinexpod commented on src/style.css
> +}
ну да, через время как то по другому на это смотрится) исправил

2021-09-25 12:23 UTC, Dinexpod commented on src/style.css
> +}
ок

2026-05-10 22:10 UTC, closed without merging