My solution
mate-academy/layout_moyo-header pull request #812
Opened 2021-07-08 12:28 UTC by Andrii-Pinchuk

I created header with working focus and hover. It's working, but how can I change space beetween the elements (links) without paddings and margins? Turn .nav in flex box too inside .header box?

2021-07-08 13:52 UTC, herkoss commented
А где синяя лини снизу и почему текст Apple не синий?)

<img width="1440" alt="Снимок экрана 2021-07-08 в 16 52 11" src="https://user-images.githubusercontent.com/61412282/124933809-d902c980-e00c-11eb-878b-17508821db62.png">

2021-07-08 13:53 UTC, herkoss requested changes
Well done, but there are some little mistakes)

2021-07-08 13:53 UTC, herkoss commented on src/index.html
> +      >
```suggestion
        >
```

2021-07-09 08:28 UTC, herkoss approved these changes
Well done!) 👍✅

2021-07-09 11:15 UTC, danheim approved these changes

2025-10-29 15:50 UTC, closed without merging