Moyo-head
mate-academy/layout_moyo-header pull request #837
Opened 2021-07-23 11:22 UTC by DariaVeretyak

2021-07-23 12:49 UTC, vkryvytskyy submitted a review, later dismissed

2021-07-23 12:49 UTC, vkryvytskyy commented on readme.md
> +- [TEST REPORT LINK](https://<DariaVeretyak>.github.io/layout_moyo-header/report/html_report/)
```suggestion
- [DEMO LINK](https://DariaVeretyak.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://DariaVeretyak.github.io/layout_moyo-header/report/html_report/)
```
Проверяй работают ли ссылки, которые ты оставляешь, с этим скобочками - не работают

2021-07-23 12:49 UTC, vkryvytskyy commented on readme.md
> +- [TEST REPORT LINK](https://<DariaVeretyak>.github.io/layout_moyo-header/report/html_report/)
![image](https://user-images.githubusercontent.com/38065883/126783257-b17a7bbc-307c-4cdd-b10d-43edad263826.png)
Тебе надо сделать один хедер, который будет размещаться вверху страницы, и растягиваться под ее текущий размер

2021-07-23 12:49 UTC, vkryvytskyy commented on index.html
> +      <a class="page page8" href="#page8">ВИДЕО</a>
Тут текст пиши обычным кеглем, а через css делай uppercase

2021-07-23 12:49 UTC, vkryvytskyy commented on index.html
> +      <a class="page" href="#page2">SAMSUNG</a>
```suggestion
      <a class="page" href="#">SAMSUNG</a>
```
Для всех ссылок этого будет достаточно

2021-07-23 12:49 UTC, vkryvytskyy commented on index.html
> +    <nav class="pages menu1024px">
```suggestion
    <nav class="pages">
```
Не надо дополнительных классов, ограничивающих ширину

2021-07-23 12:49 UTC, vkryvytskyy commented on index.html
> +</head>
Что тут с форматированием? Все внутренние теги должны быть на одном уровне

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +}
Не надо задавать бекраунд для body

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +  flex-direction: row;
display: flex по умолчанию работает с flex-direction: row

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +  background-image: url(src/images/logo.png);
logo должно быть ссылкой с картинкой внутри, расположенным в теге nav

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +}
Не надо ограничивать ширину меню. В дизайне просто показано как это меню выглядить на 1024 и на 1200 пикселей, что единственное что меняется - отступ между лого и ссылками

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +}
Используй :last-child чтобы найти последнюю ссылку

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +a:visited {
Используй классы для стилизации, не используй теги

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +  font-family: 'Roboto', sans-serif;
font-family достаточно задать один раз для body

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +  margin-top: 18.5px;
Не устанавливай дробные значения

2021-07-23 12:49 UTC, vkryvytskyy commented on style.css
> +  margin-top: 18.5px;
https://codepen.io/adskiy/pen/gOWGeLV
Вот пример того, как это должно быть реализовано

2021-07-26 18:44 UTC, mykola-yarchuk requested changes
![image](https://user-images.githubusercontent.com/35385361/127041207-6e6f4a32-ca0e-4490-b547-26b2fe902bf0.png)
gh-pages не працює, перевір налаштування репозиторію,source повинен бути встановлений в gh-pages

2021-07-26 18:44 UTC, mykola-yarchuk commented on src/index.html
> +        <a class="page" href="#">Видео</a>
давай зробимо це списком `ul` і кожна лінка буде `li`

2021-07-26 18:44 UTC, mykola-yarchuk commented on src/style.css
> +  bottom: -18px;
-18 це не ок, давай зробимо `li` елементи вони будуть мати висоту і тоді ця лінія (after) буде прикраплено до низу за допомогою botoom: 0

2021-07-26 18:44 UTC, mykola-yarchuk commented on src/style.css
> +.pages {
```suggestion
.nav {
```

2021-07-26 18:44 UTC, mykola-yarchuk commented on src/style.css
> +.page {
nav__item

2021-07-26 18:44 UTC, mykola-yarchuk commented on src/style.css
> +  flex-grow: 1;
а для чого flex-grow?

2021-07-26 18:44 UTC, mykola-yarchuk commented on src/style.css
> +.page:active:not(:first-child)::after {
можна просітше, тут якось дуже складно

2021-07-27 20:51 UTC, DariaVeretyak commented on src/style.css
> +  flex-grow: 1;
flex-grow використовую, щоб в залежності від розширення екрану, всі лінки залишались на своїх місцях і інтервали між ними не змінювались. При цьому вільний простір між логотипом і першою ссилкою пристосовувався до змін.
Чи потрібно іншим способом?

2022-11-06 14:24 UTC, closed without merging