MOYO header
mate-academy/layout_moyo-header pull request #84
Opened 2019-05-30 13:42 UTC by Hlybchenko

- [DEMO LINK](https://hlybchenko.github.io/layout_moyo-header/) <br>
 - [TEST REPORT LINK](https://hlybchenko.github.io/layout_moyo-header/report/html_report/)

2019-05-31 05:52 UTC, mgrinko commented on src/index.html
> +      </nav>
1) список лучше делать списком
2) одна ссылка это не `navigation`

2019-05-31 05:52 UTC, mgrinko commented on src/index.html
> +        <a href="#"></a>
лого это важная картинка а не просто бэкграунд

2019-05-31 05:53 UTC, mgrinko commented on src/style.css
> +.mainBox {
когда это будет на странице
то название класса явно не будет соответствовать назначению

2019-05-31 05:53 UTC, mgrinko commented on src/style.css
> +  flex-direction: row;
это значение по умолчанию

2019-05-31 05:54 UTC, mgrinko commented on src/style.css
> +  margin: 0 auto;
а это зачем?

2019-05-31 05:54 UTC, mgrinko commented on src/style.css
> +  background-color: white;
по умолчанию

2019-05-31 05:54 UTC, mgrinko commented on src/style.css
> +  padding: 10px 50px;
нет ссылки должны быть на всю высоту

2019-05-31 05:55 UTC, mgrinko commented on src/style.css
> +  background: url("./images/logo.png") center no-repeat;
<img>

2019-05-31 05:55 UTC, mgrinko commented on src/style.css
> +  align-content: center;
тут всего 1 ряд
так что вырасниваем `items`

2019-05-31 05:56 UTC, mgrinko commented on src/style.css
> +  padding: 23px 0 22.5px;
магия
нужно отцентрировать текст

2019-05-31 05:56 UTC, mgrinko commented on src/style.css
> +  color: black;
это же стандартный

2019-05-31 05:57 UTC, mgrinko commented on src/style.css
> +.navigation:nth-last-child(1) {
:last-child

2019-05-31 05:57 UTC, mgrinko commented on src/style.css
> +}
а этот класс можно навесить куда угодно или только на навигационную ссылку?

2019-05-31 05:58 UTC, mgrinko commented on src/style.css
> +  border-radius: 8px;
ну почему 8px???

2019-05-31 05:58 UTC, mgrinko requested changes
жду правок

2019-05-31 06:12 UTC, Hlybchenko commented
Принято. Тогда следующую работу можно не смотреть :)  буду править по цепочке

2019-06-05 05:12 UTC, mgrinko commented on src/style.css
> +  color: black;
цвета лучше всегда писать в формате `#000`
а не словом

2019-06-05 05:12 UTC, mgrinko approved these changes

2026-03-06 11:29 UTC, closed without merging