"layout_moyo-header" PR
mate-academy/layout_moyo-header pull request #853
Opened 2021-08-12 20:35 UTC by Rocketjet

All tests passed.

2021-08-16 06:34 UTC, Rocketjet commented
- [DEMO LINK](https://Rocketjet.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Rocketjet.github.io/layout_moyo-header/report/html_report/)

2021-08-18 11:25 UTC, herkoss requested changes
Well done!👍
But it needs some refactoring)
Good luck🍀

2021-08-18 11:25 UTC, herkoss commented on src/index.html
> +      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```suggestion
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    >
```

2021-08-18 11:25 UTC, herkoss commented on src/index.html
> +        alt="logo">
```suggestion
      <img
        class="logo"
        src="images/logo.png"
        alt="logo"
      >
```

2021-08-18 11:25 UTC, herkoss commented on src/index.html
> +        alt="logo">
Fix code style here and in a whole file

2021-08-18 11:25 UTC, herkoss commented on src/index.html
> +        alt="logo">
It must be a clickable link

2021-08-18 16:36 UTC, herkoss approved these changes
Good job!👏👍

2021-08-18 16:36 UTC, herkoss commented on src/index.html
> +      >
```suggestion
        <img
          class="logo"
          src="images/logo.png"
          alt="logo"
        >
```

2024-05-29 15:35 UTC, closed without merging