Develop
mate-academy/layout_moyo-header pull request #877
Opened 2021-08-18 15:19 UTC by caelum29

- [DEMO LINK](https://caelum29.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://caelum29.github.io/layout_moyo-header/report/html_report/)

2021-08-18 16:18 UTC, herkoss requested changes
Well done!👍👏
But it needs some refactoring)
Good luck🍀

2021-08-18 16:18 UTC, herkoss commented on src/index.html
> +          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```suggestion
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    >
```

2021-08-18 16:18 UTC, herkoss commented on src/index.html
> +      </div>
Should be a clickable link

2021-08-18 16:18 UTC, herkoss commented on src/style.css
> +}
This styles is unnecessary

2021-08-19 07:59 UTC, herkoss requested changes
Add a box-shadow property, please

2021-08-19 07:59 UTC, herkoss commented on src/style.css
> +}
Where is a box-shadow?

2021-08-19 09:01 UTC, caelum29 commented on src/style.css
> +}
done

2021-08-19 10:54 UTC, herkoss approved these changes
Great!👍😊

2025-10-31 11:11 UTC, closed without merging