Moyo header denys voichenko
mate-academy/layout_moyo-header pull request #957
Opened 2021-09-18 16:49 UTC by DenCoderok

- [DEMO LINK](https://dencoderok.github.io/layout_moyo-header/src/index.html?_ijt=c7cm2qehbvbuscngrihg43qvp8)

2021-09-21 07:45 UTC, varseniuk requested changes
Посилання на test report не працює

2021-09-21 07:45 UTC, varseniuk commented on src/style.css
> +  margin-right: 10px;
```suggestion
  margin-right: 20px;
```
По дизайну відступи між елементами мають бути 20px

2021-09-21 07:45 UTC, varseniuk commented on src/style.css
> +  flex-grow: 6;
```suggestion
```
flex-grow нам тут не потрібно. Просто задай правильні марджини для елементів навігації

2021-09-21 07:45 UTC, varseniuk commented on src/style.css
> +  flex-grow: 1;
```suggestion
```

2021-09-25 11:19 UTC, DenCoderok commented
- [DEMO LINK](https://dencoderok.github.io/layout_moyo-header/src/index.html?_ijt=3i02o9eod64h2dvjat14tqdir4)
- [TEST REPORT LINK](https://dencoderok.github.io/GitHub/practica_mate/moyoHeader/layout_moyo-header/backstop_data/html_report/index.html)

2021-09-25 11:21 UTC, DenCoderok commented
я не понимаю почему не работает ссылка на тест...
запустил тест, скопировал ссылку, все как у инструкции 
но ссылка на тест не работает, где и что я делаю не так подскажите пожалуйста

2021-09-25 13:37 UTC, closed without merging