MOYO header
mate-academy/layout_moyo-header pull request #965
Opened 2021-09-29 16:43 UTC by JeniaGaidukov

https://JeniaGaidukov.github.io/layout_moyo-header/
https://JeniaGaidukov.github.io/layout_moyo-header/report/html_report/

2021-09-30 08:07 UTC, mykola-yarchuk requested changes

2021-09-30 08:07 UTC, mykola-yarchuk commented on src/index.html
> +      <span class="moyo">
спан зайвий

2021-09-30 15:34 UTC, JeniaGaidukov commented on src/index.html
> +      <span class="moyo">
Замінити на div? Чи взагалі він не потрібній?

2021-12-30 11:31 UTC, varseniuk requested changes

2021-12-30 11:31 UTC, varseniuk commented on src/index.html
> +          <img src="./images/logo.png" alt="MOYO-logo">
```suggestion
        <a
          class="moyo"
          href="#home"
        >
          <img src="./images/logo.png" alt="MOYO-logo">
```
Форматування і відступи

2021-12-30 11:31 UTC, varseniuk commented on src/index.html
> +          <li class="nav__list--low">
```suggestion
          <li class="nav__item">
```
li - це складовий елемент ul. Недоречіно використовувати його як модифікатор

2021-12-30 11:31 UTC, varseniuk commented on src/index.html
> +            >
```suggestion
            <a
              class="is-active nav__link"
              href="#apple"
            >
```
Зазвичай прийнято переносити атрибути на нові рядки, якщо їх більше трьох . Але якщо вже переносиш, то необхідно враховувати відступи правильно

2021-12-30 11:31 UTC, varseniuk commented on src/index.html
> +            >
```suggestion
            <a
              class="nav__link"
              href="#samsung"
            >
```
Це потрібно скрізь пофіксити

2022-04-01 19:12 UTC, JeniaGaidukov commented
Перевірте будь-ласка задачу. Дякую

2022-04-04 16:25 UTC, JeniaGaidukov commented on src/index.html
> +            >
Перевірте виправлення, дякую!)

2022-04-13 07:48 UTC, marina-tilniak requested changes

2022-04-13 07:48 UTC, marina-tilniak commented on src/index.html
>    <head>
```suggestion
<html lang="en">
  <head>
```

2022-04-13 07:48 UTC, marina-tilniak commented on src/index.html
> +        href="#home">
```suggestion
      <a class="moyo" href="#home">
```

2022-04-13 07:48 UTC, marina-tilniak commented on src/index.html
>  </html>
```suggestion
  </body>
</html>
```

2022-04-22 06:56 UTC, Bohdan-Maksymiuk approved these changes

2022-04-23 09:41 UTC, closed without merging